#!/usr/bin/env python3
"""Generate Kaggle kernel that clones GitHub repo for source code.

The kernel itself contains NO CUDA source code. Instead it:
1. Clones the project from GitHub
2. Configures API from Kaggle secrets (env vars)
3. Runs python -m src.main --probes-only or --pipeline
4. The multi-agent system autonomously generates CUDA code
"""
import pathlib


def generate_kernel():
    """Generate the Kaggle kernel source code."""

    # Build line by line to avoid escaping issues
    L = []  # lines

    L.append('#!/usr/bin/env python3')
    L.append('"""GPU Profiling System - Kaggle Test Kernel.')
    L.append('')
    L.append('Clones the project from GitHub, then runs the GPU profiling system.')
    L.append('The multi-agent system autonomously generates CUDA code based on targets.')
    L.append('No hardcoded CUDA source in this kernel - Agent generates everything.')
    L.append('"""')
    L.append('from __future__ import annotations')
    L.append('import json, os, shutil, subprocess, sys, time, traceback')
    L.append('from pathlib import Path')
    L.append('')
    L.append('# Redirect stdout/stderr to a log file for debugging')
    L.append('WORKING_DIR = "/kaggle/working"')
    L.append('os.makedirs(WORKING_DIR, exist_ok=True)')
    L.append('LOG_FILE = os.path.join(WORKING_DIR, "execution.log")')
    L.append('log_fh = open(LOG_FILE, "w", buffering=1)  # line-buffered')
    L.append('')
    L.append('class TeeWriter:')
    L.append('    def __init__(self, stream, file):')
    L.append('        self._stream = stream')
    L.append('        self._file = file')
    L.append('    def write(self, s):')
    L.append('        self._stream.write(s)')
    L.append('        self._file.write(s)')
    L.append('        self._file.flush()')
    L.append('    def flush(self):')
    L.append('        self._stream.flush()')
    L.append('        self._file.flush()')
    L.append('')
    L.append('sys.stdout = TeeWriter(sys.stdout, log_fh)')
    L.append('sys.stderr = TeeWriter(sys.stderr, log_fh)')
    L.append('')
    L.append('os.chdir(WORKING_DIR)')
    L.append('print(f"Working dir: {WORKING_DIR}")')
    L.append('print(f"Python: {sys.version}")')
    L.append('print(f"Log file: {LOG_FILE}")')
    L.append('')
    L.append('')
    L.append('def banner(title):')
    L.append('    print()')
    L.append('    print("=" * 60)')
    L.append('    print(f"  {title}")')
    L.append('    print("=" * 60)')
    L.append('')
    L.append('')
    L.append('def run_cmd(cmd, timeout=300, description=""):')
    L.append('    if description:')
    L.append('        print(f"  {description}")')
    L.append("    print(f\"$ {' '.join(cmd)}\")")
    L.append('    try:')
    L.append('        r = subprocess.run(cmd, capture_output=True, text=True,')
    L.append('                          timeout=timeout, cwd=WORKING_DIR)')
    L.append('        if r.stdout:')
    L.append('            out = r.stdout')
    L.append('            if len(out) > 5000:')
    L.append('                print(f"... ({len(out)} chars total, showing first 3000 + last 2000)")')
    L.append('                print(out[:3000])')
    L.append('                print("\\n... [truncated] ...\\n")')
    L.append('                print(out[-2000:])')
    L.append('            else:')
    L.append('                print(out)')
    L.append('        if r.stderr:')
    L.append('            print(f"STDERR: {r.stderr[-1000:]}")')
    L.append('        print(f"Exit code: {r.returncode}")')
    L.append('        return r.returncode == 0, r.stdout, r.stderr')
    L.append('    except subprocess.TimeoutExpired:')
    L.append('        print(f"Timeout after {timeout}s")')
    L.append('        return False, "", "Timeout"')
    L.append('    except Exception as e:')
    L.append('        print(f"Error: {e}")')
    L.append('        return False, "", str(e)')
    L.append('')
    L.append('')

    # Environment check
    L.append('def check_environment():')
    L.append('    banner("1. Environment Check")')
    L.append('    ok, out, err = run_cmd(["nvidia-smi", "-L"], description="GPU check")')
    L.append('    if not ok:')
    L.append('        print("No GPU detected -- aborting")')
    L.append('        return False')
    L.append('    ok, out, err = run_cmd(["nvcc", "--version"], description="nvcc check")')
    L.append('    if not ok:')
    L.append('        print("nvcc not found, trying install...")')
    L.append('        run_cmd(["apt-get", "update"], timeout=120)')
    L.append('        run_cmd(["apt-get", "install", "-y", "cuda-toolkit-12-0"], timeout=300)')
    L.append('        ok, out, err = run_cmd(["nvcc", "--version"])')
    L.append('        if not ok:')
    L.append('            print("nvcc still not available -- aborting")')
    L.append('            return False')
    L.append('    ok, _, _ = run_cmd(["which", "ncu"], description="ncu check")')
    L.append('    if ok:')
    L.append('        print("ncu available -- will use Nsight Compute profiling")')
    L.append('    else:')
    L.append('        print("ncu not found -- will use cudaEventElapsedTime fallback")')
    L.append('    return True')
    L.append('')
    L.append('')

    # API config
    L.append('def configure_api():')
    L.append('    banner("2. API Configuration")')
    L.append('    config_path = os.path.join(PROJECT_ROOT, "config", "api_config.json")')
    L.append('    if os.path.isfile(config_path):')
    L.append('        with open(config_path) as f:')
    L.append('            cfg = json.load(f)')
    L.append('        token = cfg.get("env", {}).get("ANTHROPIC_AUTH_TOKEN", "")')
    L.append('        if token and len(token) > 30 and not token.startswith("mock") and not token.startswith("YOUR") and len(token) > 30:')
    L.append('            print("API config already exists with valid token")')
    L.append('            return True')
    L.append('    longcat_key = os.environ.get("LONGCAT_API_KEY", "")')
    L.append('    dashscope_key = os.environ.get("DASHSCOPE_API_KEY", "")')
    L.append('    anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "")')

    # LongCat config
    L.append('    if longcat_key and len(longcat_key) > 10:')
    L.append('        env = {')
    L.append('            "ANTHROPIC_BASE_URL": "https://api.longcat.com/openaicompatible/api/v1/chat/completions",')
    L.append('            "ANTHROPIC_AUTH_TOKEN": longcat_key,')
    L.append('            "ANTHROPIC_MODEL": "longcat-flash-chat",')
    L.append('            "ANTHROPIC_REASONING_MODEL": "longcat-flash-chat",')
    L.append('            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "longcat-flash-chat",')
    L.append('            "ANTHROPIC_DEFAULT_SONNET_MODEL": "longcat-flash-chat",')
    L.append('            "ANTHROPIC_DEFAULT_OPUS_MODEL": "longcat-flash-chat"')
    L.append('        }')
    L.append('        cfg = {"env": env, "includeCoAuthoredBy": False, "effortLevel": "high"}')
    L.append('        os.makedirs(os.path.dirname(config_path), exist_ok=True)')
    L.append('        with open(config_path, "w") as f:')
    L.append('            json.dump(cfg, f, indent=2)')
    L.append('        print("API configured from LONGCAT_API_KEY")')
    L.append('        return True')

    # DashScope config
    L.append('    elif dashscope_key and len(dashscope_key) > 10:')
    L.append('        env = {')
    L.append('            "ANTHROPIC_BASE_URL": "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",')
    L.append('            "ANTHROPIC_AUTH_TOKEN": dashscope_key,')
    L.append('            "ANTHROPIC_MODEL": "qwen-max",')
    L.append('            "ANTHROPIC_REASONING_MODEL": "qwen-max",')
    L.append('            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "qwen-turbo",')
    L.append('            "ANTHROPIC_DEFAULT_SONNET_MODEL": "qwen-plus",')
    L.append('            "ANTHROPIC_DEFAULT_OPUS_MODEL": "qwen-max"')
    L.append('        }')
    L.append('        cfg = {"env": env, "includeCoAuthoredBy": False, "effortLevel": "high"}')
    L.append('        os.makedirs(os.path.dirname(config_path), exist_ok=True)')
    L.append('        with open(config_path, "w") as f:')
    L.append('            json.dump(cfg, f, indent=2)')
    L.append('        print("API configured from DASHSCOPE_API_KEY")')
    L.append('        return True')

    # Anthropic config
    L.append('    elif anthropic_key and len(anthropic_key) > 30:')
    L.append('        env = {')
    L.append('            "ANTHROPIC_BASE_URL": "https://api.anthropic.com",')
    L.append('            "ANTHROPIC_AUTH_TOKEN": anthropic_key,')
    L.append('            "ANTHROPIC_MODEL": "claude-sonnet-4-5-20250514",')
    L.append('            "ANTHROPIC_REASONING_MODEL": "claude-sonnet-4-5-20250514",')
    L.append('            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "claude-haiku-4-5-20251001",')
    L.append('            "ANTHROPIC_DEFAULT_SONNET_MODEL": "claude-sonnet-4-5-20250514",')
    L.append('            "ANTHROPIC_DEFAULT_OPUS_MODEL": "claude-opus-4-6-20250514"')
    L.append('        }')
    L.append('        cfg = {"env": env, "includeCoAuthoredBy": False, "effortLevel": "high"}')
    L.append('        os.makedirs(os.path.dirname(config_path), exist_ok=True)')
    L.append('        with open(config_path, "w") as f:')
    L.append('            json.dump(cfg, f, indent=2)')
    L.append('        print("API configured from ANTHROPIC_API_KEY")')
    L.append('        return True')

    L.append('    else:')
    L.append('        print("No LLM API keys found -- probes-only mode")')
    L.append('        return False')
    L.append('')
    L.append('')

    # Target spec
    L.append('def create_target_spec():')
    L.append('    ts_path = os.path.join(PROJECT_ROOT, "config", "target_spec.json")')
    L.append('    if not os.path.isfile(ts_path):')
    L.append('        spec = {"targets": ["dram_latency_cycles", "l2_cache_size_mb",')
    L.append('            "actual_boost_clock_mhz", "max_shmem_per_block_kb",')
    L.append('            "dram_bandwidth_gbps", "shmem_bandwidth_gbps",')
    L.append('            "bank_conflict_penalty_ratio", "sm_count"]}')
    L.append('        os.makedirs(os.path.dirname(ts_path), exist_ok=True)')
    L.append('        with open(ts_path, "w") as f:')
    L.append('            json.dump(spec, f, indent=2)')
    L.append('        print(f"Created target_spec.json: {ts_path}")')
    L.append('    else:')
    L.append('        with open(ts_path) as f:')
    L.append('            print(f"Loaded target_spec: {json.load(f)}")')
    L.append('    return ts_path')
    L.append('')
    L.append('')

    # Run probes
    L.append('def run_probes():')
    L.append('    banner("3. Hardware Probes (probes-only)")')
    L.append('    print("Running: python -m src.main --probes-only --no-docker")')
    L.append('    ok, out, err = run_cmd([')
    L.append('        sys.executable, "-m", "src.main",')
    L.append('        "--probes-only",')
    L.append('        "--output-dir", WORKING_DIR,')
    L.append('        "--state-dir", os.path.join(WORKING_DIR, ".state"),')
    L.append('        "--no-docker",')
    L.append('    ], timeout=600)')
    L.append('    print(f"Probes completed: success={ok}")')
    L.append('    return ok')
    L.append('')
    L.append('')

    # Run pipeline
    L.append('def run_pipeline(target_spec_path):')
    L.append('    banner("4. Multi-Agent Pipeline")')
    L.append('    print("Planner -> CodeGen -> MetricAnalysis -> Verification")')
    L.append('    print("Agent will autonomously generate CUDA kernels based on targets")')
    L.append('    ok, out, err = run_cmd([')
    L.append('        sys.executable, "-m", "src.main",')
    L.append('        "Profile GPU hardware parameters for the given targets",')
    L.append('        "--pipeline",')
    L.append('        "--target-spec", target_spec_path,')
    L.append('        "--output-dir", WORKING_DIR,')
    L.append('        "--state-dir", os.path.join(WORKING_DIR, ".state"),')
    L.append('        "--no-docker",')
    L.append('        "--mode", "high_autonomy",')
    L.append('        "--max-turns", "50",')
    L.append('        "--max-tokens", "16000",')
    L.append('    ], timeout=3600)')
    L.append('    print(f"Pipeline completed: success={ok}")')
    L.append('    return ok')
    L.append('')
    L.append('')

    # Analyze results
    L.append('def analyze_results():')
    L.append('    banner("5. Results Analysis")')
    L.append('    results_path = os.path.join(WORKING_DIR, "results.json")')
    L.append('    if not os.path.isfile(results_path):')
    L.append('        print(f"ERROR: results.json not found at {results_path}")')
    L.append('        print("Directory listing:")')
    L.append('        for f in sorted(os.listdir(WORKING_DIR)):')
    L.append('            print(f"  {f}")')
    L.append('        return False')
    L.append('    with open(results_path) as f:')
    L.append('        results = json.load(f)')
    L.append('    m = results.get("measurements", {})')
    L.append('    print()')
    L.append('    print("Measurements:")')
    L.append('    key_metrics = ["actual_boost_clock_mhz", "dram_latency_cycles",')
    L.append('        "l2_latency_cycles", "l1_latency_cycles", "l2_cache_size_mb",')
    L.append('        "dram_bandwidth_gbps", "shmem_bandwidth_gbps",')
    L.append('        "max_shmem_per_block_kb", "bank_conflict_penalty_ratio",')
    L.append('        "sm_count", "likely_gpu_family"]')
    L.append('    for metric in key_metrics:')
    L.append('        if metric in m:')
    L.append('            print(f"  {metric}: {m[metric]}")')
    L.append('    cv = results.get("cross_validation", {})')
    L.append('    if cv:')
    L.append('        passed = sum(1 for v in cv.values() if v is True)')
    L.append('        print(f"Cross-validation: {passed}/{len(cv)} passed")')
    L.append('    methodology = results.get("methodology", "")')
    L.append('    print(f"Methodology length: {len(methodology)} chars")')
    L.append('    return True')
    L.append('')
    L.append('')

    # Main
    L.append("# ============================================================")
    L.append("# MAIN")
    L.append("# ============================================================")
    L.append('')
    L.append('PROJECT_ROOT = None')
    L.append('all_errors = []')
    L.append('')
    L.append('try:')
    L.append('    banner("GPU Profiling System - Kaggle Test")')
    L.append('')
    L.append('    # Step 0: Clone repo')
    L.append('    banner("0. Clone Project Repository")')
    L.append('    PROJECT_ROOT = os.path.join(WORKING_DIR, "gpu_profiling_system")')
    L.append('    if os.path.isfile(os.path.join(PROJECT_ROOT, "src", "main.py")):')
    L.append('        print("Project already cloned -- skipping")')
    L.append('    else:')
    L.append('        ok, out, err = run_cmd([')
    L.append('            "git", "clone",')
    L.append('            "https://github.com/Geetie/gpu_profiling_system.git",')
    L.append('            PROJECT_ROOT,')
    L.append('        ], timeout=120, description="Clone repository")')
    L.append('        if not ok:')
    L.append('            all_errors.append("Failed to clone repository")')
    L.append('            print("ERROR: Failed to clone repository")')
    L.append('            sys.exit(1)')
    L.append('')
    L.append('    os.chdir(PROJECT_ROOT)')
    L.append('    sys.path.insert(0, PROJECT_ROOT)')
    L.append('    print(f"Project root: {PROJECT_ROOT}")')
    L.append('')
    L.append('')
    L.append('    if not check_environment():')
    L.append('        all_errors.append("Environment check failed")')
    L.append('        print("Environment check failed")')
    L.append('        sys.exit(1)')
    L.append('')
    L.append('    api_configured = configure_api()')
    L.append('')
    L.append('    target_spec_path = create_target_spec()')
    L.append('')
    L.append('    # Run probes first')
    L.append('    probe_ok = run_probes()')
    L.append('    if not probe_ok:')
    L.append('        all_errors.append("Hardware probes failed")')
    L.append('')
    L.append('    # Run pipeline if API available')
    L.append('    pipeline_ok = False')
    L.append('    if api_configured and probe_ok:')
    L.append('        pipeline_ok = run_pipeline(target_spec_path)')
    L.append('        if not pipeline_ok:')
    L.append('            all_errors.append("Pipeline failed")')
    L.append('    else:')
    L.append('        banner("Pipeline - SKIPPED (no API or probes failed)")')
    L.append('        all_errors.append(f"Pipeline skipped: api_configured={api_configured}, probe_ok={probe_ok}")')
    L.append('')
    L.append('    results_ok = analyze_results()')
    L.append('    if not results_ok:')
    L.append('        all_errors.append("Results analysis failed")')
    L.append('')
    L.append('except Exception as e:')
    L.append('    all_errors.append(f"Fatal error: {str(e)}")')
    L.append('    print(f"\\nFATAL ERROR: {e}")')
    L.append('    traceback.print_exc()')
    L.append('')
    L.append('finally:')
    L.append('    # Write execution summary')
    L.append('    banner("Execution Summary")')
    L.append('    rp = os.path.join(WORKING_DIR, "results.json")')
    L.append('    ps = "PASS" if probe_ok else "FAIL"')
    L.append('    pl = "PASS" if pipeline_ok else "SKIP"')
    L.append('    rs = "FOUND" if os.path.isfile(rp) else "MISSING"')
    L.append('    print("  Hardware probes:", ps)')
    L.append('    print("  Pipeline mode:  ", pl)')
    L.append('    print("  results.json:   ", rs)')
    L.append('    if os.path.isfile(rp):')
    L.append('        print("  Size:", os.path.getsize(rp), "bytes")')
    L.append('')
    L.append('    # Write summary file for debugging')
    L.append('    summary = {')
    L.append('        "probe_ok": probe_ok,')
    L.append('        "pipeline_ok": pipeline_ok,')
    L.append('        "results_found": os.path.isfile(rp) if "rp" in dir() else False,')
    L.append('        "api_configured": api_configured,')
    L.append('        "errors": all_errors,')
    L.append('        "project_root": PROJECT_ROOT,')
    L.append('    }')
    L.append('    summary_path = os.path.join(WORKING_DIR, "execution_summary.json")')
    L.append('    with open(summary_path, "w") as f:')
    L.append('        json.dump(summary, f, indent=2)')
    L.append('    print(f"\\nExecution summary written to: {summary_path}")')
    L.append('    if all_errors:')
    L.append('        print(f"\\nERRORS ({len(all_errors)}):")')
    L.append('        for i, err in enumerate(all_errors, 1):')
    L.append('            print(f"  {i}. {err}")')
    L.append('')
    L.append('    print("\\nTest complete.")')
    L.append('    print(f"Log file: {LOG_FILE}")')
    L.append('')
    L.append('    # Close log file')
    L.append('    log_fh.close()')

    return "\n".join(L)


# Generate and write
content = generate_kernel()
kernel_path = pathlib.Path("kaggle_kernel.py")
kernel_path.write_text(content, encoding="utf-8")
print(f"Kernel written: {len(content)} chars, {kernel_path.stat().st_size} bytes")

# Syntax check
try:
    compile(content, str(kernel_path), 'exec')
    print("Syntax check: PASSED")
except SyntaxError as e:
    print(f"Syntax check: FAILED at line {e.lineno}: {e.msg}")
