#!/usr/bin/env python3
"""GPU Profiling System - Kaggle Kernel (Real GPU Environment).

Runs the complete multi-agent GPU profiling pipeline on Kaggle's T4/P100 GPUs.
No hardcoded CUDA code — everything is generated by agents or hardware probes.

Pipeline flow:
  Environment Check → API Config → Target Spec → Hardware Probes → Agent Pipeline → Results

Usage: Run as a Kaggle notebook/kernel with GPU enabled.
Required Kaggle Secrets: LONGCAT_API_KEY, DASHSCOPE_API_KEY, or ANTHROPIC_API_KEY
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import time
import traceback
from pathlib import Path

# ── Logging ──────────────────────────────────────────────────────────

WORKING_DIR = "/kaggle/working"
os.makedirs(WORKING_DIR, exist_ok=True)
LOG_FILE = os.path.join(WORKING_DIR, "execution.log")
SESSION_LOG = os.path.join(WORKING_DIR, "session_log.jsonl")  # M3 invariant

try:
    log_fh = open(LOG_FILE, "w", buffering=1)  # line-buffered
except (OSError, IOError):
    log_fh = None  # fallback: stdout only


class TeeWriter:
    def __init__(self, stream, file):
        self._stream = stream
        self._file = file

    def write(self, s):
        self._stream.write(s)
        if self._file:
            self._file.write(s)
            self._file.flush()

    def flush(self):
        self._stream.flush()
        if self._file:
            self._file.flush()


sys.stdout = TeeWriter(sys.stdout, log_fh)
sys.stderr = TeeWriter(sys.stderr, log_fh)
os.chdir(WORKING_DIR)

print(f"Working dir: {WORKING_DIR}")
print(f"Python: {sys.version}")
print(f"Log file: {LOG_FILE}")


def banner(title):
    print()
    print("=" * 20)
    print(f"  {title}")
    print("=" * 20) 


def log_step(step_name: str, status: str, details: dict | None = None):
    """Append one line to session_log.jsonl (M3 invariant)."""
    import time as _time
    entry = {
        "timestamp": _time.strftime("%Y-%m-%dT%H:%M:%S"),
        "step": step_name,
        "status": status,
        "details": details or {},
    }
    line = json.dumps(entry)
    try:
        with open(SESSION_LOG, "a") as f:
            f.write(line + "\n")
    except (OSError, IOError):
        pass


def run_cmd(cmd, timeout=300, description="", wd=None, extra_env=None, realtime_output=True):
    """Run a shell command with timeout and output capture."""
    if description:
        print(f"  {description}")
    cwd = wd if wd else WORKING_DIR
    print(f"[cwd={cwd}] $ {' '.join(cmd)}")
    env = os.environ.copy()
    if extra_env:
        env.update(extra_env)
    
    # Generate a unique log file for this command
    import hashlib
    cmd_hash = hashlib.md5(' '.join(cmd).encode()).hexdigest()[:8]
    cmd_log_file = os.path.join(WORKING_DIR, f".cmd_{cmd_hash}.log")
    full_output = []
    full_stderr = []
    
    try:
        if realtime_output:
            # Run with real-time output
            process = subprocess.Popen(
                cmd, 
                stdout=subprocess.PIPE, 
                stderr=subprocess.PIPE, 
                text=True,
                cwd=cwd, 
                env=env,
            )
            
            # Read output in real-time with timeout
            import time
            stdout_lines = []
            stderr_lines = []
            
            print("\n=== Command Output ===")
            start_time = time.time()
            while True:
                # Check for timeout
                if time.time() - start_time > timeout:
                    process.kill()
                    raise subprocess.TimeoutExpired(cmd, timeout)
                
                # Read output with non-blocking
                import select
                ready, _, _ = select.select([process.stdout, process.stderr], [], [], 1.0)
                
                if process.stdout in ready:
                    stdout_line = process.stdout.readline()
                    if stdout_line:
                        print(stdout_line, end="")
                        stdout_lines.append(stdout_line)
                
                if process.stderr in ready:
                    stderr_line = process.stderr.readline()
                    if stderr_line:
                        print(f"STDERR: {stderr_line}", end="")
                        stderr_lines.append(stderr_line)
                
                # Check if process has exited
                if process.poll() is not None:
                    # Read any remaining output
                    while True:
                        stdout_line = process.stdout.readline()
                        if not stdout_line:
                            break
                        print(stdout_line, end="")
                        stdout_lines.append(stdout_line)
                    
                    while True:
                        stderr_line = process.stderr.readline()
                        if not stderr_line:
                            break
                        print(f"STDERR: {stderr_line}", end="")
                        stderr_lines.append(stderr_line)
                    break
            
            returncode = process.wait()
            stdout = ''.join(stdout_lines)
            stderr = ''.join(stderr_lines)
        else:
            # Run with captured output
            r = subprocess.run(
                cmd, capture_output=True, text=True,
                timeout=timeout, cwd=cwd, env=env,
            )
            returncode = r.returncode
            stdout = r.stdout
            stderr = r.stderr
        
        # Save full output to log file
        try:
            with open(cmd_log_file, "w") as log_f:
                log_f.write(f"Command: {' '.join(cmd)}\n")
                log_f.write(f"CWD: {cwd}\n")
                log_f.write(f"Exit code: {returncode}\n\n")
                
                log_f.write("STDOUT:\n")
                log_f.write(stdout)
                log_f.write("\n\nSTDERR:\n")
                log_f.write(stderr)
        except (OSError, IOError) as e:
            print(f"Failed to write command log: {e}")
        
        if not realtime_output:
            if stdout:
                out = stdout
                if len(out) > 5000:
                    # Save full output to a file so nothing is lost
                    full_out_path = os.path.join(WORKING_DIR, f".cmd_output_{cmd_hash}.log")
                    try:
                        with open(full_out_path, "w") as _f:
                            _f.write(out)
                    except (OSError, IOError):
                        pass
                    print(f"... ({len(out)} chars total, showing first 3000 + last 2000)")
                    print(out[:3000])
                    print("\n... [truncated] ...\n")
                    print(out[-2000:])
                    print(f"Full output saved to: .cmd_output_{cmd_hash}.log")
                else:
                    print(out)
            if stderr:
                print(f"STDERR: {stderr[-1000:]}")
                if len(stderr) > 1000:
                    print(f"Full stderr saved to: .cmd_{cmd_hash}.log")
        
        print(f"\nExit code: {returncode}")
        print(f"Command log: .cmd_{cmd_hash}.log")
        return returncode == 0, stdout, stderr
    except subprocess.TimeoutExpired:
        print(f"\nTimeout after {timeout}s")
        # Save timeout information to log file
        try:
            with open(cmd_log_file, "w") as log_f:
                log_f.write(f"Command: {' '.join(cmd)}\n")
                log_f.write(f"CWD: {cwd}\n")
                log_f.write(f"Error: Timeout after {timeout}s\n")
        except (OSError, IOError):
            pass
        return False, "", "Timeout"
    except Exception as e:
        print(f"\nError: {e}")
        # Save exception information to log file
        try:
            with open(cmd_log_file, "w") as log_f:
                log_f.write(f"Command: {' '.join(cmd)}\n")
                log_f.write(f"CWD: {cwd}\n")
                log_f.write(f"Error: {str(e)}\n")
                import traceback
                log_f.write(traceback.format_exc())
        except (OSError, IOError):
            pass
        return False, "", str(e)


# ── Secret Management ────────────────────────────────────────────────

def get_kaggle_secret(secret_name: str) -> str | None:
    """Read a secret from Kaggle's Secrets storage (4 methods)."""
    # Method 1: kaggle_secrets module (available in Kaggle kernels)
    masked_name = secret_name[:3] + "***" if len(secret_name) > 3 else "***"
    try:
        from kaggle_secrets import UserSecretsClient
        client = UserSecretsClient()
        val = client.get_secret(secret_name)
        if val:
            print(f"[secret] {masked_name}: found via kaggle_secrets")
            return val
    except Exception as e:
        print(f"[secret] {masked_name}: kaggle_secrets failed: {e}")

    # Method 2: /kaggle/secrets/ file mount
    secret_path = f"/kaggle/secrets/{secret_name}"
    if os.path.isfile(secret_path):
        with open(secret_path) as f:
            val = f.read().strip()
        if val:
            print(f"[secret] {masked_name}: found via file mount")
            return val

    # Method 3: Direct environment variable
    val = os.environ.get(secret_name, "")
    if val:
        print(f"[secret] {masked_name}: found via env var")
        return val

    # Method 4: /kaggle/input/ mount
    secret_input_path = f"/kaggle/input/{secret_name}"
    if os.path.isfile(secret_input_path):
        with open(secret_input_path) as f:
            val = f.read().strip()
        if val:
            print(f"[secret] {masked_name}: found via /kaggle/input")
            return val

    masked_name = secret_name[:3] + "***" if len(secret_name) > 3 else "***"
    print(f"[secret] {masked_name}: not found")
    return None


# ── Step 1: Environment Check ────────────────────────────────────────

def check_environment():
    """Verify GPU, nvcc, and optionally ncu are available."""
    banner("1. Environment Check")
    ok, out, err = run_cmd(["nvidia-smi", "-L"], description="GPU check")
    if not ok:
        print("No GPU detected -- aborting")
        return False

    # Print GPU details
    print("\nFull nvidia-smi output:")
    run_cmd(["nvidia-smi"], description="GPU details")

    ok, out, err = run_cmd(["nvcc", "--version"], description="nvcc check")
    if not ok:
        print("nvcc not found -- Kaggle GPU image should include CUDA, aborting")
        return False

    ok, _, _ = run_cmd(["which", "ncu"], description="ncu check")
    if ok:
        print("ncu available -- will use Nsight Compute profiling")
    else:
        print("ncu not found -- will use cudaEventElapsedTime fallback")

    return True


# ── Step 2: API Configuration ────────────────────────────────────────

def configure_api(project_root: str) -> bool:
    """Configure LLM API from Kaggle Secrets or environment variables.

    Tries 3 providers in order: LongCat > DashScope > Anthropic.
    Sets environment variables so ProviderManager can auto-detect.
    Writes config/api_config.json for the pipeline to use.
    """
    banner("2. API Configuration")
    config_path = os.path.join(project_root, "config", "api_config.json")

    # Check if valid config already exists
    if os.path.isfile(config_path):
        with open(config_path) as f:
            cfg = json.load(f)
        token = cfg.get("env", {}).get("ANTHROPIC_AUTH_TOKEN", "")
        if token and len(token) > 30 and not token.startswith("mock") and not token.startswith("YOUR"):
            print("API config already exists with valid token")
            # Also set env vars from existing config
            for k, v in cfg.get("env", {}).items():
                os.environ[k] = v
            return True

    # Read secrets from Kaggle Secrets storage (4 methods each)
    print("Reading secrets from Kaggle...")
    longcat_key = get_kaggle_secret("LONGCAT_API_KEY") or ""
    dashscope_key = get_kaggle_secret("DASHSCOPE_API_KEY") or ""
    anthropic_key = get_kaggle_secret("ANTHROPIC_API_KEY") or ""

    provider_configs = {}

    if longcat_key and len(longcat_key) > 10:
        # LongCat-Flash-Thinking has strongest reasoning — use for CodeGen
        # (CUDA code generation needs deep reasoning capability)
        provider_configs = {
            "provider": "longcat",
            "env": {
                "LONGCAT_API_KEY": longcat_key,
                "DASHSCOPE_API_KEY": "",
                "ANTHROPIC_API_KEY": "",
                "ANTHROPIC_BASE_URL": "https://api.longcat.chat/openai/v1/chat/completions",
                "ANTHROPIC_AUTH_TOKEN": longcat_key,
                # Main model: use thinking model for CodeGen
                "ANTHROPIC_MODEL": "LongCat-Flash-Thinking-2601",
                # Code model: use strongest reasoning model
                "ANTHROPIC_DEFAULT_SONNET_MODEL": "LongCat-Flash-Thinking-2601",
                # Verification: use strongest reasoning model
                "ANTHROPIC_DEFAULT_OPUS_MODEL": "LongCat-Flash-Thinking-2601",
                "ANTHROPIC_REASONING_MODEL": "LongCat-Flash-Thinking-2601",
                "ANTHROPIC_DEFAULT_HAIKU_MODEL": "LongCat-Flash-Thinking-2601",
            },
            "label": "LongCat API",
        }
    elif dashscope_key and len(dashscope_key) > 10:
        # qwen3.6-plus for general tasks, qwen3-coder-480b for code generation
        provider_configs = {
            "provider": "dashscope",
            "env": {
                "LONGCAT_API_KEY": "",
                "DASHSCOPE_API_KEY": dashscope_key,
                "ANTHROPIC_API_KEY": "",
                "ANTHROPIC_BASE_URL": "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",
                "ANTHROPIC_AUTH_TOKEN": dashscope_key,
                # Main model: qwen3.6-plus for Planner/MetricAnalysis
                "ANTHROPIC_MODEL": "qwen3.6-plus",
                # Code model: qwen3-coder — strongest for code generation
                "ANTHROPIC_DEFAULT_SONNET_MODEL": "qwen3-coder-480b-a35b-instruct",
                # Verification: use strongest reasoning model
                "ANTHROPIC_DEFAULT_OPUS_MODEL": "qwen3.6-plus",
                "ANTHROPIC_REASONING_MODEL": "qwen3.6-plus",
                "ANTHROPIC_DEFAULT_HAIKU_MODEL": "qwen-turbo",
            },
            "label": "DashScope (Aliyun)",
        }
    elif anthropic_key and len(anthropic_key) > 30:
        provider_configs = {
            "provider": "anthropic",
            "env": {
                "LONGCAT_API_KEY": "",
                "DASHSCOPE_API_KEY": "",
                "ANTHROPIC_API_KEY": anthropic_key,
                "ANTHROPIC_BASE_URL": "https://api.anthropic.com",
                "ANTHROPIC_AUTH_TOKEN": anthropic_key,
                "ANTHROPIC_MODEL": "claude-sonnet-4-5-20250514",
                "ANTHROPIC_REASONING_MODEL": "claude-sonnet-4-5-20250514",
                "ANTHROPIC_DEFAULT_HAIKU_MODEL": "claude-haiku-4-5-20251001",
                "ANTHROPIC_DEFAULT_SONNET_MODEL": "claude-sonnet-4-5-20250514",
                "ANTHROPIC_DEFAULT_OPUS_MODEL": "claude-opus-4-6-20250514",
            },
            "label": "Anthropic Claude",
        }

    if not provider_configs:
        print("No LLM API keys found in Kaggle Secrets -- probes-only mode")
        return False

    # Set environment variables (so ProviderManager can auto-detect)
    for k, v in provider_configs["env"].items():
        os.environ[k] = v

    # Write config file for the pipeline
    cfg = {
        "env": provider_configs["env"],
        "includeCoAuthoredBy": False,
        "effortLevel": "high",
    }
    os.makedirs(os.path.dirname(config_path), exist_ok=True)
    with open(config_path, "w") as f:
        json.dump(cfg, f, indent=2)

    print(f"API configured from {provider_configs['label']}")
    print(f"  Model: {provider_configs['env']['ANTHROPIC_MODEL']}")
    print(f"  Base URL: {provider_configs['env']['ANTHROPIC_BASE_URL']}")
    return True


# ── Step 3: Target Spec ──────────────────────────────────────────────

def create_target_spec(project_root: str) -> str:
    """Create or load target_spec.json.

    Includes 8 GPU parameters (DRAM latency, L2 cache, clock, shmem,
    bandwidth, bank conflicts, SM count).
    """
    ts_path = os.path.join(project_root, "config", "target_spec.json")
    if not os.path.isfile(ts_path):
        spec = {
            "targets": [
                "dram_latency_cycles",
                "l2_cache_size_mb",
                "actual_boost_clock_mhz",
                "max_shmem_per_block_kb",
                "dram_bandwidth_gbps",
                "shmem_bandwidth_gbps",
                "bank_conflict_penalty_ratio",
                "sm_count",
            ],
        }
        os.makedirs(os.path.dirname(ts_path), exist_ok=True)
        with open(ts_path, "w") as f:
            json.dump(spec, f, indent=2)
        print(f"Created target_spec.json: {ts_path}")
    else:
        with open(ts_path) as f:
            spec = json.load(f)
        print(f"Loaded target_spec: {spec}")
    return ts_path


# ── Step 4: Hardware Probes ──────────────────────────────────────────

def run_probes(project_root: str) -> bool:
    """Run hardware probes (--probes-only mode).

    Directly compiles and runs CUDA micro-benchmarks to measure
    GPU hardware parameters. No LLM involved.
    """
    banner("3. Hardware Probes (probes-only)")
    print("Running: python -m src.main --probes-only --no-docker")
    ok, out, err = run_cmd(
        [
            sys.executable,
            "-m",
            "src.main",
            "--probes-only",
            "--output-dir",
            WORKING_DIR,
            "--state-dir",
            os.path.join(WORKING_DIR, ".state"),
            "--no-docker",
        ],
        timeout=600,
        wd=project_root,
    )
    print(f"Probes completed: success={ok}")
    return ok


# ── Step 5: Multi-Agent Pipeline ─────────────────────────────────────

def run_pipeline(project_root: str, target_spec_path: str) -> bool:
    """Run the full multi-agent pipeline.

    Planner → CodeGen → MetricAnalysis → Verification
    Agents autonomously generate CUDA code based on targets.
    """
    banner("4. Multi-Agent Pipeline")
    print("Planner → CodeGen → MetricAnalysis → Verification")
    print("Agents will autonomously generate CUDA kernels based on targets")
    print(f"Timeout: 3600s (1 hour), overridable via PIPELINE_TIMEOUT env var")
    print("\nAgent conversation logs will be saved to: agent_logs/ directory")
    print("Check these files for detailed multi-round dialogues and error reasons")

    pipeline_timeout = int(os.environ.get("PIPELINE_TIMEOUT", "3600"))

    # Run with real-time output capture
    print("\n=== Pipeline Execution Start ===")
    print("""Note: Agent dialogue will be captured in real-time. 
Look for agent_logs/*.jsonl files for complete conversation history.""")
    print()
    print("=== Real-time Pipeline Output ===")
    print("You will see the pipeline execution status and errors below:")
    print("- Stage transitions: Planner → CodeGen → MetricAnalysis → Verification")
    print("- Tool calls: compile_cuda, run_ncu, execute_binary, etc.")
    print("- Error messages: API failures, compilation errors, etc.")
    print("- Progress updates: Each agent's current activity")
    print()
    print("=== Starting Pipeline at", time.strftime("%Y-%m-%d %H:%M:%S"))
    print("=== Command:", " ".join([
        sys.executable,
        "-m",
        "src.main",
        "Profile GPU hardware parameters for the given targets",
        "--pipeline",
        "--target-spec",
        target_spec_path,
        "--output-dir",
        WORKING_DIR,
        "--state-dir",
        os.path.join(WORKING_DIR, ".state"),
        "--no-docker",
        "--mode",
        "high_autonomy",
        "--max-turns",
        "50",
        "--max-tokens",
        "16000",
    ]))
    print("=== Timeout:", pipeline_timeout, "seconds")
    print("=== Working directory:", project_root)
    print()

    start_time = time.time()
    print(f"=== Pipeline started at {time.strftime('%Y-%m-%d %H:%M:%S')}")
    
    ok, out, err = run_cmd(
        [
            sys.executable,
            "-m",
            "src.main",
            "Profile GPU hardware parameters for the given targets",
            "--pipeline",
            "--target-spec",
            target_spec_path,
            "--output-dir",
            WORKING_DIR,
            "--state-dir",
            os.path.join(WORKING_DIR, ".state"),
            "--no-docker",
            "--mode",
            "high_autonomy",
            "--max-turns",
            "50",
            "--max-tokens",
            "16000",
        ],
        timeout=pipeline_timeout,
        wd=project_root,
        realtime_output=True  # Enable real-time output
    )
    
    end_time = time.time()
    print(f"=== Pipeline finished at {time.strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"=== Execution time: {end_time - start_time:.2f} seconds")
    print(f"=== Pipeline result: {'SUCCESS' if ok else 'FAILED'}")
    if err:
        print(f"=== Error message: {err[:500]}")
    
    print("\n=== Pipeline Execution End ===")
    print(f"Pipeline completed: success={ok}")
    
    # Check for agent logs
    state_dir = os.path.join(WORKING_DIR, ".state")
    if os.path.isdir(state_dir):
        state_files = list(Path(state_dir).rglob("*.jsonl"))
        if state_files:
            print(f"\nFound {len(state_files)} agent log files:")
            for sf in state_files:
                print(f"  - {sf.name}")
            print("\nThese files contain:")
            print("  • Multi-round dialogues between agents")
            print("  • Tool calls and their results")
            print("  • Error messages and recovery attempts")
            print("  • Stage transitions and handoffs")
    
    return ok


# ── Step 6: Results Analysis ─────────────────────────────────────────

def analyze_results() -> bool:
    """Read and display results.json."""
    banner("5. Results Analysis")
    results_path = os.path.join(WORKING_DIR, "results.json")

    if not os.path.isfile(results_path):
        print(f"ERROR: results.json not found at {results_path}")
        print("Directory listing:")
        for f in sorted(os.listdir(WORKING_DIR)):
            print(f"  {f}")
        return False

    with open(results_path) as f:
        results = json.load(f)

    # Extract measurements (may be at top level or nested)
    measurements = results.get("measurements", {})
    if not measurements:
        # Top-level numeric keys
        measurements = {
            k: v for k, v in results.items() if isinstance(v, (int, float))
        }

    print()
    print("Measurements:")
    key_metrics = [
        "actual_boost_clock_mhz",
        "dram_latency_cycles",
        "l2_latency_cycles",
        "l1_latency_cycles",
        "l2_cache_size_mb",
        "dram_bandwidth_gbps",
        "shmem_bandwidth_gbps",
        "max_shmem_per_block_kb",
        "bank_conflict_penalty_ratio",
        "sm_count",
        "likely_gpu_family",
    ]
    for metric in key_metrics:
        if metric in measurements:
            print(f"  {metric}: {measurements[metric]}")

    # Cross-validation
    cv = results.get("cross_validation", {})
    if cv:
        passed = sum(1 for v in cv.values() if v is True)
        print(f"\nCross-validation: {passed}/{len(cv)} passed")
        failed = [k for k, v in cv.items() if v is False]
        if failed:
            print(f"  Failed checks: {failed}")

    # Probe status
    probe_status = results.get("probe_status", {})
    if probe_status:
        print(f"\nProbe status:")
        for name, status in probe_status.items():
            mark = "OK" if status == "success" else "!!"
            print(f"  [{mark}] {name}: {status}")

    # Methodology
    methodology = results.get("methodology", "")
    print(f"\nMethodology length: {len(methodology)} chars")

    # Evidence files
    evidence = results.get("evidence", [])
    print(f"Evidence files: {len(evidence)}")

    return True


# ── Step 7: Copy Artifacts ───────────────────────────────────────────

def copy_artifacts(project_root: str, all_errors: list) -> None:
    """Copy audit reports and state files to working dir for download."""
    banner("6. Artifact Collection")

    # Copy audit report
    audit_dir = os.path.join(WORKING_DIR, "audit")
    src_audit = os.path.join(project_root, "audit")
    if not os.path.isdir(audit_dir) and os.path.isdir(src_audit):
        print(f"Copying audit reports from {src_audit}")
        ok, out, err = run_cmd(
            ["cp", "-r", src_audit, audit_dir],
            description="Copy audit reports",
        )
        if not ok:
            err_msg = f"Failed to copy audit reports: {err}"
            print(f"  {err_msg}")
            all_errors.append(err_msg)

    # Copy state directory (contains agent conversation logs)
    state_dir = os.path.join(WORKING_DIR, ".state")
    if os.path.isdir(state_dir):
        state_files = list(Path(state_dir).rglob("*.jsonl"))
        print(f"State files: {len(state_files)}")
        for sf in state_files:
            print(f"  {sf.name} ({sf.stat().st_size} bytes)")
        
        # Copy state files to working dir for easy download
        state_output_dir = os.path.join(WORKING_DIR, "agent_logs")
        os.makedirs(state_output_dir, exist_ok=True)
        for sf in state_files:
            dest_file = os.path.join(state_output_dir, sf.name)
            try:
                import shutil
                shutil.copy2(sf, dest_file)
                print(f"  Copied to: agent_logs/{sf.name}")
            except Exception as e:
                print(f"  Failed to copy {sf.name}: {e}")

    # List all output files
    print(f"\nOutput files in {WORKING_DIR}:")
    for f in sorted(Path(WORKING_DIR).rglob("*")):
        if f.is_file() and not f.name.startswith("."):
            print(f"  {f.relative_to(WORKING_DIR)} ({f.stat().st_size:,} bytes)")


# ============================================================
# MAIN
# ============================================================

PROJECT_ROOT = None
all_errors = []
probe_ok = False
pipeline_ok = False
api_configured = False
results_ok = False

try:
    banner("GPU Profiling System - Kaggle Test")

    # ── Step 0: Clone / locate repo ──────────────────────────────
    banner("0. Repository Setup")
    PROJECT_ROOT = os.path.join(WORKING_DIR, "gpu_profiling_system")

    if os.path.isfile(os.path.join(PROJECT_ROOT, "src", "main.py")):
        print("Project already exists -- skipping clone")
    else:
        ok, out, err = run_cmd(
            [
                "git",
                "clone",
                "https://github.com/Geetie/gpu_profiling_system.git",
                PROJECT_ROOT,
            ],
            timeout=120,
            description="Clone repository",
        )
        if not ok:
            all_errors.append("Failed to clone repository")
            print("ERROR: Failed to clone repository")
            sys.exit(1)

    os.chdir(PROJECT_ROOT)
    sys.path.insert(0, PROJECT_ROOT)
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Current dir: {os.getcwd()}")
    print(f"src/main.py exists: {os.path.isfile(os.path.join(PROJECT_ROOT, 'src', 'main.py'))}")

    # ── Step 1: Environment ──────────────────────────────────────
    env_ok = check_environment()
    if not env_ok:
        all_errors.append("Environment check failed")
        print("Environment check failed -- aborting")
    else:
        log_step("environment", "pass")

        # ── Step 2: API Config ───────────────────────────────────────
        api_configured = configure_api(PROJECT_ROOT)
        log_step("api_config", "configured" if api_configured else "skipped")

        # ── Step 3: Target Spec ──────────────────────────────────────
        target_spec_path = create_target_spec(PROJECT_ROOT)
        log_step("target_spec", "created")

        # ── Step 4: Hardware Probes (skipped — pipeline runs independently)
        # Hardware probes take ~10 min and are only for cross-validation.
        # The Pipeline's CodeGen generates and executes its own CUDA code.
        # Probes remain available via --probes-only in main.py.
        probe_ok = True  # Treat as "skipped" — pipeline will run regardless
        print("Hardware probes: SKIPPED (pipeline runs independently)")
        log_step("probes", "skipped")

        # ── Step 5: Pipeline (only if API configured) ──
        if api_configured:  
            pipeline_ok = run_pipeline(PROJECT_ROOT, target_spec_path)
            log_step("pipeline", "pass" if pipeline_ok else "fail")
            if not pipeline_ok:
                all_errors.append("Pipeline failed")
        else:
            banner("Pipeline - SKIPPED")
            msg = "Pipeline skipped: no API key"
            all_errors.append(msg)
            print(msg)
            log_step("pipeline", "skipped", {"reason": msg})

        # ── Step 6: Results ──────────────────────────────────────────
        results_ok = analyze_results()
        log_step("results", "pass" if results_ok else "fail")
        if not results_ok:
            all_errors.append("Results analysis failed")

        # ── Step 7: Collect artifacts ────────────────────────────────
        copy_artifacts(PROJECT_ROOT, all_errors)
        log_step("artifacts", "collected")

except Exception as e:
    all_errors.append(f"Fatal error: {str(e)}")
    print(f"\nFATAL ERROR: {e}")
    traceback.print_exc()

finally:
    # ── Execution Summary ────────────────────────────────────────
    banner("Execution Summary")
    rp = os.path.join(WORKING_DIR, "results.json")
    ps = "SKIP"  # Hardware probes are skipped in Kaggle mode
    pl = "PASS" if pipeline_ok else "SKIP"
    rs = "FOUND" if os.path.isfile(rp) else "MISSING"

    print(f"  Hardware probes: {ps}")
    print(f"  Pipeline mode:   {pl}")
    print(f"  results.json:    {rs}")
    print(f"  API configured:  {api_configured}")
    if os.path.isfile(rp):
        print(f"  results.json size: {os.path.getsize(rp):,} bytes")

    # Check for agent logs
    agent_logs_dir = os.path.join(WORKING_DIR, "agent_logs")
    if os.path.isdir(agent_logs_dir):
        log_files = list(Path(agent_logs_dir).glob("*.jsonl"))
        if log_files:
            print(f"  Agent logs:      {len(log_files)} files")
            for lf in log_files[:5]:  # Show first 5 files
                print(f"    - {lf.name} ({lf.stat().st_size:,} bytes)")
            if len(log_files) > 5:
                print(f"    ... and {len(log_files) - 5} more files")
        else:
            print(f"  Agent logs:      NONE")
    else:
        print(f"  Agent logs:      NONE")

    # Write summary file
    summary = {
        "probe_ok": probe_ok,
        "pipeline_ok": pipeline_ok,
        "api_configured": api_configured,
        "results_ok": results_ok,
        "results_found": os.path.isfile(rp),
        "errors": all_errors,
        "project_root": PROJECT_ROOT,
        "working_dir": WORKING_DIR,
        "log_files": [str(f.relative_to(WORKING_DIR)) for f in Path(WORKING_DIR).rglob("*.log")],
        "agent_logs": [str(f.relative_to(WORKING_DIR)) for f in Path(WORKING_DIR).rglob("agent_logs/*.jsonl")],
    }
    summary_path = os.path.join(WORKING_DIR, "execution_summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"\nExecution summary written to: {summary_path}")

    # Detailed log file information
    print("\n=== Log Files for Debugging ===")
    print("Check the following files for detailed information:")
    print("  1. execution.log         - Main execution log")
    print("  2. session_log.jsonl     - Session state changes")
    print("  3. agent_logs/*.jsonl    - Agent conversation history")
    print("  4. execution_summary.json - Execution summary")
    print("  5. results.json          - Final measurement results")
    print("\nAgent logs contain:")
    print("  • Multi-round dialogues between agents")
    print("  • Tool calls and their results")
    print("  • Error messages and recovery attempts")
    print("  • Stage transitions and handoffs")

    if all_errors:
        print(f"\nERRORS ({len(all_errors)}):")
        for i, err in enumerate(all_errors, 1):
            print(f"  {i}. {err}")

    print("\nTest complete.")
    print(f"Main log file: {LOG_FILE}")
    print(f"Agent logs directory: {os.path.join(WORKING_DIR, 'agent_logs')}")
    if log_fh:
        log_fh.close()
