"""Design principles for GPU profiling targets.

Extracted from pipeline.py to separate prompt engineering from
orchestration logic.  Each principle provides the CodeGen agent
with architectural insight, measurement strategy, anti-cheat
awareness, expected ranges, and validation criteria.

This module is a pure data lookup — no side effects.
"""
from __future__ import annotations


def get_design_principle(target: str) -> str:
    """Return design principle for a specific profiling target.

    The agent generates CUDA code based on these principles —
    no hardcoded source templates.
    """
    principles: dict[str, str] = {
        "dram_latency_cycles": _DRAM_LATENCY,
        "l2_latency_cycles": _L2_LATENCY,
        "l1_latency_cycles": _L1_LATENCY,
        "l2_cache_size_mb": _L2_CACHE_SIZE,
        "actual_boost_clock_mhz": _BOOST_CLOCK,
        "dram_bandwidth_gbps": _DRAM_BANDWIDTH,
        "max_shmem_per_block_kb": _SHMEM_CAPACITY,
        "bank_conflict_penalty_ratio": _BANK_CONFLICT,
        "shmem_bandwidth_gbps": _SHMEM_BANDWIDTH,
        "sm_count": _SM_COUNT,
        "shmem_bank_conflict_penalty_ns": _BANK_CONFLICT_NS,
        "l1_cache_size_kb": _L1_CACHE_SIZE,
        "launch__sm_count": _LAUNCH_SM_COUNT,
        "dram__bytes_read.sum.per_second": _DRAM_BYTES_READ,
        "dram__bytes_write.sum.per_second": _DRAM_BYTES_WRITE,
        "device__attribute_max_gpu_frequency_khz": _DEVICE_MAX_GPU_FREQ,
        "device__attribute_max_mem_frequency_khz": _DEVICE_MAX_MEM_FREQ,
        "device__attribute_fb_bus_width": _DEVICE_FB_BUS_WIDTH,
        "sm__throughput.avg.pct_of_peak_sustained_elapsed": _SM_THROUGHPUT,
        "gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed": _GPU_COMPUTE_MEM_THROUGHPUT,
    }
    return principles.get(target, _DEFAULT_PRINCIPLE)


_DEFAULT_PRINCIPLE = (
    "🎯 DESIGN THINKING: Custom Micro-Benchmark for '{target}'\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- Analyze the hardware resource being measured\n"
    "- Identify potential interference (cache, prefetchers, virtualization)\n"
    "- Design measurement to isolate target behavior\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Write a complete CUDA .cu file with proper includes and main()\n"
    "2. Choose appropriate timing method:\n"
    "   - clock64() for cycle-accurate timing (cache latency, compute)\n"
    "   - cudaEventElapsedTime for wall-clock timing (bandwidth, kernel execution)\n"
    "3. Use multiple trials (minimum 3) and report MEDIAN for latency, MAXIMUM for bandwidth\n"
    "4. Output must be parseable: printf(\"key: value\\n\")\n\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "📦 MANDATORY #include BLOCK (COPY THIS INTO EVERY .cu FILE)\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "Every CUDA micro-benchmark MUST start with these includes:\n\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>    // for std::sort (median calculation)\n"
    "  #include <cstring>      // for memset\n\n"
    "⚠️ If you use std::sort, you MUST #include <algorithm>.\n"
    "⚠️ If you use memset/memcpy, you MUST #include <cstring>.\n"
    "⚠️ Missing includes cause compilation errors that waste turns.\n\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "🛡️ ANTI-OPTIMIZATION REQUIREMENTS (CRITICAL — READ THIS)\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "The CUDA compiler (nvcc -O3) WILL optimize away your measurement code if you\n"
    "don't prevent it. This is the #1 cause of zero measurements.\n\n"
    "MANDATORY anti-optimization techniques:\n\n"
    "1. Use 'volatile' for ALL variables that carry measurement results:\n"
    "   volatile uint64_t start = clock64();\n"
    "   volatile uint64_t end = clock64();\n\n"
    "2. Use asm volatile memory barriers to prevent reordering:\n"
    "   asm volatile(\"\" : : : \"memory\");  // before start timer\n"
    "   asm volatile(\"\" : : : \"memory\");  // after end timer\n\n"
    "3. Use #pragma unroll 1 before ALL measurement loops:\n"
    "   #pragma unroll 1\n"
    "   for (uint64_t i = 0; i < iterations; i++) { ... }\n\n"
    "4. Use a SINK variable to consume the result and prevent dead-code elimination.\n"
    "   ⚠️ CRITICAL: asm constraint type MUST match variable size!\n\n"
    "   For 32-bit pointer-chasing (uint32_t indices):\n"
    "     uint32_t idx = 0;\n"
    "     // ... pointer-chasing loop: idx = indices[idx]; ...\n"
    "     volatile uint64_t sink64 = (uint64_t)idx;  // cast to 64-bit FIRST\n"
    "     asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");  // +l = 64-bit register\n\n"
    "   For 64-bit compute results (double, uint64_t):\n"
    "     volatile double sink = 0.0;\n"
    "     // ... compute loop ...\n"
    "     asm volatile(\"\" : \"+d\"(sink) : : \"memory\");  // +d = double register\n\n"
    "   ❌ WRONG: volatile uint32_t sink; asm volatile(\"\" : \"+l\"(sink) : : \"memory\");\n"
    "      → 'l' constraint requires 64-bit (8-byte) operand, but uint32_t is 4 bytes!\n"
    "      → This causes: 'asm operand type size(4) does not match constraint l'\n"
    "   ❌ WRONG: int sink; asm volatile(\"\" : \"+l\"(sink) : : \"memory\");\n"
    "      → int is 4 bytes, +l requires 8 bytes\n\n"
    "   CONSTRAINT CHEAT SHEET:\n"
    "   +l → 64-bit integer register (uint64_t, long long)\n"
    "   +r → generic 32-bit register (uint32_t, int, float)\n"
    "   +d → double-precision register (double)\n"
    "   +f → single-precision register (float)\n\n"
    "5. NEVER let the compiler see that the loop result is unused:\n"
    "   ❌ WRONG: for (...){ idx = arr[idx]; }  // compiler sees idx unused → removes loop\n"
    "   ✅ RIGHT: for (...){ idx = arr[idx]; } volatile uint64_t sink64 = (uint64_t)idx;\n"
    "             asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "⚠️ ANTI-CHEAT REQUIREMENTS\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "- Do NOT rely solely on cudaGetDeviceProperties or cudaDeviceGetAttribute\n"
    "  These may return virtualized data in cloud/containerized environments\n"
    "- ALWAYS measure actual hardware behavior using:\n"
    "  - clock64() for GPU core cycles\n"
    "  - cudaEventElapsedTime for GPU wall-clock time\n"
    "  - Empirical measurement (block ID sweep, pointer-chasing)\n"
    "- Use at least 2 measurement strategies and cross-validate results\n"
    "- Report confidence level and methodology used\n\n"
    "📊 EXPECTED RANGE: Research typical values for target hardware\n"
    "🔍 VALIDATION: If result is 0 or outside expected range, the compiler likely optimized away your code.\n"
    "   Add volatile/asm barriers as described above and REWRITE.\n\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "🔧 COMMON COMPILATION ERRORS AND FIXES\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "1. 'namespace std has no member sort' → Add #include <algorithm>\n"
    "2. 'asm operand type size(4) does not match constraint l' →\n"
    "   Cast 32-bit variable to uint64_t before using +l constraint:\n"
    "   volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "3. 'undefined reference to clock()' → Use clock64() instead (clock() returns 0 on Pascal+)\n"
    "4. 'cannot bind lvalue to volatile' → Remove volatile from the loop variable,\n"
    "   only use volatile for the sink and timing variables\n"
    "5. 'warning: variable was set but never used' → Add sink variable as described above\n"
)

_DRAM_LATENCY = (
    "🎯 DESIGN THINKING: DRAM Latency Measurement via Pointer-Chasing\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- DRAM latency is exposed when cache hierarchy is completely bypassed\n"
    "- Hardware prefetchers can hide latency by pre-loading data before it's needed\n"
    "- To measure TRUE latency: must defeat ALL prefetchers (streaming + stride)\n"
    "- Modern GPUs have sophisticated prefetchers that detect sequential/strided patterns\n"
    "- Random pointer-chasing creates serial dependency that prefetchers cannot predict\n\n"
    "📦 MANDATORY #include BLOCK (COPY THIS INTO YOUR .cu FILE):\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>    // for std::sort (median calculation)\n"
    "  #include <cstring>      // for memset\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Working Set: Allocate 32M uint32_t indices (=128 MB)\n"
    "   - Rationale: >> L2 cache size on ALL GPUs (typically 4-72 MB)\n"
    "   - Ensures every access misses L1, L2, and goes to DRAM\n"
    "   - Memory layout: linear array of random indices\n\n"
    "2. Access Pattern: Random permutation chain (Knuth shuffle with LCG seed)\n"
    "   - CRITICAL: Random access defeats hardware prefetchers\n"
    "   - Strided patterns (arr[i], arr[i+stride]) are detected and prefetched\n"
    "   - Random chains force serial dependency: next = array[current]\n"
    "   - Implementation: Fisher-Yates shuffle with LCG (a=1664525, c=1013904223)\n\n"
    "3. CUDA KERNEL STRUCTURE:\n"
    "   Write a __global__ kernel with these requirements:\n"
    "   - Single thread execution (threadIdx.x == 0 && blockIdx.x == 0 guard)\n"
    "   - Pointer-chasing loop: idx = indices[idx] for 10M iterations\n"
    "   - Use volatile uint32_t* indices parameter to prevent register caching\n"
    "   - Use asm volatile memory barriers before/after timing region\n"
    "   - Use volatile uint64_t for clock64() start/end variables\n"
    "   - Use #pragma unroll 1 before the pointer-chasing loop\n"
    "   - Consume final idx into 64-bit sink: volatile uint64_t sink64 = (uint64_t)idx;\n"
    "     then asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "   - Output: *cycles = (end - start) / iterations;\n"
    "   NOTE: You MUST write the complete kernel yourself — do NOT copy from examples.\n\n"
    "4. Timing Method: clock64() for cycle-accurate measurement\n"
    "   - Single thread: idx = next[idx] for 10M iterations\n"
    "   - Measure total_cycles = clock64(end) - clock64(start)\n"
    "   - latency_cycles = total_cycles / iterations\n"
    "   - MUST use clock64(), NOT clock() (returns 0 on Pascal+)\n\n"
    "5. Statistical Rigor: Run 3 trials, report MEDIAN\n"
    "   - Median eliminates outliers from context switches, thermal throttling\n"
    "   - Discard max/min if variance > 10%\n\n"
    "🛡️ ANTI-OPTIMIZATION (CRITICAL — prevents zero measurements):\n"
    "- Use 'volatile' on clock64() variables AND the sink variable\n"
    "- Use asm volatile(\"\" : : : \"memory\") barriers before/after timing region\n"
    "- Use #pragma unroll 1 before the pointer-chasing loop\n"
    "- Consume the final idx value into a 64-bit sink to prevent dead-code elimination:\n"
    "  volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "  ❌ WRONG: volatile uint32_t sink = idx; asm volatile(\"\" : \"+l\"(sink) : : \"memory\");\n"
    "     → +l requires 64-bit operand, uint32_t is 32-bit → compilation error!\n"
    "- Pass indices as 'volatile uint32_t*' to prevent register caching\n"
    "- Without these, nvcc -O3 WILL optimize away the loop and return 0\n\n"
    "⚠️ ANTI-CHEAT AWARENESS:\n"
    "- Do NOT use sequential access (prefetcher hides true latency)\n"
    "- Do NOT use strided access (hardware detects and prefetches)\n"
    "- Do NOT use cudaGetDeviceProperties — may return virtualized data\n"
    "- Do NOT measure with host timers (PCIe transfer overhead contaminates)\n"
    "- MUST use clock64() — measures GPU core cycles directly\n"
    "- MUST ensure working set >> L2 cache (test with 128 MB)\n"
    "- MUST use single thread (parallel threads pollute measurement)\n\n"
    "📊 EXPECTED RANGE: 400-800 cycles (varies by GPU generation, DDR speed)\n"
    "🔍 VALIDATION: \n"
    "- If result == 0 → compiler optimized away the loop → ADD volatile/asm barriers\n"
    "- If result < 200 cycles → prefetcher succeeded → REWRITE code\n"
    "- If result > 1000 cycles → possible measurement error → check clock64() usage\n"
    "- If variance > 10% → increase iterations or check for context switches\n\n"
    "🔧 COMMON COMPILATION ERRORS:\n"
    "- 'namespace std has no member sort' → Add #include <algorithm>\n"
    "- 'asm operand type size(4) does not match constraint l' →\n"
    "  Use volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "- 'undefined reference to clock()' → Use clock64() instead"
)

_L2_LATENCY = (
    "🎯 DESIGN THINKING: L2 Cache Latency Measurement via Pointer-Chasing\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- L2 latency is exposed when working set fits in L2 but exceeds L1\n"
    "- L2 is typically 512 KB - 72 MB on modern GPUs\n"
    "- L1 is typically 32-128 KB per SM\n"
    "- L2 is shared across all SMs, accessed via crossbar\n\n"
    "📦 MANDATORY #include BLOCK (COPY THIS INTO YOUR .cu FILE):\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>    // for std::sort (median calculation)\n"
    "  #include <cstring>      // for memset\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Working Set: 2 MB (512K uint32_t indices)\n"
    "   - Rationale: >> L1 cache (32-128 KB), << typical L2 cache\n"
    "   - Ensures L1 miss, L2 hit on every access\n\n"
    "2. Access Pattern: Random permutation chain (same as DRAM)\n"
    "   - Defeats L1 hardware prefetchers\n"
    "   - Implementation: Fisher-Yates shuffle with LCG\n\n"
    "3. CUDA KERNEL: Same structure as DRAM latency, working set = 2 MB\n"
    "4. Timing: clock64() for cycle accuracy, 10M iterations\n"
    "5. Run 3 trials, report MEDIAN\n\n"
    "🛡️ ANTI-OPTIMIZATION (CRITICAL — prevents zero measurements):\n"
    "- Use 'volatile' on clock64() variables AND sink variable\n"
    "- Use asm volatile(\"\" : : : \"memory\") barriers before/after timing\n"
    "- Use #pragma unroll 1 before the pointer-chasing loop\n"
    "- Consume final idx into 64-bit sink to prevent dead-code elimination:\n"
    "  volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "  ❌ WRONG: volatile uint32_t sink = idx; asm volatile(\"\" : \"+l\"(sink) : : \"memory\");\n"
    "     → +l requires 64-bit operand, uint32_t is 32-bit → compilation error!\n"
    "- Pass indices as 'volatile uint32_t*' to prevent register caching\n\n"
    "⚠️ ANTI-CHEAT:\n"
    "- Do NOT use sequential access (prefetcher hides latency)\n"
    "- Do NOT use working set < 64 KB (may fit in L1)\n"
    "- Do NOT use working set > L2 size (will miss to DRAM)\n\n"
    "📊 EXPECTED RANGE: 100-500 cycles\n"
    "🔍 VALIDATION: \n"
    "- If result == 0 → compiler optimized away the loop → ADD volatile/asm barriers\n"
    "- If result < 50 cycles → L1 hit → INCREASE working set\n\n"
    "🔧 COMMON COMPILATION ERRORS:\n"
    "- 'namespace std has no member sort' → Add #include <algorithm>\n"
    "- 'asm operand type size(4) does not match constraint l' →\n"
    "  Use volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "- 'undefined reference to clock()' → Use clock64() instead"
)

_L1_LATENCY = (
    "🎯 DESIGN THINKING: L1 Cache Latency Measurement via Pointer-Chasing\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- L1 cache is smallest, fastest cache (typically 32-128 KB per SM)\n"
    "- Must ensure working set fits ENTIRELY in L1\n\n"
    "📦 MANDATORY #include BLOCK (COPY THIS INTO YOUR .cu FILE):\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>    // for std::sort (median calculation)\n"
    "  #include <cstring>      // for memset\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Working Set: 8 KB (2K uint32_t indices)\n"
    "   - Rationale: << L1 cache on ALL GPUs (32-128 KB)\n"
    "2. Access Pattern: Random permutation chain\n"
    "3. CUDA KERNEL: Same structure, working set = 8 KB\n"
    "4. Timing: clock64(), 10M iterations, single thread\n"
    "5. Run 3 trials, report MEDIAN\n\n"
    "🛡️ ANTI-OPTIMIZATION (CRITICAL — prevents zero measurements):\n"
    "- Use 'volatile' on clock64() variables AND sink variable\n"
    "- Use asm volatile(\"\" : : : \"memory\") barriers before/after timing\n"
    "- Use #pragma unroll 1 before the pointer-chasing loop\n"
    "- Consume final idx into 64-bit sink to prevent dead-code elimination:\n"
    "  volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "  ❌ WRONG: volatile uint32_t sink = idx; asm volatile(\"\" : \"+l\"(sink) : : \"memory\");\n"
    "     → +l requires 64-bit operand, uint32_t is 32-bit → compilation error!\n"
    "- Pass indices as 'volatile uint32_t*' to prevent register caching\n\n"
    "⚠️ ANTI-CHEAT:\n"
    "- Do NOT use working set > 64 KB (may miss L1)\n"
    "- MUST verify working set fits in L1: size < 32 KB\n\n"
    "📊 EXPECTED RANGE: 50-300 cycles\n"
    "🔍 VALIDATION: \n"
    "- If result == 0 → compiler optimized away the loop → ADD volatile/asm barriers\n"
    "- If result > 400 cycles → L1 miss → DECREASE working set\n\n"
    "🔧 COMMON COMPILATION ERRORS:\n"
    "- 'namespace std has no member sort' → Add #include <algorithm>\n"
    "- 'asm operand type size(4) does not match constraint l' →\n"
    "  Use volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "- 'undefined reference to clock()' → Use clock64() instead"
)

_L2_CACHE_SIZE = (
    "🎯 DESIGN THINKING: L2 Cache Capacity Detection via Working-Set Sweep\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- Cache capacity is exposed by measuring latency vs working-set size\n"
    "- At cache capacity, latency jumps dramatically (cache cliff)\n"
    "- L2 miss → DRAM access causes 3-10x latency increase\n\n"
    "📦 MANDATORY #include BLOCK (COPY THIS INTO YOUR .cu FILE):\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>    // for std::sort (median calculation)\n"
    "  #include <cstring>      // for memset\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Sweep across 14 sizes: 1, 2, 4, 8, 12, 16, 20, 24, 32, 40, 48, 64, 96, 128 MB\n"
    "2. At each size: run pointer-chasing, measure cycles/access with clock64()\n"
    "3. Detect 'cliff': the size where latency jumps >3x\n"
    "4. L2 size = last size before cliff\n\n"
    "🛡️ ANTI-OPTIMIZATION (CRITICAL — prevents zero measurements):\n"
    "This is the #1 target where the compiler optimizes away the measurement loop.\n"
    "The pointer-chasing loop has no visible side effect, so nvcc -O3 removes it.\n\n"
    "MANDATORY anti-optimization for the sweep kernel:\n"
    "Write a __global__ sweep_latency kernel with these requirements:\n"
    "- Single thread execution (threadIdx.x == 0 && blockIdx.x == 0 guard)\n"
    "- Pointer-chasing loop: idx = indices[idx] for 'iterations' times\n"
    "- Use volatile uint32_t* indices parameter to prevent register caching\n"
    "- Use asm volatile memory barriers before/after timing region\n"
    "- Use volatile uint64_t for clock64() start/end variables\n"
    "- Use #pragma unroll 1 before the pointer-chasing loop\n"
    "- Consume final idx into 64-bit sink: volatile uint64_t sink64 = (uint64_t)idx;\n"
    "  then asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "- Output: *result = (end - start) / iterations;\n"
    "NOTE: You MUST write the complete kernel yourself — do NOT copy from examples.\n\n"
    "Key points:\n"
    "- 'volatile uint32_t* indices' prevents the compiler from caching indices in registers\n"
    "- '#pragma unroll 1' prevents the compiler from unrolling the loop\n"
    "- 'volatile uint64_t start/end' prevents the compiler from reordering clock64() calls\n"
    "- 'volatile uint64_t sink64 = (uint64_t)idx' casts 32-bit idx to 64-bit BEFORE asm\n"
    "- 'asm volatile(\"\" : \"+l\"(sink64) : : \"memory\")' forces the compiler to keep sink64 alive\n"
    "  ❌ WRONG: volatile uint32_t sink = idx; asm volatile(\"\" : \"+l\"(sink) : : \"memory\");\n"
    "     → +l requires 64-bit operand, uint32_t is 32-bit → compilation error!\n\n"
    "⚠️ ANTI-CHEAT:\n"
    "- MUST use random permutation to defeat prefetchers\n"
    "- MUST test enough sizes to capture cliff (minimum 10 points)\n\n"
    "📊 EXPECTED RANGE: 4-72 MB (varies by GPU)\n"
    "🔍 VALIDATION: \n"
    "- If result == 0.0 → compiler optimized away the loop → ADD volatile/asm barriers above\n"
    "- If no clear cliff → INCREASE sweep points\n\n"
    "🔧 COMMON COMPILATION ERRORS:\n"
    "- 'namespace std has no member sort' → Add #include <algorithm>\n"
    "- 'asm operand type size(4) does not match constraint l' →\n"
    "  Use volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "- 'undefined reference to clock()' → Use clock64() instead"
)

_BOOST_CLOCK = (
    "🎯 DESIGN THINKING: GPU Boost Clock Measurement via Cycle Counter\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- True frequency = GPU cycles / wall-clock time\n"
    "- Reported clock may not reflect actual runtime frequency\n\n"
    "📦 MANDATORY #include BLOCK (COPY THIS INTO YOUR .cu FILE):\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>    // for std::sort (median calculation)\n"
    "  #include <cstring>      // for memset\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Compute-Intensive Kernel: 10M iterations of arithmetic operations\n"
    "2. Dual Timing: clock64() for GPU cycles + cudaEventElapsedTime for wall-clock\n"
    "3. freq_MHz = total_cycles / elapsed_microseconds\n"
    "4. Run 3 trials, report MEDIAN\n\n"
    "🛡️ ANTI-OPTIMIZATION (CRITICAL — prevents zero measurements):\n"
    "- Use 'volatile' on the arithmetic result sink variable\n"
    "- Use asm volatile(\"\" : : : \"memory\") barriers before/after timing\n"
    "- Use #pragma unroll 1 before the compute loop\n"
    "- Consume the compute result into a volatile sink to prevent dead-code elimination\n"
    "- Example (using +d constraint for double — CORRECT for 64-bit float):\n"
    "  volatile double sink = 0.0;\n"
    "  #pragma unroll 1\n"
    "  for (int i = 0; i < 10000000; i++) { sink += 1.0 / (i + 1); }\n"
    "  asm volatile(\"\" : \"+d\"(sink) : : \"memory\");  // +d = double register (8 bytes)\n\n"
    "⚠️ ANTI-CHEAT:\n"
    "- Do NOT use cudaGetDeviceProperties — returns base/max clock, not actual\n"
    "- MUST use cudaEventElapsedTime for wall-clock timing\n"
    "- Ensure kernel is compute-bound (no global memory access)\n\n"
    "📊 EXPECTED RANGE: 1000-2500 MHz\n"
    "🔍 VALIDATION: \n"
    "- If result == 0 → compiler optimized away the compute loop → ADD volatile/asm barriers\n"
    "- If result < 500 MHz → thermal throttling or error\n\n"
    "🔧 COMMON COMPILATION ERRORS:\n"
    "- 'namespace std has no member sort' → Add #include <algorithm>\n"
    "- 'asm operand type size(4) does not match constraint l' →\n"
    "  Use volatile uint64_t sink64 = (uint64_t)idx; asm volatile(\"\" : \"+l\"(sink64) : : \"memory\");\n"
    "- 'undefined reference to clock()' → Use clock64() instead"
)

_DRAM_BANDWIDTH = (
    "🎯 DESIGN THINKING: DRAM Bandwidth Measurement via STREAM Copy\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- DRAM bandwidth is exposed by saturating memory bus with sequential access\n"
    "- Must launch enough threads to fully utilize memory controller\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. STREAM Copy: dst[i] = src[i] for 32M floats (128 MB)\n"
    "2. Launch 65535 blocks, 256 threads/block\n"
    "3. Timing: cudaEventElapsedTime(start, stop)\n"
    "4. BW_GBps = bytes_transferred / elapsed_ns * 1e9\n"
    "5. Run 3 trials, report MAXIMUM\n\n"
    "⚠️ ANTI-CHEAT:\n"
    "- Do NOT use host timers — PCIe overhead contaminates measurement\n"
    "- Do NOT use small working set (< 64 MB) — L2 cache may satisfy\n"
    "- MUST use cudaEventElapsedTime, NOT clock64()\n\n"
    "📊 EXPECTED RANGE: 200-1000+ GB/s\n"
    "🔍 VALIDATION: If result < 100 GB/s → insufficient parallelism"
)

_SHMEM_CAPACITY = (
    "🎯 DESIGN THINKING: Shared Memory Capacity via Occupancy API Sweep\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- Shared memory is a per-SM resource, partitioned among blocks\n"
    "- CUDA occupancy API directly queries this hardware limit\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Sweep sizes: 1K, 2K, 4K, 8K, 16K, 32K, 48K, 64K, 96K, 100K, 128K, 164K\n"
    "2. At each size: call cudaOccupancyMaxActiveBlocksPerMultiprocessor\n"
    "3. Max shmem where blocks_per_sm > 0 = per-block capacity\n"
    "4. Direct CUDA API query — most reliable probe in the suite\n\n"
    "⚠️ ANTI-CHEAT:\n"
    "- Do NOT rely solely on cudaGetDeviceProperties — may be virtualized\n"
    "- Occupancy API is more reliable\n\n"
    "📊 EXPECTED RANGE: 48-232 KB\n"
    "🔍 VALIDATION: If result < 16 KB → likely error"
)

_BANK_CONFLICT = (
    "🎯 DESIGN THINKING: Shared Memory Bank Conflict Penalty\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- Shared memory is divided into 32 banks\n"
    "- Concurrent accesses to same bank are serialized\n"
    "- 32-way bank conflict = 32x slowdown (worst case)\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Two-Kernel Comparison:\n"
    "   Kernel A (Strided): thread t accesses shared_mem[t * 32] — all hit bank 0\n"
    "   Kernel B (Sequential): thread t accesses shared_mem[t] — one per bank\n"
    "2. 1 block, 256 threads, __shared__ uint32_t[256]\n"
    "3. Timing: cudaEventElapsedTime (NOT clock64())\n"
    "4. ratio = strided_ms / sequential_ms\n"
    "5. Run 3 trials, report MINIMUM ratio\n\n"
    "⚠️ ANTI-CHEAT:\n"
    "- Do NOT use clock64() — insufficient resolution\n"
    "- MUST use cudaEventElapsedTime\n\n"
    "📊 EXPECTED RANGE: 2x-32x\n"
    "🔍 VALIDATION: If ratio < 1.5 → measurement error"
)

_SHMEM_BANDWIDTH = (
    "🎯 DESIGN THINKING: Shared Memory Bandwidth Measurement\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- Shared memory bandwidth is MUCH higher than DRAM (on-chip)\n"
    "- Shared memory is per-SM resource — measure per-SM bandwidth\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. 1 block, 256 threads, __shared__ uint32_t[256]\n"
    "2. Each iteration: every thread reads one element, writes one element\n"
    "3. BW = (iterations * 256 * 2 * sizeof(uint32_t)) / elapsed_us / 1000 GB/s\n"
    "4. Timing: cudaEventElapsedTime\n\n"
    "📊 EXPECTED RANGE: 5000-20000+ GB/s\n"
    "🔍 VALIDATION: If result < 1000 GB/s → likely using DRAM"
)

_SM_COUNT = (
    "🎯 DESIGN THINKING: Multi-Strategy SM Count Detection\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- SM count is fundamental GPU topology\n"
    "- Virtualization can hide SMs\n"
    "- Must cross-validate with multiple strategies\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "Strategy 1: CUDA API Query — cudaGetDeviceProperties\n"
    "Strategy 2: Block ID Sweep (Empirical) — MOST TRUSTWORTHY\n"
    "Strategy 3: Occupancy API Cross-Validation\n\n"
    "⚠️ ANTI-CHEAT:\n"
    "- Do NOT rely solely on cudaGetDeviceProperties — may be virtualized\n"
    "- MUST use empirical measurement\n"
    "- MUST cross-validate\n\n"
    "📊 EXPECTED RANGE: 8-132 SMs\n"
    "🔍 VALIDATION: If empirical < API → virtualization detected"
)

_BANK_CONFLICT_NS = (
    "🎯 DESIGN THINKING: Shared Memory Bank Conflict Absolute Penalty\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- Bank conflicts cause absolute latency increase (nanoseconds)\n"
    "- Penalty_ns = (conflict_cycles - no_conflict_cycles) / clock_MHz\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Two-Kernel Comparison (same as ratio measurement)\n"
    "2. Timing: cudaEventElapsedTime\n"
    "3. penalty_ns = strided_latency_ns - sequential_latency_ns\n"
    "4. Run 3 trials, report MEDIAN penalty\n\n"
    "📊 EXPECTED RANGE: 10-500 ns\n"
    "🔍 VALIDATION: If penalty < 0 ns → measurement error"
)

_L1_CACHE_SIZE = (
    "🎯 DESIGN THINKING: L1 Cache Capacity Detection via Working-Set Sweep\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- L1 cache capacity is exposed by latency vs working-set size\n"
    "- L1 is typically 32-128 KB per SM\n"
    "- At L1 capacity, latency jumps 2x-4x (L1 miss → L2 access)\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Sweep sizes: 1, 2, 4, 8, 16, 32, 48, 64, 96, 128, 192, 256 KB\n"
    "2. At each size: pointer-chasing, measure cycles/access\n"
    "3. Detect 'L1 Cliff': size where latency jumps >2x\n"
    "4. L1 size = last size before cliff\n\n"
    "📊 EXPECTED RANGE: 32-128 KB\n"
    "🔍 VALIDATION: If no clear cliff → INCREASE sweep points"
)

_LAUNCH_SM_COUNT = (
    "🎯 DESIGN THINKING: SM Count via Hardware Attribute Query\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- SM (Streaming Multiprocessor) count = cudaDevAttrMultiProcessorCount\n"
    "- This is the most reliable way to detect the actual SM count at runtime\n"
    "- Cross-validate with block ID sweep for anti-cheat\n\n"
    "📦 MANDATORY #include BLOCK:\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>\n"
    "  #include <cstring>\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Call cudaDeviceGetAttribute(&sm_count, cudaDevAttrMultiProcessorCount, 0)\n"
    "2. Also run block ID sweep: launch 256 blocks of 1 thread, each sets flag[blockIdx.x]\n"
    "3. Count how many blocks actually executed on the GPU\n"
    "4. Print: printf(\"launch__sm_count: %d\\n\", sm_count)\n"
    "5. Cross-validate both methods agree\n\n"
    "📊 EXPECTED RANGE: 8-132 SMs (A100=108, V100=80, P100=56)\n"
    "🔍 VALIDATION: If result == 0 → API call failed"
)

_DRAM_BYTES_READ = (
    "🎯 DESIGN THINKING: DRAM Read Bandwidth via STREAM Copy\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- The target 'dram__bytes_read.sum.per_second' measures the sustained DRAM read throughput\n"
    "- Nsight Compute collects this metric when the kernel reads from global memory\n"
    "- Use a large sequential read kernel to saturate the DRAM bus\n\n"
    "📦 MANDATORY #include BLOCK:\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>\n"
    "  #include <cstring>\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Allocate 64MB float array on device with random data\n"
    "2. Launch a read-only kernel: 65535 blocks x 256 threads, each thread reads array[idx]\n"
    "3. Use cudaEventElapsedTime for wall-clock timing\n"
    "4. Compute bandwidth = total_bytes_read / elapsed_time in bytes/second\n"
    "5. Print: printf(\"dram__bytes_read.sum.per_second: %.2f\\n\", bandwidth)\n"
    "6. Run 3 trials, report MAXIMUM\n\n"
    "⚠️ The kernel MUST perform only reads (no writes) to isolate read bandwidth.\n"
    "⚠️ Use __ldg() to ensure reads go through the load path.\n\n"
    "📊 EXPECTED RANGE: 200-1600 GB/s (depends on GPU)\n"
    "🔍 VALIDATION: If result < 50 GB/s → insufficient parallelism"
)

_DRAM_BYTES_WRITE = (
    "🎯 DESIGN THINKING: DRAM Write Bandwidth via STREAM Copy\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- The target 'dram__bytes_write.sum.per_second' measures the sustained DRAM write throughput\n"
    "- Nsight Compute collects this metric when the kernel writes to global memory\n"
    "- Use a large sequential write kernel to saturate the DRAM bus\n\n"
    "📦 MANDATORY #include BLOCK:\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>\n"
    "  #include <cstring>\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Allocate 64MB float array on device\n"
    "2. Launch a write-only kernel: 65535 blocks x 256 threads, each thread writes to array[idx]\n"
    "3. Use cudaEventElapsedTime for wall-clock timing\n"
    "4. Compute bandwidth = total_bytes_written / elapsed_time in bytes/second\n"
    "5. Print: printf(\"dram__bytes_write.sum.per_second: %.2f\\n\", bandwidth)\n"
    "6. Run 3 trials, report MAXIMUM\n\n"
    "⚠️ The kernel MUST perform only writes (no reads of the data being written) to isolate write bandwidth.\n"
    "⚠️ Use volatile pointer to prevent compiler optimization.\n\n"
    "📊 EXPECTED RANGE: 200-1600 GB/s (depends on GPU)\n"
    "🔍 VALIDATION: If result < 50 GB/s → insufficient parallelism"
)

_DEVICE_MAX_GPU_FREQ = (
    "🎯 DESIGN THINKING: Maximum GPU Clock Frequency\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- The target 'device__attribute_max_gpu_frequency_khz' is the peak GPU core clock\n"
    "- Use cudaDeviceGetAttribute with cudaDevAttrClockRate to query\n"
    "- The value is returned in kHz\n\n"
    "📦 MANDATORY #include BLOCK:\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>\n"
    "  #include <cstring>\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Call cudaDeviceGetAttribute(&clock_rate, cudaDevAttrClockRate, 0)\n"
    "2. clock_rate is in kHz — print it directly\n"
    "3. Print: printf(\"device__attribute_max_gpu_frequency_khz: %d\\n\", clock_rate)\n"
    "4. Run 3 trials for statistical confidence\n\n"
    "📊 EXPECTED RANGE: 1000000-2500000 kHz (1000-2500 MHz)\n"
    "🔍 VALIDATION: If result == 0 → API call failed"
)

_DEVICE_MAX_MEM_FREQ = (
    "🎯 DESIGN THINKING: Maximum Memory Clock Frequency\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- The target 'device__attribute_max_mem_frequency_khz' is the peak memory clock\n"
    "- Use cudaDeviceGetAttribute with cudaDevAttrMemoryClockRate to query\n"
    "- The value is returned in kHz\n\n"
    "📦 MANDATORY #include BLOCK:\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>\n"
    "  #include <cstring>\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Call cudaDeviceGetAttribute(&mem_clock, cudaDevAttrMemoryClockRate, 0)\n"
    "2. mem_clock is in kHz — print it directly\n"
    "3. Print: printf(\"device__attribute_max_mem_frequency_khz: %d\\n\", mem_clock)\n"
    "4. Run 3 trials for statistical confidence\n\n"
    "📊 EXPECTED RANGE: 500000-1600000 kHz (500-1600 MHz)\n"
    "🔍 VALIDATION: If result == 0 → API call failed"
)

_DEVICE_FB_BUS_WIDTH = (
    "🎯 DESIGN THINKING: Frame Buffer Bus Width\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- The target 'device__attribute_fb_bus_width' is the memory bus width in bits\n"
    "- Use cudaDeviceGetAttribute with cudaDevAttrMemoryBusWidth to query\n"
    "- Common values: 256, 384, 512, 4096 bits\n\n"
    "📦 MANDATORY #include BLOCK:\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>\n"
    "  #include <cstring>\n\n"
    "🔬 MEASUREMENT STRATEGY:\n"
    "1. Call cudaDeviceGetAttribute(&bus_width, cudaDevAttrMemoryBusWidth, 0)\n"
    "2. bus_width is in bits — print it directly\n"
    "3. Print: printf(\"device__attribute_fb_bus_width: %d\\n\", bus_width)\n"
    "4. Run 3 trials for statistical confidence\n\n"
    "📊 EXPECTED RANGE: 256-4096 bits\n"
    "🔍 VALIDATION: If result == 0 → API call failed"
)

_SM_THROUGHPUT = (
    "🎯 DESIGN THINKING: SM Throughput via Compute-Intensive Kernel\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- sm__throughput.avg.pct_of_peak_sustained_elapsed measures SM utilization\n"
    "- Use a compute-bound kernel with NO memory bottleneck to maximize SM throughput\n\n"
    "📦 MANDATORY #include BLOCK:\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>\n"
    "  #include <cstring>\n\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "⚠️  ARCHITECTURAL CONSTRAINTS (violating ANY = compilation BLOCKING)\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "  1. clock64() MUST be called INSIDE __global__ kernel, NEVER in main()\n"
    "     → clock64() is a __device__ intrinsic, calling from host = compile error\n"
    "     → Pass a uint64_t* device pointer to kernel, store cycle count there\n"
    "  2. Grid size MUST be sm_count*4 blocks x 256 threads per block\n"
    "  3. Use double-precision FMA (double type), NOT float\n"
    "  4. DO NOT use cudaDevAttrClockRate for peak_flops — it gives BASE clock\n"
    "     → Use actual_freq_mhz derived from clock64() inside kernel instead\n"
    "  5. WARMUP: Run kernel once before timed measurement\n"
    "  6. Compute actual percentage, NEVER output placeholder 0.0\n"
    "  7. Use volatile double* sink to prevent dead-code elimination\n"
    "  8. Use #pragma unroll 1 before the FMA loop to prevent unrolling\n\n"
    "📐 VERIFIED FORMULA (implement this step-by-step):\n"
    "  Step 1: In __global__ kernel:\n"
    "    - Record start_cycle = clock64()\n"
    "    - Perform double-precision FMA loop (many iterations)\n"
    "    - Record end_cycle = clock64()\n"
    "    - Write (end_cycle - start_cycle) to device pointer\n"
    "    - Write FMA result to volatile sink pointer\n"
    "  Step 2: In main():\n"
    "    - Query sm_count via cudaDevAttrMultiProcessorCount\n"
    "    - Query compute capability (major, minor)\n"
    "    - Determine fp64_per_sm from compute capability:\n"
    "      * sm_70 (V100): fp64_per_sm = 32\n"
    "      * sm_80 (A100): fp64_per_sm = 32\n"
    "      * sm_90 (H100): fp64_per_sm = 64\n"
    "      * Others: fp64_per_sm = 2 (consumer GPUs)\n"
    "    - Run WARMUP kernel, then timed kernel with cudaEvent timing\n"
    "    - Copy cycle count from device to host\n"
    "    - actual_freq_mhz = kernel_cycle_count / (elapsed_ms * 1000.0)\n"
    "    - peak_flops = sm_count * fp64_per_sm * actual_freq_mhz * 1e6 * 2\n"
    "    - achieved_flops = grid_size * block_size * iterations * 2 / elapsed_seconds\n"
    "    - pct = clamp(achieved_flops / peak_flops * 100, 0, 100)\n"
    "    - printf with target name and %.2f format\n\n"
    "⚠️ COMMON MISTAKES THAT CAUSE COMPILATION FAILURE:\n"
    "  ❌ Putting clock64() in main() → 'calling __device__ from __host__' error\n"
    "  ❌ Using grid_size < sm_count*4 → KERNEL QUALITY BLOCKED\n"
    "  ❌ Using float instead of double → wrong throughput measurement\n"
    "  ❌ Using cudaDevAttrClockRate instead of clock64() → wrong peak_flops\n\n"
    "📊 EXPECTED RANGE: 70-99 percent\n"
    "🔍 VALIDATION: If result < 30 → kernel is not compute-bound enough\n"
)

_GPU_COMPUTE_MEM_THROUGHPUT = (
    "🎯 DESIGN THINKING: GPU Compute-Memory Throughput via Fused Kernel\n\n"
    "📐 ARCHITECTURAL INSIGHT:\n"
    "- gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed measures\n"
    "  the combined compute and memory throughput as a percentage of peak sustained\n"
    "- Use a kernel that reads from global memory, performs arithmetic, then writes back\n\n"
    "📦 MANDATORY #include BLOCK:\n"
    "  #include <cuda_runtime.h>\n"
    "  #include <cstdio>\n"
    "  #include <cstdint>\n"
    "  #include <cstddef>\n"
    "  #include <cstdlib>\n"
    "  #include <algorithm>\n"
    "  #include <cstring>\n\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "⚠️  ARCHITECTURAL CONSTRAINTS (violating ANY = compilation BLOCKING)\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "  1. FMA chain MUST use value READ from input[i] (NOT register-only!)\n"
    "     → Register-only FMA gives ~0.09% throughput — FUNDAMENTALLY WRONG!\n"
    "     → The FMA input MUST depend on global memory read, not a register constant\n"
    "  2. Grid size MUST be sm_count*4 blocks x 256 threads per block\n"
    "  3. Use 64MB+ buffer (16M+ floats) to saturate memory bandwidth\n"
    "  4. WARMUP: Run kernel once before timed measurement\n"
    "  5. Use volatile float* output to prevent dead-code elimination\n"
    "  6. Use const float* __restrict__ input for read-only optimization\n"
    "  7. Compute actual percentage, NEVER output placeholder 0.0\n\n"
    "📐 VERIFIED FORMULA (implement this step-by-step):\n"
    "  Step 1: In __global__ kernel:\n"
    "    - Read val = input[idx] from global memory (CRITICAL!)\n"
    "    - Apply FMA chain: val = val * 1.0001f + 0.001f (multiple times)\n"
    "    - Write output[idx] = val to global memory\n"
    "    - The key: val depends on input[idx], so memory is stressed\n"
    "  Step 2: In main():\n"
    "    - Query sm_count, mem_clock_khz, bus_width_bits via cudaDeviceGetAttribute\n"
    "    - Allocate input and output buffers (both 64MB+)\n"
    "    - Initialize input buffer with cudaMemset\n"
    "    - grid_size = sm_count * 4, block_size = 256\n"
    "    - Run WARMUP kernel, then timed kernel with cudaEvent timing\n"
    "    - peak_bw = (mem_clock_khz / 1000.0) * 1e6 * (bus_width_bits / 8) * 2 / 1e9\n"
    "      (DDR factor = 2 for double data rate)\n"
    "    - achieved_bw = (2.0 * buffer_bytes) / elapsed_seconds / 1e9\n"
    "      (factor 2.0 = read + write)\n"
    "    - pct = clamp(achieved_bw / peak_bw * 100, 0, 100)\n"
    "    - printf with target name and %.2f format\n\n"
    "⚠️ COMMON MISTAKES THAT CAUSE WRONG MEASUREMENT:\n"
    "  ❌ FMA chain with register-only input → gives 0.09% (memory not stressed)\n"
    "  ❌ Missing volatile on output pointer → compiler may eliminate writes\n"
    "  ❌ Buffer too small (< 64MB) → L2 cache absorbs all reads\n"
    "  ❌ Using elapsed_ms instead of elapsed_seconds in bandwidth formula\n\n"
    "📊 EXPECTED RANGE: 40-80 percent\n"
    "🔍 VALIDATION: If result < 5 → kernel is NOT stressing memory at all\n"
)
