"""DRAM bandwidth probe — measures memory bandwidth in GB/s.

Uses a STREAM copy pattern (dst[i] = src[i]) to saturate the memory bus.
Wall-clock timing via ncu profiling — no device-side clock() needed.

Bandwidth = bytes_copied / gpu_time_ns * 1e9 (GB/s).

This is frequency-independent — no SM clock assumptions.

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

import os
import shutil
from typing import Any, Callable

from src.infrastructure.probing.kernel_templates import get_stream_copy_design_spec
from src.infrastructure.probing.probe_helpers import (
    compile_and_run,
    parse_ncu_gpu_time,
    parse_nvcc_output,
    _assess_confidence,
    _detect_arch,
)
from src.infrastructure.sandbox import SandboxRunner


def probe_dram_bandwidth(
    sandbox: SandboxRunner | None = None,
    actual_freq_mhz: float | None = None,
    code_generator: Callable[[str], str] | None = None,
    size_elements: int = 32 * 1024 * 1024,
) -> dict[str, Any] | None:
    """Measure DRAM bandwidth via STREAM copy + ncu profiling.

    Strategy:
    1. Compile and run stream_copy kernel
    2. Profile with ncu to get GPU execution time
    3. bandwidth = bytes / gpu_time_ns * 1e9

    Args:
        sandbox: SandboxRunner for compilation/execution.
        actual_freq_mhz: SM clock frequency (not used, kept for API compatibility).
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.
        size_elements: Number of elements to copy (default 32M = 128 MB).

    Returns dict with:
        dram_bandwidth_gbps: float — bandwidth in GB/s
        bytes_copied: int — total bytes transferred
        gpu_time_ns: float — GPU execution time in ns
        elements_copied: int — number of elements
        method: str — methodology
    """
    ncu = shutil.which("ncu")
    if ncu is None:
        return _run_without_ncu(sandbox, code_generator, size_elements)

    spec = get_stream_copy_design_spec()
    
    if code_generator is not None:
        source = code_generator(_build_generation_prompt(spec, size_elements))
        print("[bandwidth] Using LLM-generated CUDA source")
    else:
        source = _get_fallback_source(size_elements)
        print("[bandwidth] Using fallback CUDA source (no LLM available)")
    
    result = compile_and_run(source, sandbox=sandbox)
    if not result or not result.success:
        return None

    parsed = parse_nvcc_output(result.stdout)
    elements = parsed.get("elements", 0)
    bytes_copied = parsed.get("bytes_copied", 0)

    if not elements or not bytes_copied:
        return None

    work_dir = getattr(sandbox, "sandbox_root", None) or getattr(sandbox, "_sandbox_root", None) if sandbox else None
    binary_path = None
    if work_dir:
        for name in ["probe_binary", "stream_copy"]:
            p = os.path.join(work_dir, name)
            if os.path.exists(p):
                binary_path = p
                break

    if not binary_path:
        return _build_result(elements, bytes_copied, parsed, None)

    try:
        min_gpu_time_ns = None
        best_ncu_raw = None
        for _ in range(3):
            ncu_result = sandbox.run(
                command=ncu,
                args=["--profile-fromstart", "on", "--print-summary", "per_kernel",
                      binary_path],
                work_dir=work_dir,
            )
            if ncu_result and ncu_result.success:
                gpu_time_ns = parse_ncu_gpu_time(ncu_result.stdout + ncu_result.stderr)
                if gpu_time_ns and gpu_time_ns > 0:
                    if min_gpu_time_ns is None or gpu_time_ns < min_gpu_time_ns:
                        min_gpu_time_ns = gpu_time_ns
                        best_ncu_raw = ncu_result.stdout + ncu_result.stderr
        if min_gpu_time_ns:
            result = _build_result(elements, bytes_copied, parsed, min_gpu_time_ns)
            if result and best_ncu_raw:
                result["_ncu_raw_output"] = best_ncu_raw
            return result
    except Exception:
        pass

    gpu_time_ns = _measure_with_cuda_events(size_elements, sandbox, code_generator)
    if gpu_time_ns and gpu_time_ns > 0:
        result = _build_result(elements, bytes_copied, parsed, gpu_time_ns)
        if result:
            result["_confidence"] = round(
                _assess_confidence(
                    bytes_copied / gpu_time_ns,
                    low=50.0, high=2000.0,
                    ideal_low=100.0, ideal_high=1600.0,
                ) * 0.8, 2
            )
        return result

    return _build_result(elements, bytes_copied, parsed, None)


def _build_generation_prompt(spec, size_elements: int) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for DRAM bandwidth measurement.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

ARCHITECTURE NOTES:
{spec.architecture_notes}

PARAMETERS:
- Elements: {size_elements}
- Bytes: {size_elements * 4}

REQUIREMENTS:
1. Simple copy kernel: dst[i] = src[i]
2. Large data size to exceed L2 cache
3. Full grid launch with max blocks
4. Warmup run before measurement
5. Output must be parseable (key: value format)
6. No architecture-specific code — must work on all NVIDIA GPUs
7. Include complete main() function with error handling
"""


def _get_fallback_source(size_elements: int = 32 * 1024 * 1024) -> str:
    """Fallback CUDA source when LLM is not available.
    
    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.
    
    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.
    """
    return f"""
#include <stdio.h>
#include <cuda_runtime.h>

#define BLOCK_SIZE 256

__global__ void stream_copy_kernel(float* dst, const float* src, int n) {{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    int stride = blockDim.x * gridDim.x;
    for (int i = idx; i < n; i += stride) {{
        dst[i] = src[i];
    }}
}}

int main() {{
    int n = {size_elements};
    size_t bytes = n * sizeof(float);

    float *d_src, *d_dst;
    cudaMalloc(&d_src, bytes);
    cudaMalloc(&d_dst, bytes);

    float* h_src = (float*)malloc(bytes);
    for (int i = 0; i < n; i++) h_src[i] = (float)i;
    cudaMemcpy(d_src, h_src, bytes, cudaMemcpyHostToDevice);

    int blocks = (n + BLOCK_SIZE - 1) / BLOCK_SIZE;
    if (blocks > 65535) blocks = 65535;

    printf("elements: %d\\n", n);
    printf("bytes_copied: %zu\\n", bytes);
    printf("blocks: %d\\n", blocks);

    stream_copy_kernel<<<blocks, BLOCK_SIZE>>>(d_dst, d_src, n);
    cudaDeviceSynchronize();

    free(h_src);
    cudaFree(d_src);
    cudaFree(d_dst);
    return 0;
}}
"""


def _measure_with_cuda_events(
    size_elements: int,
    sandbox: SandboxRunner | None,
    code_generator: Callable[[str], str] | None = None,
) -> float | None:
    """Measure GPU time using cudaEventElapsedTime as ncu fallback."""
    runner = sandbox
    work_dir = getattr(runner, "sandbox_root", None) or getattr(runner, "_sandbox_root", None) if runner else None
    nvcc = shutil.which("nvcc")
    if nvcc is None or not runner or not work_dir:
        return None

    arch = _detect_arch(runner)

    source = f"""
#include <stdio.h>
#include <cuda_runtime.h>

#define BLOCK_SIZE 256

__global__ void stream_copy_kernel(float* dst, const float* src, int n) {{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    int stride = blockDim.x * gridDim.x;
    for (int i = idx; i < n; i += stride) {{
        dst[i] = src[i];
    }}
}}

int main() {{
    int n = {size_elements};
    size_t bytes = n * sizeof(float);

    float *d_src, *d_dst;
    cudaMalloc(&d_src, bytes);
    cudaMalloc(&d_dst, bytes);

    float* h_src = (float*)malloc(bytes);
    for (int i = 0; i < n; i++) h_src[i] = (float)i;
    cudaMemcpy(d_src, h_src, bytes, cudaMemcpyHostToDevice);

    int blocks = (n + BLOCK_SIZE - 1) / BLOCK_SIZE;
    if (blocks > 65535) blocks = 65535;

    stream_copy_kernel<<<blocks, BLOCK_SIZE>>>(d_dst, d_src, n);
    cudaDeviceSynchronize();

    cudaEvent_t evt_start, evt_stop;
    cudaEventCreate(&evt_start);
    cudaEventCreate(&evt_stop);

    cudaEventRecord(evt_start);
    stream_copy_kernel<<<blocks, BLOCK_SIZE>>>(d_dst, d_src, n);
    cudaEventRecord(evt_stop);
    cudaEventSynchronize(evt_stop);

    float elapsed_ms;
    cudaEventElapsedTime(&elapsed_ms, evt_start, evt_stop);

    printf("elements: %d\\n", n);
    printf("bytes_copied: %zu\\n", bytes);
    printf("gpu_time_ms: %.4f\\n", elapsed_ms);

    cudaEventDestroy(evt_start);
    cudaEventDestroy(evt_stop);
    free(h_src);
    cudaFree(d_src);
    cudaFree(d_dst);
    return 0;
}}
"""

    compile_result = runner.run(
        source_code=source,
        command=nvcc,
        args=["-o", os.path.join(work_dir, "probe_binaries", "stream_event"), "source.cu", f"-arch={arch}", "-Wno-deprecated-gpu-targets"],
        work_dir=work_dir,
    )
    if not compile_result.success:
        return None

    timed_binary = os.path.join(work_dir, "probe_binaries", "stream_event")

    min_elapsed_ms = None
    for _ in range(3):
        r = runner.run(
            command=timed_binary,
            args=[],
            work_dir=work_dir,
        )
        if r and r.success:
            p = parse_nvcc_output(r.stdout)
            elapsed_ms = p.get("gpu_time_ms", 0)
            if elapsed_ms > 0:
                if min_elapsed_ms is None or elapsed_ms < min_elapsed_ms:
                    min_elapsed_ms = elapsed_ms

    if min_elapsed_ms and min_elapsed_ms > 0:
        return min_elapsed_ms * 1_000_000

    return None


def _run_without_ncu(
    sandbox: SandboxRunner | None,
    code_generator: Callable[[str], str] | None = None,
    size_elements: int = 32 * 1024 * 1024,
) -> dict[str, Any] | None:
    """Run stream_copy without ncu — falls back to cudaEventElapsedTime."""
    gpu_time_ns = _measure_with_cuda_events(size_elements, sandbox, code_generator)

    spec = get_stream_copy_design_spec()
    
    if code_generator is not None:
        source = code_generator(_build_generation_prompt(spec, size_elements))
    else:
        source = _get_fallback_source(size_elements)
    
    result = compile_and_run(source, sandbox=sandbox)
    if not result or not result.success:
        return None
    parsed = parse_nvcc_output(result.stdout)
    elements = parsed.get("elements", 0)
    bytes_copied = parsed.get("bytes_copied", 0)
    if not elements:
        return None
    return _build_result(elements, bytes_copied, parsed, gpu_time_ns)


def _build_result(
    elements: int,
    bytes_copied: int,
    parsed: dict,
    gpu_time_ns: float | None,
) -> dict[str, Any] | None:
    """Build bandwidth result dict."""
    results: dict[str, Any] = {
        "method": "stream_copy_with_ncu_profiling",
        "elements_copied": int(elements),
        "bytes_copied": int(bytes_copied),
    }

    if "blocks" in parsed:
        results["launch_blocks"] = int(parsed["blocks"])

    if gpu_time_ns and gpu_time_ns > 0:
        results["gpu_time_ns"] = round(gpu_time_ns, 2)
        bw_gbps = bytes_copied / gpu_time_ns
        results["dram_bandwidth_gbps"] = round(bw_gbps, 2)
        results["_confidence"] = round(
            _assess_confidence(bw_gbps, low=50.0, high=2000.0,
                               ideal_low=100.0, ideal_high=1600.0), 2
        )

    return results if results.get("elements_copied") else None
