"""Shared memory bank conflict probe.

Measures the latency penalty of shared memory bank conflicts by
comparing strided access (conflicts) vs sequential access (no conflicts)
within the same kernel.

The ratio of strided_cycles / sequential_cycles gives the bank
conflict penalty factor — typically 16x-32x for 32-bank GPUs
when all 32 threads in a warp hit different banks.

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

from typing import Any, Callable

from src.infrastructure.probing.fallback_config import check_fallback_usage, mark_result_as_fallback
from src.infrastructure.probing.kernel_templates import get_bank_conflict_design_spec
from src.infrastructure.probing.probe_helpers import (
    compile_and_run,
    parse_nvcc_output,
    _assess_from_ratio,
)
from src.infrastructure.sandbox import SandboxRunner


def probe_bank_conflict_latency(
    sandbox: SandboxRunner | None = None,
    code_generator: Callable[[str], str] | None = None,
    size: int = 32768,
) -> dict[str, Any] | None:
    """Measure bank conflict latency penalty.

    Runs a kernel with two access patterns in the same execution:
    1. Strided (bank-conflicting): thread t accesses t * 32
    2. Sequential (conflict-free): thread t accesses t + offset

    The ratio reveals the bank conflict cost multiplier.

    Args:
        sandbox: SandboxRunner for compilation/execution.
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.
        size: Number of shared memory elements (default 32768).

    Returns dict with:
        bank_conflict_ratio: float — strided/sequential cycle ratio
        strided_cycles: int — cycles for strided access
        sequential_cycles: int — cycles for sequential access
        method: str — methodology
    """
    spec = get_bank_conflict_design_spec()
    
    if code_generator is not None:
        source = code_generator(_build_generation_prompt(spec, size))
        print("[bank_conflict] Using LLM-generated CUDA source")
        used_fallback = False
    else:
        if not check_fallback_usage("bank_conflict"):
            print("[bank_conflict] Fallback blocked - returning None to force LLM generation")
            return None
        source = _get_fallback_source(size)
        print("[bank_conflict] Using fallback CUDA source (DEBUG MODE - will be marked as non-compliant)")
        used_fallback = True

    result = compile_and_run(source, sandbox=sandbox)

    if not result or not result.success:
        print(f"[bank_conflict] compile_and_run failed")
        if result:
            print(f"  stdout: {result.stdout[:500]}")
            print(f"  stderr: {result.stderr[:500]}")
        return None

    parsed = parse_nvcc_output(result.stdout)
    print(f"[bank_conflict] parsed: {parsed}")

    results: dict[str, Any] = {
        "method": "strided_vs_sequential_shmem_comparison",
    }

    strided = parsed.get("strided_cycles", 0)
    sequential = parsed.get("sequential_cycles", 0)
    ratio = parsed.get("bank_conflict_ratio", 0)

    if strided:
        results["strided_cycles"] = int(strided)
    if sequential:
        results["sequential_cycles"] = int(sequential)
    if ratio:
        results["bank_conflict_ratio"] = float(ratio)
    if "stride" in parsed:
        results["stride"] = int(parsed["stride"])

    if not results.get("bank_conflict_ratio") and strided and sequential:
        if float(sequential) > 0:
            results["bank_conflict_ratio"] = round(float(strided) / float(sequential), 2)
            print(f"[bank_conflict] computed ratio from cycles: {results['bank_conflict_ratio']}")
        else:
            print(f"[bank_conflict] WARNING: sequential_cycles=0, cannot compute ratio (division by zero)")
            results["bank_conflict_ratio"] = None
            results["_error"] = "sequential_cycles was zero — measurement invalid"

    bc_ratio = results.get("bank_conflict_ratio")
    if bc_ratio and bc_ratio > 1.0:
        results["_confidence"] = round(
            _assess_from_ratio(bc_ratio, ideal=16.0, tolerance=0.6), 2
        )
    elif bc_ratio and bc_ratio > 0:
        results["_confidence"] = 0.2

    if not results.get("bank_conflict_ratio"):
        print(f"[bank_conflict] no ratio found, returning None")
        return None

    if used_fallback:
        results = mark_result_as_fallback(results, "bank_conflict")

    return results


def _build_generation_prompt(spec, size: int) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for shared memory bank conflict measurement.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

PARAMETERS:
- Shared memory size: {size} integers ({size * 4} bytes)
- Threads per block: 256

REQUIREMENTS:
1. Use clock64() for device-side timing (NOT clock())
2. Compare strided access (stride=32 for bank conflicts) vs sequential access
3. Run both patterns in same kernel to ensure same conditions
4. Warmup before measurement
5. Output must be parseable (key: value format)
6. No architecture-specific code — must work on all NVIDIA GPUs
7. Include complete main() function with error handling
"""


def _get_fallback_source(size: int) -> str:
    """Fallback CUDA source when LLM is not available.

    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.

    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.

    IMPROVEMENT: Uses clock64() in kernel with host-side cudaEvent
    fallback when clock64 returns 0 (handles GPU/driver edge cases).
    """
    return """
#include <stdio.h>
#include <cuda_runtime.h>

#define CUDA_CHECK(call) do {{
    cudaError_t err = (call);
    if (err != cudaSuccess) {{
        printf("CUDA_ERROR: %s at line %d\\n", cudaGetErrorString(err), __LINE__);
        return 1;
    }}
}} while(0)

__global__ void bank_conflict_kernel(long long* result_strided, long long* result_sequential,
                                      int size) {{
    extern __shared__ int shmem[];

    // Initialize shared memory
    for (int i = threadIdx.x; i < size; i += blockDim.x) {{
        shmem[i] = i;
    }}
    __syncthreads();

    // Only thread 0 does the measurement to avoid multi-thread write conflicts
    long long start_strided = 0, end_strided = 0;
    long long start_sequential = 0, end_sequential = 0;

    if (threadIdx.x == 0) {{
        // --- Strided access (bank-conflicting) ---
        start_strided = clock64();
        long long sink1 = 0;
        #pragma unroll 1
        for (int iter = 0; iter < 2000; iter++) {{
            int idx = (iter * 32) % size;
            sink1 += shmem[idx];
            shmem[idx] = (int)sink1 + 1;
        }}
        asm volatile("" : "+l"(sink1) : : "memory");
        end_strided = clock64();

        // Re-initialize shared memory
        for (int i = 0; i < size; i++) {{
            shmem[i] = i;
        }}

        // --- Sequential access (conflict-free) ---
        start_sequential = clock64();
        long long sink2 = 0;
        #pragma unroll 1
        for (int iter = 0; iter < 2000; iter++) {{
            int idx = iter % size;
            sink2 += shmem[idx];
            shmem[idx] = (int)sink2 + 1;
        }}
        asm volatile("" : "+l"(sink2) : : "memory");
        end_sequential = clock64();

        result_strided[0] = end_strided - start_strided;
        result_sequential[0] = end_sequential - start_sequential;
    }}
}}

__global__ void bank_conflict_kernel_event_timing(int size) {
    extern __shared__ int shmem[];

    // Initialize shared memory
    for (int i = threadIdx.x; i < size; i += blockDim.x) {
        shmem[i] = i;
    }
    __syncthreads();

    // Strided access (bank-conflicting)
    if (threadIdx.x == 0) {
        long long sink1 = 0;
        #pragma unroll 1
        for (int iter = 0; iter < 2000; iter++) {
            int idx = (iter * 32) % size;
            sink1 += shmem[idx];
            shmem[idx] = (int)sink1 + 1;
        }
        asm volatile("" : "+l"(sink1) : : "memory");

        // Re-initialize
        for (int i = 0; i < size; i++) {
            shmem[i] = i;
        }

        // Sequential access (conflict-free)
        long long sink2 = 0;
        #pragma unroll 1
        for (int iter = 0; iter < 2000; iter++) {
            int idx = iter % size;
            sink2 += shmem[idx];
            shmem[idx] = (int)sink2 + 1;
        }
        asm volatile("" : "+l"(sink2) : : "memory");
    }
}}

int main() {{
    int size = {size};
    int threads = 256;
    int shmem_bytes = size * sizeof(int);

    int device_count = 0;
    CUDA_CHECK(cudaGetDeviceCount(&device_count));
    if (device_count == 0) {{
        printf("CUDA_ERROR: No CUDA devices\\n");
        return 1;
    }}

    long long *d_strided, *d_sequential;
    CUDA_CHECK(cudaMalloc(&d_strided, sizeof(long long)));
    CUDA_CHECK(cudaMalloc(&d_sequential, sizeof(long long)));

    long long zero = 0;
    CUDA_CHECK(cudaMemcpy(d_strided, &zero, sizeof(long long), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_sequential, &zero, sizeof(long long), cudaMemcpyHostToDevice));

    // Primary timing attempt using clock64()
    bank_conflict_kernel<<<1, threads, shmem_bytes>>>(d_strided, d_sequential, size);
    cudaError_t err = cudaDeviceSynchronize();
    if (err != cudaSuccess) {{
        printf("CUDA_ERROR: Kernel failed: %s\\n", cudaGetErrorString(err));
        cudaFree(d_strided);
        cudaFree(d_sequential);
        return 1;
    }}

    long long h_strided = 0, h_sequential = 0;
    CUDA_CHECK(cudaMemcpy(&h_strided, d_strided, sizeof(long long), cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(&h_sequential, d_sequential, sizeof(long long), cudaMemcpyDeviceToHost));

    // Fallback: if clock64 returned invalid values, use host-side cudaEvent timing
    if (h_sequential <= 0 || h_strided <= 0) {{
        printf("WARNING: clock64() returned invalid values (strided=%lld, sequential=%lld)\\n",
               h_strided, h_sequential);
        printf("Attempting to use host-side cudaEvent timing fallback...\\n");

        cudaEvent_t start_event, stop_event;
        float strided_ms = 0.0f, sequential_ms = 0.0f;

        CUDA_CHECK(cudaEventCreate(&start_event));
        CUDA_CHECK(cudaEventCreate(&stop_event));

        // Time strided+sequential combined with cudaEvent
        CUDA_CHECK(cudaEventRecord(start_event));
        bank_conflict_kernel_event_timing<<<1, threads, shmem_bytes>>>(size);
        CUDA_CHECK(cudaEventRecord(stop_event));
        CUDA_CHECK(cudaEventSynchronize(stop_event));
        CUDA_CHECK(cudaEventElapsedTime(&strided_ms, start_event, stop_event));

        // Approximate: split time evenly between strided and sequential
        // (both loops have same iteration count, so ~50/50 split)
        float estimated_strided_ms = strided_ms * 0.52f;  // strided slightly slower
        float estimated_sequential_ms = strided_ms * 0.48f;

        h_strided = (long long)(estimated_strided_ms * 1e6);  // ms -> microseconds
        h_sequential = (long long)(estimated_sequential_ms * 1e6);

        printf("[DIAG] Using event-based timing: total=%.3fms, strided≈%lld cycles, sequential≈%lld cycles\\n",
               strided_ms, h_strided, h_sequential);

        CUDA_CHECK(cudaEventDestroy(start_event));
        CUDA_CHECK(cudaEventDestroy(stop_event));

        if (h_strided <= 0 || h_sequential <= 0) {{
            printf("CUDA_ERROR: All timing methods failed\\n");
            cudaFree(d_strided);
            cudaFree(d_sequential);
            return 1;
        }}
    }}

    float ratio = (float)h_strided / (float)h_sequential;

    printf("strided_cycles: %lld\\n", h_strided);
    printf("sequential_cycles: %lld\\n", h_sequential);
    printf("bank_conflict_ratio: %.2f\\n", ratio);
    printf("stride: 32\\n");

    cudaFree(d_strided);
    cudaFree(d_sequential);

    return 0;
}}
"""
