"""Shared memory bank conflict probe.

Measures the latency penalty of shared memory bank conflicts by
comparing strided access (conflicts) vs sequential access (no conflicts)
within the same kernel.

The ratio of strided_cycles / sequential_cycles gives the bank
conflict penalty factor — typically 16x-32x for 32-bank GPUs
when all 32 threads in a warp hit different banks.

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

from typing import Any, Callable

from src.infrastructure.probing.kernel_templates import get_bank_conflict_design_spec
from src.infrastructure.probing.probe_helpers import (
    compile_and_run,
    parse_nvcc_output,
    _assess_from_ratio,
)
from src.infrastructure.sandbox import SandboxRunner


def probe_bank_conflict_latency(
    sandbox: SandboxRunner | None = None,
    code_generator: Callable[[str], str] | None = None,
    size: int = 32768,
) -> dict[str, Any] | None:
    """Measure bank conflict latency penalty.

    Runs a kernel with two access patterns in the same execution:
    1. Strided (bank-conflicting): thread t accesses t * 32
    2. Sequential (conflict-free): thread t accesses t + offset

    The ratio reveals the bank conflict cost multiplier.

    Args:
        sandbox: SandboxRunner for compilation/execution.
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.
        size: Number of shared memory elements (default 32768).

    Returns dict with:
        bank_conflict_ratio: float — strided/sequential cycle ratio
        strided_cycles: int — cycles for strided access
        sequential_cycles: int — cycles for sequential access
        method: str — methodology
    """
    spec = get_bank_conflict_design_spec()
    
    if code_generator is not None:
        source = code_generator(_build_generation_prompt(spec, size))
        print("[bank_conflict] Using LLM-generated CUDA source")
    else:
        source = _get_fallback_source(size)
        print("[bank_conflict] Using fallback CUDA source (no LLM available)")
    
    result = compile_and_run(source, sandbox=sandbox)

    if not result or not result.success:
        print(f"[bank_conflict] compile_and_run failed")
        if result:
            print(f"  stdout: {result.stdout[:500]}")
            print(f"  stderr: {result.stderr[:500]}")
        return None

    parsed = parse_nvcc_output(result.stdout)
    print(f"[bank_conflict] parsed: {parsed}")

    results: dict[str, Any] = {
        "method": "strided_vs_sequential_shmem_comparison",
    }

    strided = parsed.get("strided_cycles", 0)
    sequential = parsed.get("sequential_cycles", 0)
    ratio = parsed.get("bank_conflict_ratio", 0)

    if strided:
        results["strided_cycles"] = int(strided)
    if sequential:
        results["sequential_cycles"] = int(sequential)
    if ratio:
        results["bank_conflict_ratio"] = float(ratio)
    if "stride" in parsed:
        results["stride"] = int(parsed["stride"])

    if not results.get("bank_conflict_ratio") and strided and sequential:
        if float(sequential) > 0:
            results["bank_conflict_ratio"] = round(float(strided) / float(sequential), 2)
            print(f"[bank_conflict] computed ratio from cycles: {results['bank_conflict_ratio']}")
        else:
            print(f"[bank_conflict] WARNING: sequential_cycles=0, cannot compute ratio (division by zero)")
            results["bank_conflict_ratio"] = None
            results["_error"] = "sequential_cycles was zero — measurement invalid"

    bc_ratio = results.get("bank_conflict_ratio")
    if bc_ratio and bc_ratio > 1.0:
        results["_confidence"] = round(
            _assess_from_ratio(bc_ratio, ideal=16.0, tolerance=0.6), 2
        )
    elif bc_ratio and bc_ratio > 0:
        results["_confidence"] = 0.2

    if not results.get("bank_conflict_ratio"):
        print(f"[bank_conflict] no ratio found, returning None")
    return results if results.get("bank_conflict_ratio") else None


def _build_generation_prompt(spec, size: int) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for shared memory bank conflict measurement.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

PARAMETERS:
- Shared memory size: {size} integers ({size * 4} bytes)
- Threads per block: 256

REQUIREMENTS:
1. Use clock64() for device-side timing (NOT clock())
2. Compare strided access (stride=32 for bank conflicts) vs sequential access
3. Run both patterns in same kernel to ensure same conditions
4. Warmup before measurement
5. Output must be parseable (key: value format)
6. No architecture-specific code — must work on all NVIDIA GPUs
7. Include complete main() function with error handling
"""


def _get_fallback_source(size: int) -> str:
    """Fallback CUDA source when LLM is not available.
    
    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.
    
    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.
    """
    return f"""
#include <stdio.h>
#include <cuda_runtime.h>

__global__ void bank_conflict_kernel(int* result_strided, int* result_sequential, int size) {{
    extern __shared__ int shmem[];
    
    int tid = threadIdx.x;
    int stride = 32;
    
    for (int i = 0; i < size; i += blockDim.x) {{
        if (i + tid < size) {{
            shmem[i + tid] = i + tid;
        }}
    }}
    __syncthreads();
    
    long long start_strided = clock64();
    for (int iter = 0; iter < 1000; iter++) {{
        int idx = (tid * stride) % size;
        int val = shmem[idx];
        shmem[idx] = val + 1;
    }}
    long long end_strided = clock64();
    __syncthreads();
    
    for (int i = 0; i < size; i += blockDim.x) {{
        if (i + tid < size) {{
            shmem[i + tid] = i + tid;
        }}
    }}
    __syncthreads();
    
    long long start_sequential = clock64();
    for (int iter = 0; iter < 1000; iter++) {{
        int idx = tid;
        int val = shmem[idx];
        shmem[idx] = val + 1;
    }}
    long long end_sequential = clock64();
    
    if (tid == 0) {{
        result_strided[0] = (int)(end_strided - start_strided);
        result_sequential[0] = (int)(end_sequential - start_sequential);
    }}
}}

int main() {{
    int size = {size};
    int threads = 256;
    int shmem_bytes = size * sizeof(int);
    
    int *d_strided, *d_sequential;
    cudaMalloc(&d_strided, sizeof(int));
    cudaMalloc(&d_sequential, sizeof(int));
    
    bank_conflict_kernel<<<1, threads, shmem_bytes>>>(d_strided, d_sequential, size);
    cudaDeviceSynchronize();
    
    int h_strided, h_sequential;
    cudaMemcpy(&h_strided, d_strided, sizeof(int), cudaMemcpyDeviceToHost);
    cudaMemcpy(&h_sequential, d_sequential, sizeof(int), cudaMemcpyDeviceToHost);
    
    float ratio = (float)h_strided / (float)h_sequential;
    
    printf("strided_cycles: %d\\n", h_strided);
    printf("sequential_cycles: %d\\n", h_sequential);
    printf("bank_conflict_ratio: %.2f\\n", ratio);
    printf("stride: 32\\n");
    
    cudaFree(d_strided);
    cudaFree(d_sequential);
    
    return 0;
}}
"""
