"""L2 cache capacity probe — working-set sweep with cliff detection.

Measures L2 cache capacity by sweeping the working set size and
detecting the latency "cliff" — the point where latency jumps sharply
because the working set no longer fits in L2 cache.

The sweep runs the pointer chasing kernel at progressively larger
sizes and analyzes the latency curve for discontinuities.

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

from typing import Any, Callable

from src.infrastructure.probing.kernel_templates import get_working_set_sweep_design_spec
from src.infrastructure.probing.probe_helpers import (
    compile_and_run,
    parse_nvcc_output,
    _assess_from_ratio,
)
from src.infrastructure.sandbox import SandboxRunner


def probe_l2_cache_capacity(
    sandbox: SandboxRunner | None = None,
    code_generator: Callable[[str], str] | None = None,
) -> dict[str, Any] | None:
    """Measure L2 cache capacity via working-set sweep.

    Sweeps working set sizes from 1 MB to 128 MB, measuring latency
    at each point. The capacity is identified at the "cliff" — where
    latency jumps by >3x, indicating cache overflow.

    Args:
        sandbox: SandboxRunner for compilation/execution.
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.

    Returns dict with:
        l2_cache_size_mb: float — estimated L2 capacity in MB
        l2_cache_size_kb: float — estimated L2 capacity in KB
        sweep_data: dict — latency at each working set size
        cliff_index: int — index where capacity cliff was detected
        method: str — methodology
    """
    sizes_elements = [
        256 * 1024,
        512 * 1024,
        1024 * 1024,
        2 * 1024 * 1024,
        3 * 1024 * 1024,
        4 * 1024 * 1024,
        5 * 1024 * 1024,
        6 * 1024 * 1024,
        8 * 1024 * 1024,
        10 * 1024 * 1024,
        12 * 1024 * 1024,
        16 * 1024 * 1024,
        24 * 1024 * 1024,
        32 * 1024 * 1024,
    ]

    sweep_data: list[dict[str, float]] = []
    spec = get_working_set_sweep_design_spec()

    for size_elem in sizes_elements:
        if code_generator is not None:
            source = code_generator(_build_generation_prompt(spec, size_elem))
            print(f"[cache_capacity] Using LLM-generated CUDA source for {size_elem}")
        else:
            source = _get_fallback_source(size_elem)
            print(f"[cache_capacity] Using fallback CUDA source for {size_elem}")
        
        result = compile_and_run(source, sandbox=sandbox)
        if result and result.success:
            parsed = parse_nvcc_output(result.stdout)
            cpa = parsed.get("cycles_per_access", 0)
            size_bytes = parsed.get("size_bytes", size_elem * 4)
            if cpa > 0:
                sweep_data.append({
                    "size_bytes": int(size_bytes),
                    "size_mb": round(size_bytes / (1024 * 1024), 2),
                    "cycles_per_access": round(cpa, 2),
                })

    if not sweep_data:
        return None

    cliff_index = _find_capacity_cliff(sweep_data)
    l2_size_bytes = 0
    cliff_ratio = 0.0

    if cliff_index > 0 and cliff_index < len(sweep_data):
        l2_size_bytes = int(sweep_data[cliff_index - 1]["size_bytes"])
        cliff_ratio = sweep_data[cliff_index]["cycles_per_access"] / \
                      sweep_data[cliff_index - 1]["cycles_per_access"] \
                      if sweep_data[cliff_index - 1]["cycles_per_access"] > 0 else 0.0
    elif sweep_data:
        min_cpa = min(d["cycles_per_access"] for d in sweep_data)
        for i, d in enumerate(sweep_data):
            if d["cycles_per_access"] > min_cpa * 2.5:
                l2_size_bytes = int(sweep_data[i - 1]["size_bytes"]) if i > 0 else 0
                cliff_index = i
                cliff_ratio = d["cycles_per_access"] / min_cpa if min_cpa > 0 else 0.0
                break

    results: dict[str, Any] = {
        "sweep_data": sweep_data,
        "cliff_index": cliff_index,
        "method": "working_set_sweep_with_cliff_detection",
    }

    if cliff_ratio > 0:
        results["_confidence"] = round(
            _assess_from_ratio(cliff_ratio, ideal=6.0, tolerance=0.6), 2
        )
    elif sweep_data:
        results["_confidence"] = 0.3

    if l2_size_bytes > 0:
        results["l2_cache_size_mb"] = round(l2_size_bytes / (1024 * 1024), 4)
        results["l2_cache_size_kb"] = round(l2_size_bytes / 1024, 2)

    return results


def _find_capacity_cliff(sweep_data: list[dict[str, float]]) -> int:
    """Find the index where latency jumps most dramatically."""
    if len(sweep_data) < 2:
        return 0

    max_ratio = 0.0
    cliff_idx = 0

    for i in range(1, len(sweep_data)):
        prev_cpa = sweep_data[i - 1]["cycles_per_access"]
        curr_cpa = sweep_data[i]["cycles_per_access"]
        if prev_cpa > 0:
            ratio = curr_cpa / prev_cpa
            if ratio > max_ratio:
                max_ratio = ratio
                cliff_idx = i

    return cliff_idx


def _build_generation_prompt(spec, size_elements: int) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for cache capacity detection via working-set sweep.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

PARAMETERS:
- Array size: {size_elements} integers ({size_elements * 4} bytes)
- Iterations: 5000

REQUIREMENTS:
1. Use clock64() for device-side timing (NOT clock())
2. Build random permutation on host to defeat hardware prefetcher
3. Make chain circular: last element points back to first
4. Warmup: traverse chain 100 times before timing
5. Write result to device memory to prevent dead-code elimination
6. Output must be parseable (key: value format)
7. No architecture-specific code — must work on all NVIDIA GPUs
8. Include complete main() function with error handling
"""


def _get_fallback_source(size_elements: int) -> str:
    """Fallback CUDA source when LLM is not available.
    
    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.
    
    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.
    """
    return f"""
#include <stdio.h>
#include <cuda_runtime.h>
#include <stdlib.h>

__global__ void pointer_chase_kernel(int* array, int* result, int size, int iterations) {{
    int idx = 0;
    for (int i = 0; i < iterations; i++) {{
        idx = array[idx];
    }}
    result[0] = idx;
}}

int main() {{
    int size = {size_elements};
    int iterations = 5000;
    
    int* h_array = (int*)malloc(size * sizeof(int));
    for (int i = 0; i < size; i++) h_array[i] = i;
    
    srand(42);
    for (int i = size - 1; i > 0; i--) {{
        int j = rand() % (i + 1);
        int tmp = h_array[i];
        h_array[i] = h_array[j];
        h_array[j] = tmp;
    }}
    
    int* d_array;
    int* d_result;
    cudaMalloc(&d_array, size * sizeof(int));
    cudaMalloc(&d_result, sizeof(int));
    cudaMemcpy(d_array, h_array, size * sizeof(int), cudaMemcpyHostToDevice);
    
    cudaEvent_t start, stop;
    cudaEventCreate(&start);
    cudaEventCreate(&stop);
    
    cudaEventRecord(start);
    pointer_chase_kernel<<<1, 1>>>(d_array, d_result, size, iterations);
    cudaEventRecord(stop);
    cudaEventSynchronize(stop);
    
    float elapsed_ms;
    cudaEventElapsedTime(&elapsed_ms, start, stop);
    
    int h_result;
    cudaMemcpy(&h_result, d_result, sizeof(int), cudaMemcpyDeviceToHost);
    
    printf("size_bytes: %d\\n", size * 4);
    printf("iterations: %d\\n", iterations);
    printf("total_cycles: %d\\n", (int)(elapsed_ms * 1e6));
    printf("cycles_per_access: %.2f\\n", (elapsed_ms * 1e6) / iterations);
    
    cudaEventDestroy(start);
    cudaEventDestroy(stop);
    cudaFree(d_array);
    cudaFree(d_result);
    free(h_array);
    
    return 0;
}}
"""
