"""Actual SM clock frequency probe — defeats frequency locking.

Measures the actual GPU clock frequency by:
1. Running a clock-calibration kernel that outputs SM cycle counts
2. Measuring wall-clock time of the same kernel via host timing

The ratio of SM cycles to wall-clock time gives the actual frequency,
which is immune to frequency locking because it measures what the GPU
is actually running at, not what it is supposed to run at.

Key insight: clock() in CUDA returns SM clock cycles. If we know
elapsed time from an independent clock, we can derive:
    actual_freq_MHz = total_sm_cycles / elapsed_time_us

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

import os
import shutil
import time
from typing import Any, Callable

from src.infrastructure.probing.kernel_templates import get_clock_calibration_design_spec
from src.infrastructure.probing.probe_helpers import (
    compile_and_run,
    parse_ncu_gpu_time,
    parse_nvcc_output,
    _detect_arch,
)
from src.infrastructure.sandbox import SandboxRunner


def probe_actual_clock_frequency(
    sandbox: SandboxRunner | None = None,
    code_generator: Callable[[str], str] | None = None,
    loop_iterations: int = 10_000_000,
) -> dict[str, Any] | None:
    """Measure actual SM clock frequency.

    Two-stage approach:
    1. Compile and run a calibration kernel, capturing SM cycles from
       the kernel output.
    2. Independently time the same kernel with host-side timing.

    Args:
        sandbox: SandboxRunner for compilation/execution.
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.
        loop_iterations: Number of loop iterations for timing (default 10M).

    Returns dict with:
        actual_boost_clock_mhz: float — measured SM frequency in MHz
        total_sm_cycles: int — total SM clock cycles measured
        elapsed_time_us: float — host-measured time in microseconds
        confidence: float — confidence score (0.0-1.0)
        method: str — measurement methodology
    """
    print("[clock] Starting clock frequency probe...")
    
    spec = get_clock_calibration_design_spec()
    
    if code_generator is not None:
        source = code_generator(_build_generation_prompt(spec, loop_iterations))
        print("[clock] Using LLM-generated CUDA source")
    else:
        source = _get_fallback_source(loop_iterations)
        print("[clock] Using fallback CUDA source (no LLM available)")
    
    print(f"[clock] Kernel source length: {len(source)} chars")
    result = compile_and_run(source, sandbox=sandbox)

    if not result or not result.success:
        print("[clock] compile_and_run failed")
        if result:
            print(f"  stdout: {result.stdout[:500]}")
            print(f"  stderr: {result.stderr[:500]}")
        return None

    parsed = parse_nvcc_output(result.stdout)
    total_cycles = parsed.get("total_cycles", 0)
    print(f"[clock] Parse result: {parsed}")

    if total_cycles <= 0:
        print(f"[clock] total_cycles <= 0, stdout: {result.stdout[:500]}")
        return None

    print(f"[clock] total_cycles={total_cycles}, cycles_per_iter={parsed.get('cycles_per_iter', 0)}")

    print("[clock] Attempting host timing measurement...")
    freq_mhz, ncu_raw = _measure_with_host_timing(source, sandbox)
    print(f"[clock] _measure_with_host_timing returned: freq_mhz={freq_mhz}")

    if freq_mhz and freq_mhz > 100:
        if freq_mhz < 500 or freq_mhz > 5000:
            print(f"[clock] WARNING: Unusual frequency {freq_mhz:.2f} MHz "
                  f"(expected range: 500-3000 MHz), but accepting as measured")
        result_dict = {
            "actual_boost_clock_mhz": round(freq_mhz, 2),
            "total_sm_cycles": int(total_cycles),
            "cycles_per_iteration": parsed.get("cycles_per_iter", 0),
            "_confidence": _assess_clock_confidence(freq_mhz),
            "method": "sm_clock_cycles_vs_host_wall_clock",
            "_note": "clock64() measures SM clock, which may differ from GPU boost clock. "
                     "On some GPUs (e.g., P100), SM clock runs lower than boost clock. "
                     "Low power states can further reduce the actual frequency.",
        }
        if ncu_raw:
            result_dict["_ncu_raw_output"] = ncu_raw
        return result_dict

    print(f"[clock] Host timing returned invalid freq={freq_mhz} MHz (< 100 MHz threshold)")

    print("[clock] Host timing failed, trying cudaEvents fallback...")
    freq_mhz = _measure_with_cuda_events(source, sandbox)
    print(f"[clock] _measure_with_cuda_events returned: freq_mhz={freq_mhz}")
    if freq_mhz and freq_mhz > 100:
        return {
            "actual_boost_clock_mhz": round(freq_mhz, 2),
            "total_sm_cycles": int(total_cycles),
            "cycles_per_iteration": parsed.get("cycles_per_iter", 0),
            "_confidence": _assess_clock_confidence(freq_mhz) * 0.8,
            "method": "sm_clock_cycles_vs_cuda_event_timing",
        }

    print("[clock] All timing methods failed, returning None")
    return None


def _build_generation_prompt(spec, loop_iterations: int) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for GPU clock frequency calibration.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

PARAMETERS:
- Loop iterations: {loop_iterations}

REQUIREMENTS:
1. Use clock64() for device-side timing (NOT clock())
2. Run a compute-intensive loop that takes measurable time
3. Output total SM cycles from clock64()
4. Warmup run before measurement
5. Output must be parseable (key: value format)
6. No architecture-specific code — must work on all NVIDIA GPUs
7. Include complete main() function with error handling
"""


def _get_fallback_source(loop_iterations: int) -> str:
    """Fallback CUDA source when LLM is not available.
    
    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.
    
    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.
    """
    return f"""
#include <stdio.h>
#include <cuda_runtime.h>

#define CUDA_CHECK(call) do {{ \\
    cudaError_t err = (call); \\
    if (err != cudaSuccess) {{ \\
        printf("CUDA_ERROR: %s at line %d\\n", cudaGetErrorString(err), __LINE__); \\
        printf("total_cycles: 0\\n"); \\
        printf("iterations: %d\\n", iterations); \\
        printf("cycles_per_iter: 0.00\\n"); \\
        return 1; \\
    }} \\
}} while(0)

__global__ void clock_calibrate_kernel(long long* cycles, int iterations) {{
    long long start = clock64();
    
    volatile long long sink = 0;
    #pragma unroll 1
    for (int i = 0; i < iterations; i++) {{
        sink += (long long)i * i + (sink & 1);
    }}
    asm volatile("" : "+l"(sink) : : "memory");
    if (sink < 0) {{
        cycles[0] = -1;
        return;
    }}
    
    long long end = clock64();
    __threadfence();
    
    if (threadIdx.x == 0) {{
        cycles[0] = end - start;
    }}
}}

int main() {{
    int iterations = {loop_iterations};
    
    int device_count = 0;
    cudaError_t err = cudaGetDeviceCount(&device_count);
    if (err != cudaSuccess || device_count == 0) {{
        printf("CUDA_ERROR: No CUDA devices available (err=%d, count=%d)\\n", err, device_count);
        printf("total_cycles: 0\\n");
        printf("iterations: %d\\n", iterations);
        printf("cycles_per_iter: 0.00\\n");
        return 1;
    }}
    
    cudaDeviceProp prop;
    CUDA_CHECK(cudaGetDeviceProperties(&prop, 0));
    printf("diag_gpu_name: %s\\n", prop.name);
    printf("diag_compute_capability: %d.%d\\n", prop.major, prop.minor);
    printf("diag_sm_count: %d\\n", prop.multiProcessorCount);
    
    long long* d_cycles;
    CUDA_CHECK(cudaMalloc(&d_cycles, sizeof(long long)));
    
    long long zero = 0;
    CUDA_CHECK(cudaMemcpy(d_cycles, &zero, sizeof(long long), cudaMemcpyHostToDevice));
    
    clock_calibrate_kernel<<<1, 1>>>(d_cycles, iterations / 10);
    err = cudaDeviceSynchronize();
    if (err != cudaSuccess) {{
        printf("CUDA_ERROR: Warmup kernel failed: %s\\n", cudaGetErrorString(err));
        printf("total_cycles: 0\\n");
        printf("iterations: %d\\n", iterations);
        printf("cycles_per_iter: 0.00\\n");
        cudaFree(d_cycles);
        return 1;
    }}
    
    CUDA_CHECK(cudaMemcpy(d_cycles, &zero, sizeof(long long), cudaMemcpyHostToDevice));
    
    clock_calibrate_kernel<<<1, 1>>>(d_cycles, iterations);
    err = cudaDeviceSynchronize();
    if (err != cudaSuccess) {{
        printf("CUDA_ERROR: Measurement kernel failed: %s\\n", cudaGetErrorString(err));
        printf("total_cycles: 0\\n");
        printf("iterations: %d\\n", iterations);
        printf("cycles_per_iter: 0.00\\n");
        cudaFree(d_cycles);
        return 1;
    }}
    
    long long h_cycles = 0;
    CUDA_CHECK(cudaMemcpy(&h_cycles, d_cycles, sizeof(long long), cudaMemcpyDeviceToHost));
    
    if (h_cycles <= 0) {{
        printf("CUDA_ERROR: Measured cycles is %lld (expected > 0)\\n", h_cycles);
        printf("total_cycles: 0\\n");
        printf("iterations: %d\\n", iterations);
        printf("cycles_per_iter: 0.00\\n");
        cudaFree(d_cycles);
        return 1;
    }}
    
    printf("total_cycles: %lld\\n", h_cycles);
    printf("iterations: %d\\n", iterations);
    printf("cycles_per_iter: %.2f\\n", (double)h_cycles / iterations);
    
    cudaFree(d_cycles);
    
    return 0;
}}
"""


def _measure_with_host_timing(
    source: str,
    sandbox: SandboxRunner | None = None,
) -> tuple[float | None, str | None]:
    """Measure kernel execution time via sandbox for frequency derivation.

    Compiles and runs the calibration kernel through the sandbox,
    parsing SM cycles from kernel output. Host wall-clock timing
    is measured by the kernel binary itself (it prints total_cycles
    from device clock()).

    Returns: (frequency in MHz, raw ncu output) tuple.
    """
    runner = sandbox
    work_dir = getattr(runner, "sandbox_root", None) or getattr(runner, "_sandbox_root", None) if runner else None
    nvcc = shutil.which("nvcc")
    if nvcc is None or not runner:
        return None, None

    arch = _detect_arch(runner)

    probe_binary_dir = os.path.join(work_dir, "probe_binaries")
    os.makedirs(probe_binary_dir, exist_ok=True)

    compile_result = runner.run(
        source_code=source,
        command=nvcc,
        args=["-o", os.path.join(probe_binary_dir, "freq_probe"), "source.cu", f"-arch={arch}", "-Wno-deprecated-gpu-targets"],
        work_dir=work_dir,
    )
    if not compile_result.success:
        return None, None

    binary = os.path.join(probe_binary_dir, "freq_probe")
    exec_result = runner.run(
        command=binary,
        args=[],
        work_dir=work_dir,
    )
    if not exec_result or not exec_result.success:
        return None, None

    min_cycles = None
    for _ in range(3):
        r = runner.run(
            command=binary,
            args=[],
            work_dir=work_dir,
        )
        if r and r.success:
            parsed = parse_nvcc_output(r.stdout)
            sm_cycles = parsed.get("total_cycles", 0)
            if sm_cycles > 0:
                if min_cycles is None or sm_cycles < min_cycles:
                    min_cycles = sm_cycles

    if min_cycles is None or min_cycles <= 0:
        return None, None

    freq_mhz, ncu_raw = _measure_with_ncu_timing(binary, work_dir, runner)
    if freq_mhz and freq_mhz > 100:
        return freq_mhz, ncu_raw

    return _measure_with_host_timing_fallback(binary, work_dir, runner, min_cycles)


def _measure_with_host_timing_fallback(
    binary_path: str,
    work_dir: str,
    runner: SandboxRunner,
    min_cycles: int,
) -> tuple[float | None, str | None]:
    """Gap 7: Host-side timing fallback when ncu is unavailable.

    Bug 4 fix: Collect cycles AND timing from the SAME execution to
    avoid frequency drift between batches.
    """
    ncu = shutil.which("ncu")

    runner.run(command=binary_path, args=[], work_dir=work_dir)

    best_cycles = None
    best_elapsed_s = None
    for _ in range(3):
        t0 = time.monotonic()
        r = runner.run(
            command=binary_path,
            args=[],
            work_dir=work_dir,
        )
        t1 = time.monotonic()
        elapsed_s = t1 - t0
        if r and r.success and elapsed_s > 0.001:
            parsed = parse_nvcc_output(r.stdout)
            cycles = parsed.get("total_cycles", 0)
            if cycles > 0:
                if best_elapsed_s is None or elapsed_s < best_elapsed_s:
                    best_elapsed_s = elapsed_s
                    best_cycles = cycles

    if best_cycles and best_elapsed_s and best_elapsed_s > 0:
        freq_mhz = best_cycles / (best_elapsed_s * 1e6)
        if freq_mhz > 100:
            return freq_mhz, None

    return None, None


def _measure_with_ncu_timing(
    binary_path: str,
    work_dir: str,
    runner: SandboxRunner,
) -> tuple[float | None, str | None]:
    """Measure SM frequency using ncu wall-clock timing.

    Returns: (frequency in MHz, raw ncu output) tuple.
    """
    ncu = shutil.which("ncu")
    if ncu is None:
        return None, None

    try:
        min_elapsed_ns = None
        best_ncu_raw = None
        best_cycles = None
        for _ in range(3):
            r = runner.run(
                command=ncu,
                args=["--profile-fromstart", "on", "--print-summary", "per_kernel",
                      binary_path],
                work_dir=work_dir,
            )
            if not r or not r.success:
                continue
            elapsed_ns = parse_ncu_gpu_time(r.stdout + r.stderr)
            parsed_cycles = parse_nvcc_output(r.stdout)
            cycles = parsed_cycles.get("total_cycles", 0)
            if elapsed_ns and elapsed_ns > 0:
                if min_elapsed_ns is None or elapsed_ns < min_elapsed_ns:
                    min_elapsed_ns = elapsed_ns
                    best_ncu_raw = r.stdout + r.stderr
                    best_cycles = cycles if cycles > 0 else best_cycles
        if min_elapsed_ns is None:
            return None, None

        sm_cycles = best_cycles or 0
        if sm_cycles <= 0:
            r2 = runner.run(
                command=binary_path,
                args=[],
                work_dir=work_dir,
            )
            if r2 and r2.success:
                parsed = parse_nvcc_output(r2.stdout)
                sm_cycles = parsed.get("total_cycles", 0)

        if sm_cycles > 0 and min_elapsed_ns > 0:
            freq_mhz = sm_cycles / (min_elapsed_ns / 1000.0)
            return freq_mhz, best_ncu_raw

    except Exception:
        pass

    return None, None


def _measure_with_cuda_events(
    source: str,
    sandbox: SandboxRunner | None = None,
) -> float | None:
    """P2: Measure SM frequency using cudaEventElapsedTime as ncu fallback.

    Wraps the kernel execution with cudaEventRecord/cudaEventElapsedTime
    to get GPU-side wall-clock timing.

    Returns: frequency in MHz, or None if measurement failed.
    """
    runner = sandbox
    work_dir = getattr(runner, "sandbox_root", None) or getattr(runner, "_sandbox_root", None) if runner else None
    nvcc = shutil.which("nvcc")
    if nvcc is None or not runner or not work_dir:
        return None

    arch = _detect_arch(runner)

    probe_binary_dir = os.path.join(work_dir, "probe_binaries")
    os.makedirs(probe_binary_dir, exist_ok=True)

    compile_result = runner.run(
        source_code=source,
        command=nvcc,
        args=["-o", os.path.join(probe_binary_dir, "freq_event_probe"), "source.cu", f"-arch={arch}", "-Wno-deprecated-gpu-targets"],
        work_dir=work_dir,
    )
    if not compile_result.success:
        return None

    binary = os.path.join(probe_binary_dir, "freq_event_probe")

    r = runner.run(
        command=binary,
        args=[],
        work_dir=work_dir,
    )
    if not r or not r.success:
        return None

    parsed = parse_nvcc_output(r.stdout)
    sm_cycles = parsed.get("total_cycles", 0)
    if sm_cycles <= 0:
        return None

    event_source = _wrap_with_events(source)
    if not event_source:
        return None

    probe_binary_dir = os.path.join(work_dir, "probe_binaries")
    os.makedirs(probe_binary_dir, exist_ok=True)

    compile_result2 = runner.run(
        source_code=event_source,
        command=nvcc,
        args=["-o", os.path.join(probe_binary_dir, "freq_event_timed"), "source.cu", f"-arch={arch}", "-Wno-deprecated-gpu-targets"],
        work_dir=work_dir,
    )
    if not compile_result2.success:
        return None

    timed_binary = os.path.join(probe_binary_dir, "freq_event_timed")

    min_elapsed_ms = None
    for _ in range(3):
        r2 = runner.run(
            command=timed_binary,
            args=[],
            work_dir=work_dir,
        )
        if r2 and r2.success:
            p2 = parse_nvcc_output(r2.stdout)
            elapsed_ms = p2.get("elapsed_time_ms", 0)
            if elapsed_ms > 0:
                if min_elapsed_ms is None or elapsed_ms < min_elapsed_ms:
                    min_elapsed_ms = elapsed_ms

    if min_elapsed_ms and min_elapsed_ms > 0:
        elapsed_us = min_elapsed_ms * 1000.0
        return sm_cycles / elapsed_us

    return None


def _wrap_with_events(original_source: str) -> str | None:
    """Wrap the original kernel source with cudaEventElapsedTime timing.

    Inserts cudaEventRecord before and after the LAST kernel launch line.
    """
    lines = original_source.split("\n")

    last_launch_idx = -1
    for i, line in enumerate(lines):
        if "<<<" in line and ">>>" in line:
            last_launch_idx = i

    if last_launch_idx < 0:
        return None

    new_lines = []
    for i, line in enumerate(lines):
        if i == last_launch_idx:
            new_lines.append('    cudaEvent_t evt_start, evt_stop;')
            new_lines.append('    cudaEventCreate(&evt_start);')
            new_lines.append('    cudaEventCreate(&evt_stop);')
            new_lines.append('    cudaEventRecord(evt_start);')
            new_lines.append(line)
            new_lines.append('    cudaEventRecord(evt_stop);')
            new_lines.append('    cudaEventSynchronize(evt_stop);')
            new_lines.append('    float elapsed_ms;')
            new_lines.append('    cudaEventElapsedTime(&elapsed_ms, evt_start, evt_stop);')
            new_lines.append('    printf("elapsed_time_ms: %.4f\\n", elapsed_ms);')
            new_lines.append('    cudaEventDestroy(evt_start);')
            new_lines.append('    cudaEventDestroy(evt_stop);')
        else:
            new_lines.append(line)

    return "\n".join(new_lines)


def _assess_clock_confidence(freq_mhz: float) -> float:
    """Assess confidence in the clock measurement."""
    if 1000 <= freq_mhz <= 2000:
        return 0.9
    elif 500 <= freq_mhz <= 2500:
        return 0.7
    elif 200 <= freq_mhz <= 3000:
        return 0.4
    return 0.2
