"""DRAM latency probe — measures memory hierarchy latency in hardware cycles.

Uses pointer chasing with different working set sizes to isolate:
- L1 cache latency (working set < 8 KB)
- L2 cache latency (working set < L2 capacity)
- DRAM latency (working set >> L2 capacity, ≥ 64 MB to exceed H100 L2)

All measurements use clock64() cycle counts — completely independent of
the SM clock frequency. The actual frequency is only needed when
converting to nanoseconds for reporting.

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

from typing import Any, Callable

from src.infrastructure.probing.kernel_templates import get_pointer_chase_design_spec
from src.infrastructure.probing.probe_helpers import (
    compile_and_run,
    parse_nvcc_output,
    _assess_confidence,
)
from src.infrastructure.sandbox import SandboxRunner


def probe_dram_latency_cycles(
    sandbox: SandboxRunner | None = None,
    actual_freq_mhz: float | None = None,
    code_generator: Callable[[str], str] | None = None,
) -> dict[str, Any] | None:
    """Measure DRAM latency in SM clock cycles.

    Strategy: run pointer chasing with a large working set that
    exceeds L2 cache capacity, ensuring all accesses hit DRAM.

    Args:
        sandbox: SandboxRunner for compilation/execution.
        actual_freq_mhz: SM clock frequency for ns conversion.
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.

    Returns dict with:
        dram_latency_cycles: float — latency in SM clock cycles
        dram_latency_ns: float — latency in nanoseconds (if freq known)
        l2_latency_cycles: float — L2 latency in cycles
        l1_latency_cycles: float — L1 latency in cycles
        method: str — measurement methodology
    """
    results: dict[str, Any] = {}

    probe_sizes = [
        (2 * 1024, "l1"),
        (512 * 1024, "l2"),
        (32 * 1024 * 1024, "dram"),
    ]

    latencies: dict[str, float] = {}

    for size, level in probe_sizes:
        iter_map = {"l1": 50000, "l2": 20000, "dram": 100000}
        iters = iter_map.get(level, 10000)
        
        spec = get_pointer_chase_design_spec()
        
        if code_generator is not None:
            source = code_generator(_build_generation_prompt(spec, size, iters))
            print(f"[dram_latency] Using LLM-generated CUDA source for {level}")
        else:
            source = _get_fallback_source(size, iters)
            print(f"[dram_latency] Using fallback CUDA source for {level}")
        
        result = compile_and_run(source, sandbox=sandbox)
        if result and result.success:
            parsed = parse_nvcc_output(result.stdout)
            cpa = parsed.get("cycles_per_access", 0)
            if cpa > 0:
                latencies[level] = cpa

    if "dram" in latencies:
        dram_cycles = latencies["dram"]
        results["dram_latency_cycles"] = round(dram_cycles)

        if actual_freq_mhz:
            results["dram_latency_ns"] = round(dram_cycles / actual_freq_mhz * 1000, 2)

    if "l2" in latencies:
        results["l2_latency_cycles"] = round(latencies["l2"])
    if "l1" in latencies:
        results["l1_latency_cycles"] = round(latencies["l1"])

    if "dram" in latencies and "l2" in latencies:
        results["dram_to_l2_latency_ratio"] = round(
            latencies["dram"] / latencies["l2"], 2
        )

    if "l1" in latencies and "l2" in latencies:
        results["l2_to_l1_latency_ratio"] = round(
            latencies["l2"] / latencies["l1"], 2
        )

    results["latency_profile"] = latencies
    results["method"] = "pointer_chasing_with_working_set_sweep"

    dram_size_mb = 128
    dram_contaminated = False
    if "dram" in latencies and "l2" in latencies:
        dram_l2_ratio = latencies["dram"] / latencies["l2"] if latencies["l2"] > 0 else 0
        if dram_l2_ratio > 0 and dram_l2_ratio < 1.5:
            results["_dram_may_be_l2_contaminated"] = True
            dram_contaminated = True

    results["_dram_working_set_mb"] = dram_size_mb

    levels_detected = sum(1 for l in ["l1", "l2", "dram"] if l in latencies)
    hierarchy_valid = (
        latencies.get("dram", 0) > latencies.get("l2", 0) > latencies.get("l1", 0)
        if levels_detected == 3 else False
    )
    if hierarchy_valid:
        results["_confidence"] = 0.9
    elif levels_detected >= 2:
        results["_confidence"] = 0.7
    elif levels_detected >= 1:
        results["_confidence"] = 0.5
    else:
        results["_confidence"] = 0.0

    if dram_contaminated:
        results["_confidence"] = min(results["_confidence"], 0.4)

    return results if results.get("dram_latency_cycles") else None


def probe_latency_profile(
    sandbox: SandboxRunner | None = None,
    sizes: list[tuple[int, str]] | None = None,
    code_generator: Callable[[str], str] | None = None,
) -> dict[str, Any] | None:
    """Full latency profile — runs pointer chasing at many sizes.

    The caller can specify custom sizes or use the default progression
    that sweeps from L1-sized to DRAM-sized working sets.

    Returns the full latency curve for cache capacity cliff detection.
    """
    if sizes is None:
        sizes = [
            (8 * 1024, "8k"),
            (32 * 1024, "32k"),
            (128 * 1024, "128k"),
            (512 * 1024, "512k"),
            (1024 * 1024, "1m"),
            (2 * 1024 * 1024, "2m"),
            (4 * 1024 * 1024, "4m"),
            (8 * 1024 * 1024, "8m"),
            (16 * 1024 * 1024, "16m"),
        ]

    curve: dict[str, float] = {}
    spec = get_pointer_chase_design_spec()
    
    for size, label in sizes:
        if code_generator is not None:
            source = code_generator(_build_generation_prompt(spec, size, 50000))
        else:
            source = _get_fallback_source(size, 50000)
        
        result = compile_and_run(source, sandbox=sandbox)
        if result and result.success:
            parsed = parse_nvcc_output(result.stdout)
            cpa = parsed.get("cycles_per_access", 0)
            if cpa > 0:
                curve[label] = cpa

    return {"latency_curve": curve} if curve else None


def _build_generation_prompt(spec, array_size: int, iterations: int) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for pointer-chasing latency measurement.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

PARAMETERS:
- Array size: {array_size} integers ({array_size * 4} bytes)
- Iterations: {iterations}

REQUIREMENTS:
1. Use clock64() for device-side timing (NOT clock())
2. Build random permutation on host to defeat hardware prefetcher
3. Make chain circular: last element points back to first
4. Warmup: traverse chain 100 times before timing
5. Write result to device memory to prevent dead-code elimination
6. Output must be parseable (key: value format)
7. No architecture-specific code — must work on all NVIDIA GPUs
8. Include complete main() function with error handling
"""


def _get_fallback_source(array_size: int, iterations: int) -> str:
    """Fallback CUDA source when LLM is not available.
    
    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.
    
    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.
    """
    return f"""
#include <stdio.h>
#include <cuda_runtime.h>
#include <stdlib.h>
#include <time.h>

__global__ void pointer_chase_kernel(int* array, int* result, int size, int iterations, long long* d_cycles) {{
    int idx = 0;
    long long start = clock64();
    for (int i = 0; i < iterations; i++) {{
        idx = array[idx];
    }}
    long long end = clock64();
    if (threadIdx.x == 0) {{
        d_cycles[0] = end - start;
        result[0] = idx;
    }}
}}

int main() {{
    int size = {array_size};
    int iterations = {iterations};
    
    int* h_array = (int*)malloc(size * sizeof(int));
    for (int i = 0; i < size; i++) h_array[i] = (i + 1) % size;
    
    srand(42);
    for (int i = size - 1; i > 0; i--) {{
        int j = rand() % (i + 1);
        int tmp = h_array[i];
        h_array[i] = h_array[j];
        h_array[j] = tmp;
    }}
    
    int* d_array;
    int* d_result;
    long long* d_cycles;
    cudaMalloc(&d_array, size * sizeof(int));
    cudaMalloc(&d_result, sizeof(int));
    cudaMalloc(&d_cycles, sizeof(long long));
    cudaMemcpy(d_array, h_array, size * sizeof(int), cudaMemcpyHostToDevice);
    
    for (int warmup = 0; warmup < 100; warmup++) {{
        int idx = 0;
        for (int i = 0; i < iterations; i++) {{
            idx = h_array[idx];
        }}
    }}
    
    pointer_chase_kernel<<<1, 1>>>(d_array, d_result, size, iterations, d_cycles);
    cudaError_t err = cudaDeviceSynchronize();
    if (err != cudaSuccess) {{
        printf("CUDA_ERROR: %s\\n", cudaGetErrorString(err));
        return 1;
    }}
    
    long long h_cycles = 0;
    cudaMemcpy(&h_cycles, d_cycles, sizeof(long long), cudaMemcpyDeviceToHost);
    
    int h_result;
    cudaMemcpy(&h_result, d_result, sizeof(int), cudaMemcpyDeviceToHost);
    
    if (h_cycles <= 0) {{
        printf("CUDA_ERROR: Measured cycles is 0 (expected > 0)\\n");
        return 1;
    }}
    
    double cycles_per_access = (double)h_cycles / iterations;
    
    printf("size_bytes: %d\\n", size * 4);
    printf("iterations: %d\\n", iterations);
    printf("total_cycles: %lld\\n", h_cycles);
    printf("cycles_per_access: %.2f\\n", cycles_per_access);
    printf("chain_checksum: %d\\n", h_result);
    
    cudaFree(d_array);
    cudaFree(d_result);
    cudaFree(d_cycles);
    free(h_array);
    
    return 0;
}}
"""
