from __future__ import annotations

import os
import warnings
from typing import Literal


FALLBACK_PROBES_ENABLED: bool = (
    os.environ.get("ENABLE_FALLBACK_PROBES", "false").lower() == "true"
)

COMPLIANCE_MODE: Literal["strict", "debug"] = (
    "debug" if FALLBACK_PROBES_ENABLED else "strict"
)


def check_fallback_usage(probe_name: str) -> bool:
    """Check if fallback probes are allowed in current mode.

    Args:
        probe_name: Name of the probing module attempting to use fallback

    Returns:
        True if fallback is allowed, False if it should be blocked

    Raises:
        UserWarning: When fallback is enabled (debug mode)
        RuntimeError: When fallback is disabled but no LLM generator available
    """
    if not FALLBACK_PROBES_ENABLED:
        print(
            f"[COMPLIANCE] {probe_name}: Fallback probes are DISABLED.\n"
            f"  Mode: {COMPLIANCE_MODE.upper()}\n"
            f"  Requirement: CUDA code MUST be generated by LLM (spec.md §5.1)\n"
            f"  Action: Returning None to force Pipeline to use CodeGen Agent."
        )
        return False

    warnings.warn(
        f"\n{'='*70}\n"
        f"⚠️  FALLBACK PROBE MODE ENABLED - {probe_name}\n"
        f"{'='*70}\n"
        f"This mode uses HARDCODED CUDA source code instead of LLM generation.\n\n"
        f"Impact on scoring (PJ需求 §1.7.4):\n"
        f"  ❌ '微基准有效性': 代理未生成适当的CUDA内核 (0/10 points)\n"
        f"  ❌ '交叉验证': 未执行不同类型探针 (0/10 points)\n"
        f"  ❌ 'API依赖': 可能依赖受限API调用 (-5 to -10 points)\n\n"
        f"Estimated score penalty: -25 to -30 points out of 100\n"
        f"Recommended use: DEBUGGING ONLY - Disable for production submission!\n"
        f"{'='*70}\n",
        UserWarning,
        stacklevel=3,
    )
    return True


def mark_result_as_fallback(result: dict, probe_name: str) -> dict:
    """Mark a result dictionary as coming from fallback (hardcoded) source.

    This ensures transparency in output and allows automated detection.

    Args:
        result: Original result dictionary from probe execution
        probe_name: Name of the probing module

    Returns:
        Modified result with compliance metadata added
    """
    result["_compliance"] = {
        "method": "fallback-hardcoded",
        "probe": probe_name,
        "llm_generated": False,
        "spec_violation": "P5-compile-time-elimination",
        "warning": (
            "This result was generated using hardcoded CUDA source code, "
            "not by LLM as required by spec.md §5.1 and PJ需求 §1.7.4. "
            "This will receive ZERO or minimal credit for "
            "'Engineering Reasoning & Methodology' scoring dimension."
        ),
    }
    return result


def get_compliance_header() -> str:
    """Generate compliance header for log files."""
    return (
        f"# Compliance Metadata\n"
        f"# Mode: {COMPLIANCE_MODE.upper()}\n"
        f"# Fallback Probes Enabled: {FALLBACK_PROBES_ENABLED}\n"
        f"# Requirement: spec.md §5.1 (LLM-generated CUDA), PJ需求 §1.7.4 (Micro-benchmarks)\n"
        f"#\n"
        f"# If FALLBACK_PROBES_ENABLED=true:\n"
        f"#   → Results will be marked with '_compliance.method=fallback-hardcoded'\n"
        f"#   → Expect significant scoring penalty (-25 to -30 points)\n"
        f"#   → Use only for debugging, NOT for competition submission\n"
        f"#\n"
        f"# If FALLBACK_PROBES_ENABLED=false (default):\n"
        f"#   → All probes must go through CodeGen Agent (LLM)\n"
        f"#   → Full compliance with spec.md and PJ requirements\n"
        f"#   → Eligible for full 'Engineering Reasoning' score (30/30 points)\n"
    )
