"""CUDA kernel design specifications for hardware probing.

This module provides DESIGN SPECIFICATIONS (not hardcoded templates) that guide
LLM-based code generation. Each specification describes:

1. The measurement objective
2. Required techniques and algorithms
3. Timing methodology
4. Output format requirements
5. Architecture-agnostic best practices

Per spec.md: "CUDA/C++ code should be generated by LLM, not hardcoded templates."
This module contains NO hardcoded CUDA source code — only design principles.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class KernelDesignSpec:
    """Design specification for a CUDA micro-benchmark kernel.
    
    Contains design principles that an LLM uses to generate actual CUDA code.
    NO hardcoded source code — only methodology descriptions.
    """
    name: str
    objective: str
    timing_method: str
    key_techniques: list[str]
    output_format: list[str]
    working_set_guidance: str
    architecture_notes: str


def get_pointer_chase_design_spec() -> KernelDesignSpec:
    """Design specification for pointer-chasing latency measurement.
    
    Used for measuring memory hierarchy latency (L1, L2, DRAM).
    The LLM generates CUDA code following these design principles.
    """
    return KernelDesignSpec(
        name="pointer_chase",
        objective=(
            "Measure memory access latency in SM clock cycles by following "
            "a linked list through GPU memory. Different working set sizes "
            "target different cache levels: L1 (< 32 KB), L2 (< L2 capacity), DRAM (> L2)."
        ),
        timing_method=(
            "Use clock64() for cycle-accurate device-side timing. "
            "NEVER use clock() — returns 0 on Pascal+ under PTX JIT. "
            "Single-thread measurement (1 block, 1 thread)."
        ),
        key_techniques=[
            "Build random permutation (Knuth shuffle) on host to defeat hardware prefetcher",
            "Make chain circular: last element points back to first",
            "Warmup: traverse chain 100 times before timing to ensure pages are resident",
            "Use __threadfence() before timing to ensure warmup completes",
            "Write result to device memory to prevent dead-code elimination",
            "Calculate cycles_per_access = total_cycles / iterations",
        ],
        output_format=[
            "total_cycles: <integer>",
            "iterations: <integer>",
            "cycles_per_access: <float>",
            "chain_checksum: <integer>  # prevents dead-code elimination",
        ],
        working_set_guidance=(
            "L1 latency: array_size = 2048 (8 KB) — fits in all GPU L1 caches\n"
            "L2 latency: array_size = 524288 (2 MB) — fits in most L2 caches\n"
            "DRAM latency: array_size = 16777216 (64 MB) — exceeds all known L2 sizes"
        ),
        architecture_notes=(
            "clock64() works on all CUDA architectures (sm_35+)\n"
            "Random permutation defeats hardware prefetcher on all architectures\n"
            "No architecture-specific intrinsics required"
        ),
    )


def get_working_set_sweep_design_spec() -> KernelDesignSpec:
    """Design specification for cache capacity detection via working-set sweep."""
    return KernelDesignSpec(
        name="working_set_sweep",
        objective=(
            "Detect L2 cache capacity by sweeping working set sizes and "
            "identifying the 'cliff' where latency jumps sharply (cache overflow)."
        ),
        timing_method=(
            "Use clock64() for device-side timing. "
            "Measure cycles per access at each working set size. "
            "The cliff is where cycles_per_access increases by > 3x."
        ),
        key_techniques=[
            "Use random permutation (Knuth shuffle) — defeats hardware prefetcher",
            "Sweep sizes from 1 MB to 128 MB with intermediate points",
            "Common L2 capacities: 2-6 MB (consumer), 40-72 MB (datacenter)",
            "Report the last size BEFORE the cliff as cache capacity",
        ],
        output_format=[
            "size_bytes: <integer>",
            "total_cycles: <integer>",
            "cycles_per_access: <float>",
            "iterations: <integer>",
        ],
        working_set_guidance=(
            "Suggested sweep points (in elements, each = 4 bytes):\n"
            "256K, 512K, 1M, 2M, 3M, 4M, 5M, 6M, 8M, 10M, 12M, 16M, 24M, 32M\n"
            "This covers 1 MB to 128 MB working sets"
        ),
        architecture_notes=(
            "L2 capacity varies by GPU:\n"
            "- Pascal (P100): 4 MB\n"
            "- Volta (V100): 6 MB\n"
            "- Turing (T4): 6 MB\n"
            "- Ampere (A100): 40-80 MB\n"
            "- Hopper (H100): 50-60 MB\n"
            "Measurement should detect actual capacity, not assume these values"
        ),
    )


def get_clock_calibration_design_spec() -> KernelDesignSpec:
    """Design specification for SM clock frequency measurement."""
    return KernelDesignSpec(
        name="clock_calibration",
        objective=(
            "Measure actual SM clock frequency by combining device-side "
            "cycle counts with wall-clock timing. This defeats frequency "
            "locking because it measures actual frequency, not spec sheet values."
        ),
        timing_method=(
            "Device-side: clock64() for total SM cycles\n"
            "Host-side: cudaEventElapsedTime OR ncu GPU time for wall-clock\n"
            "actual_freq_MHz = total_cycles / elapsed_time_us"
        ),
        key_techniques=[
            "Use random permutation linked list for stable timing",
            "Small working set (4 KB) to minimize memory latency variance",
            "Run multiple iterations (10M+) for measurable elapsed time",
            "Use cudaEventRecord/cudaEventSynchronize for host timing",
            "Run 3 trials, take minimum to reduce noise",
        ],
        output_format=[
            "total_cycles: <integer>",
            "iterations: <integer>",
            "cycles_per_iter: <float>",
            "elapsed_time_ms: <float>  # from cudaEventElapsedTime",
        ],
        working_set_guidance=(
            "Use small working set: 1024 elements (4 KB)\n"
            "This fits in L1 cache, minimizing memory latency variance\n"
            "Large iteration count (10M+) ensures measurable elapsed time"
        ),
        architecture_notes=(
            "clock64() works on all architectures\n"
            "cudaEventElapsedTime has ~0.5 microsecond precision\n"
            "Typical GPU clocks: 500-2500 MHz\n"
            "Frequency may be locked below spec by nvidia-smi"
        ),
    )


def get_stream_copy_design_spec() -> KernelDesignSpec:
    """Design specification for DRAM bandwidth measurement (STREAM copy pattern)."""
    return KernelDesignSpec(
        name="stream_copy",
        objective=(
            "Measure DRAM bandwidth using STREAM copy pattern: dst[i] = src[i]. "
            "Saturates memory bus to achieve peak bandwidth."
        ),
        timing_method=(
            "Use cudaEventElapsedTime for wall-clock timing. "
            "Bandwidth = bytes_copied / elapsed_seconds. "
            "NO device-side timing needed."
        ),
        key_techniques=[
            "Simple copy kernel: dst[i] = src[i]",
            "Large data size (128 MB+) to exceed L2 cache",
            "Full grid launch: max blocks × 256 threads",
            "Warmup run before measurement",
            "Run 3 trials, take minimum elapsed time",
        ],
        output_format=[
            "elements: <integer>",
            "bytes_copied: <integer>",
            "gpu_time_ms: <float>  # from cudaEventElapsedTime",
            "bandwidth_gbps: <float>  # calculated",
        ],
        working_set_guidance=(
            "Use 32M elements (128 MB) or larger\n"
            "This exceeds all known GPU L2 cache sizes\n"
            "Ensures measurement reflects DRAM bandwidth, not cache"
        ),
        architecture_notes=(
            "Peak DRAM bandwidth varies by GPU:\n"
            "- P100: ~550 GB/s\n"
            "- V100: ~900 GB/s\n"
            "- A100: ~1600 GB/s\n"
            "- H100: ~3350 GB/s\n"
            "Measurement should achieve 70-90% of theoretical peak"
        ),
    )


def get_shmem_capacity_design_spec() -> KernelDesignSpec:
    """Design specification for shared memory capacity detection."""
    return KernelDesignSpec(
        name="shmem_capacity",
        objective=(
            "Determine maximum shared memory per block using CUDA occupancy API. "
            "Query cudaDeviceGetAttribute and sweep shmem sizes."
        ),
        timing_method=(
            "NO timing needed — uses cudaOccupancyMaxActiveBlocksPerMultiprocessor. "
            "This is a direct API query, not a micro-benchmark."
        ),
        key_techniques=[
            "Query cudaDevAttrMaxSharedMemoryPerBlock for device limit",
            "Query cudaDevAttrMaxSharedMemoryPerMultiprocessor for SM limit",
            "Use cudaOccupancyMaxActiveBlocksPerMultiprocessor to verify",
            "Sweep shmem sizes: 1KB, 2KB, 4KB, ..., up to device max",
            "Find largest size where blocks_per_sm > 0",
            "Use cudaFuncSetAttribute to allow large dynamic shmem",
        ],
        output_format=[
            "device_max_shared_mem_per_block: <integer>",
            "device_max_shared_mem_per_sm: <integer>",
            "compute_capability: <string>  # e.g., '60' for sm_60",
            "shmem_<size>: blocks=<n> active_warps=<n>",
            "shmem_max_tested: <integer>",
        ],
        working_set_guidance=(
            "Sweep sizes: 1KB, 2KB, 4KB, 8KB, 16KB, 32KB, 48KB, 64KB, 96KB, 128KB, ...\n"
            "Typical limits:\n"
            "- sm_60 (Pascal): 64 KB/block\n"
            "- sm_70 (Volta): 96 KB/block\n"
            "- sm_75+ (Turing/Ampere): up to 164 KB/block"
        ),
        architecture_notes=(
            "Use cudaDeviceGetAttribute, NOT cudaGetDeviceProperties\n"
            "cudaGetDeviceProperties may be virtualized under vGPU/MIG\n"
            "cudaDeviceGetAttribute returns actual hardware values"
        ),
    )


def get_bank_conflict_design_spec() -> KernelDesignSpec:
    """Design specification for shared memory bank conflict latency measurement."""
    return KernelDesignSpec(
        name="bank_conflict",
        objective=(
            "Measure the latency penalty of shared memory bank conflicts "
            "by comparing strided access (conflicts) vs sequential access (no conflicts)."
        ),
        timing_method=(
            "Use clock64() for device-side timing within the kernel. "
            "Measure both patterns in the SAME kernel execution to ensure "
            "identical conditions. Ratio = strided_cycles / sequential_cycles."
        ),
        key_techniques=[
            "Use volatile __shared__ to prevent compiler caching",
            "Strided access: thread t accesses element t * stride (stride=32)",
            "Sequential access: thread t accesses element t + offset",
            "Both patterns access same number of elements",
            "Run 3 trials, take minimum for each pattern",
        ],
        output_format=[
            "strided_cycles: <integer>",
            "sequential_cycles: <integer>",
            "bank_conflict_ratio: <float>",
            "stride: <integer>",
            "size: <integer>",
            "iterations: <integer>",
        ],
        working_set_guidance=(
            "Use 32K floats (128 KB) shared memory\n"
            "Stride = 32 causes all threads in a warp to access same bank\n"
            "256 threads = 8 warps, all hitting same bank = worst case"
        ),
        architecture_notes=(
            "All NVIDIA GPUs have 32 shared memory banks\n"
            "Bank conflict ratio typically 16-32x for worst case\n"
            "Compile with -O0 to prevent aggressive optimization\n"
            "volatile shared memory ensures actual memory access"
        ),
    )


def get_shmem_bandwidth_design_spec() -> KernelDesignSpec:
    """Design specification for shared memory bandwidth measurement."""
    return KernelDesignSpec(
        name="shmem_bandwidth",
        objective=(
            "Measure shared memory bandwidth by having all threads in a block "
            "cooperatively read and write shared memory at maximum rate."
        ),
        timing_method=(
            "Use cudaEventElapsedTime for wall-clock timing. "
            "Bandwidth = total_bytes_transferred / elapsed_seconds. "
            "Total bytes = iterations × threads × 2 × sizeof(float) (read + write)."
        ),
        key_techniques=[
            "All threads read entire shared memory, then write back",
            "Use 256 threads per block",
            "Multiple iterations (10K+) for measurable time",
            "Prevent dead-code elimination with volatile or checksum",
            "Warmup run before measurement",
        ],
        output_format=[
            "shmem_bytes: <integer>",
            "block_threads: <integer>",
            "iterations: <integer>",
            "total_bytes_transferred: <integer>",
            "gpu_time_ms: <float>",
            "shmem_bandwidth_gbps: <float>",
        ],
        working_set_guidance=(
            "Shared memory size = threads × sizeof(float) = 256 × 4 = 1 KB\n"
            "This is small enough to fit in any GPU's shared memory\n"
            "Focus is on throughput, not capacity"
        ),
        architecture_notes=(
            "Shared memory bandwidth varies by architecture:\n"
            "- Typically 500-3000 GB/s\n"
            "- Higher on newer architectures with more banks\n"
            "Compile with -O3 for maximum throughput"
        ),
    )


def get_sm_count_design_spec() -> KernelDesignSpec:
    """Design specification for SM count detection (anti-masking)."""
    return KernelDesignSpec(
        name="sm_count",
        objective=(
            "Detect the actual number of active SMs on the GPU. "
            "Must work even when cudaGetDeviceProperties is virtualized. "
            "Uses cudaDeviceGetAttribute (not virtualized) + occupancy verification."
        ),
        timing_method=(
            "NO timing needed — uses API queries. "
            "Primary: cudaDeviceGetAttribute(cudaDevAttrMultiProcessorCount). "
            "Verification: cudaOccupancyMaxActiveBlocksPerMultiprocessor."
        ),
        key_techniques=[
            "Use cudaDeviceGetAttribute, NOT cudaGetDeviceProperties",
            "Query cudaDevAttrMultiProcessorCount for SM count",
            "Query cudaDevAttrMaxThreadsPerMultiProcessor for threads/SM",
            "Query cudaDevAttrMaxSharedMemoryPerMultiprocessor for shmem/SM",
            "Use occupancy API to verify SM count is consistent",
            "Compare against known GPU configurations for validation",
        ],
        output_format=[
            "sm_count: <integer>",
            "blocks_per_sm_256t: <integer>",
            "max_threads_per_block: <integer>",
            "max_threads_per_sm: <integer>",
            "max_shmem_per_sm: <integer>",
            "warp_size: <integer>",
            "likely_gpu_family: <string>",
        ],
        working_set_guidance=(
            "No working set needed — this is an API query\n"
            "Known SM counts for validation:\n"
            "- P100: 56 SMs\n"
            "- V100: 80 SMs\n"
            "- T4: 40 SMs\n"
            "- A100: 108 or 128 SMs\n"
            "- H100: 114 or 132 SMs"
        ),
        architecture_notes=(
            "cudaDeviceGetAttribute is NOT virtualized by most vGPU/MIG\n"
            "cudaGetDeviceProperties.multiProcessorCount may be wrong\n"
            "If detected SM count doesn't match known configs, may indicate:\n"
            "- SM masking (MIG partitioning)\n"
            "- Unknown GPU variant\n"
            "- Virtualization layer interference"
        ),
    )


def get_all_design_specs() -> dict[str, KernelDesignSpec]:
    """Return all kernel design specifications."""
    return {
        "pointer_chase": get_pointer_chase_design_spec(),
        "working_set_sweep": get_working_set_sweep_design_spec(),
        "clock_calibration": get_clock_calibration_design_spec(),
        "stream_copy": get_stream_copy_design_spec(),
        "shmem_capacity": get_shmem_capacity_design_spec(),
        "bank_conflict": get_bank_conflict_design_spec(),
        "shmem_bandwidth": get_shmem_bandwidth_design_spec(),
        "sm_count": get_sm_count_design_spec(),
    }
