"""Shared memory capacity probe — binary search for max shmem per block.

Uses cudaOccupancyMaxActiveBlocksPerMultiprocessor to probe the
maximum shared memory allocation per block. The kernel requests
increasing amounts of shared memory, and we check whether the
occupancy drops to zero.

This directly queries the CUDA runtime — no timing measurements
needed — making it the most reliable probe.

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

from typing import Any, Callable

from src.infrastructure.probing.kernel_templates import get_shmem_capacity_design_spec
from src.infrastructure.probing.probe_helpers import compile_and_run, parse_nvcc_output
from src.infrastructure.sandbox import SandboxRunner


def probe_shmem_capacity(
    sandbox: SandboxRunner | None = None,
    code_generator: Callable[[str], str] | None = None,
) -> dict[str, Any] | None:
    """Measure maximum shared memory per block.

    Runs a probe binary that:
    1. Queries cudaOccupancyMaxActiveBlocksPerMP for various shmem sizes
    2. Reports device properties (sharedMemPerBlock, sharedMemPerSM)
    3. Identifies the maximum shared memory per block that still allows
       at least 1 block per SM.

    Args:
        sandbox: SandboxRunner for compilation/execution.
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.

    Returns dict with:
        max_shmem_per_block_kb: float — max shared memory per block in KB
        max_shmem_per_block_bytes: int — in bytes
        max_shmem_per_sm_kb: float — max shared memory per SM in KB
        compute_capability: str — e.g. "75" for T4
        method: str — methodology
    """
    spec = get_shmem_capacity_design_spec()
    
    if code_generator is not None:
        source = code_generator(_build_generation_prompt(spec))
        print("[shmem_capacity] Using LLM-generated CUDA source")
    else:
        source = _get_fallback_source()
        print("[shmem_capacity] Using fallback CUDA source (no LLM available)")
    
    result = compile_and_run(source, sandbox=sandbox)

    if not result or not result.success:
        return None

    parsed = parse_nvcc_output(result.stdout)

    results: dict[str, Any] = {
        "method": "cuda_occupancy_api_with_shmem_sweep",
    }

    if "device_max_shared_mem_per_block" in parsed:
        block_bytes = int(parsed["device_max_shared_mem_per_block"])
        results["max_shmem_per_block_bytes"] = block_bytes
        results["max_shmem_per_block_kb"] = round(block_bytes / 1024, 2)

    if "device_max_shared_mem_per_sm" in parsed:
        sm_bytes = int(parsed["device_max_shared_mem_per_sm"])
        results["max_shmem_per_sm_bytes"] = sm_bytes
        results["max_shmem_per_sm_kb"] = round(sm_bytes / 1024, 2)

    if "compute_capability" in parsed:
        results["compute_capability"] = str(parsed["compute_capability"])

    occupancy_data = _parse_occupancy_sweep(result.stdout)
    if occupancy_data:
        results["occupancy_sweep"] = occupancy_data
        for entry in reversed(occupancy_data):
            if entry["blocks"] > 0:
                results["max_shmem_per_block_bytes"] = entry["shmem_bytes"]
                results["max_shmem_per_block_kb"] = round(
                    entry["shmem_bytes"] / 1024, 2
                )
                break

    if occupancy_data and len(occupancy_data) >= 4:
        results["_confidence"] = 0.9
    elif results.get("max_shmem_per_block_kb"):
        results["_confidence"] = 0.7
    else:
        results["_confidence"] = 0.0

    return results if results.get("max_shmem_per_block_kb") else None


def _parse_occupancy_sweep(stdout: str) -> list[dict[str, Any]]:
    """Parse shmem_X: blocks=N active_warps=M lines."""
    data = []
    for line in stdout.splitlines():
        line = line.strip()
        if line.startswith("shmem_") and ": blocks=" in line:
            parts = line.split(":")
            shmem_part = parts[0]
            try:
                shmem_bytes = int(shmem_part.split("_")[1])
            except (IndexError, ValueError):
                continue

            blocks = 0
            warps = 0
            for item in parts[1].split():
                if item.startswith("blocks="):
                    try:
                        blocks = int(item.split("=")[1])
                    except (IndexError, ValueError):
                        pass
                elif item.startswith("active_warps="):
                    try:
                        warps = int(item.split("=")[1])
                    except (IndexError, ValueError):
                        pass

            data.append({
                "shmem_bytes": shmem_bytes,
                "blocks": blocks,
                "active_warps": warps,
            })

    return data


def _build_generation_prompt(spec) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for shared memory capacity detection.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

PARAMETERS:
- Sweep shared memory sizes from 4KB to 256KB
- Test each size with cudaOccupancyMaxActiveBlocksPerMultiprocessor

REQUIREMENTS:
1. Use cudaOccupancyMaxActiveBlocksPerMultiprocessor API
2. Query device properties via cudaDeviceGetAttribute
3. Sweep shmem sizes in 4KB increments
4. Output must be parseable (key: value format)
5. No architecture-specific code — must work on all NVIDIA GPUs
6. Include complete main() function with error handling
"""


def _get_fallback_source() -> str:
    """Fallback CUDA source when LLM is not available.
    
    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.
    
    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.
    """
    return """
#include <stdio.h>
#include <cuda_runtime.h>

__global__ void shmem_test_kernel(int* result) {
    extern __shared__ int shmem[];
    if (threadIdx.x == 0) {
        shmem[0] = 0;
    }
    result[0] = shmem[0];
}

int main() {
    int device;
    cudaGetDevice(&device);
    
    cudaDeviceProp prop;
    cudaGetDeviceProperties(&prop, device);
    
    printf("device_max_shared_mem_per_block: %zu\\n", prop.sharedMemPerBlock);
    printf("device_max_shared_mem_per_sm: %zu\\n", prop.sharedMemPerMultiprocessor);
    printf("compute_capability: %d%d\\n", prop.major, prop.minor);
    
    int shmem_sizes_kb[] = {4, 8, 16, 24, 32, 48, 64, 96, 128, 160, 192, 224, 256};
    int num_sizes = sizeof(shmem_sizes_kb) / sizeof(shmem_sizes_kb[0]);
    
    for (int i = 0; i < num_sizes; i++) {
        int shmem_bytes = shmem_sizes_kb[i] * 1024;
        
        int blocks_per_sm;
        cudaError_t err = cudaOccupancyMaxActiveBlocksPerMultiprocessor(
            &blocks_per_sm, shmem_test_kernel, 256, shmem_bytes);
        
        if (err == cudaSuccess) {
            int warps = blocks_per_sm * 256 / 32;
            printf("shmem_%d: blocks=%d active_warps=%d\\n", 
                   shmem_bytes, blocks_per_sm, warps);
        } else {
            printf("shmem_%d: blocks=0 active_warps=0\\n", shmem_bytes);
        }
    }
    
    return 0;
}
"""
