"""Shared memory bandwidth probe.

Measures shared memory throughput by having a kernel read/write
shared memory at varying access patterns. Bandwidth = bytes / gpu_time_ns.

The kernel reads N floats from shared memory, writes N floats back,
using all threads in a block cooperatively. This saturates the shared
memory bus. Timed via ncu wall-clock profiling.

No cudaGetDeviceProperties used — all measurements from micro-benchmarks.

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

import os
import shutil
from typing import Any, Callable

from src.infrastructure.probing.probe_helpers import (
    compile_and_run,
    parse_ncu_gpu_time,
    parse_nvcc_output,
    _assess_confidence,
)
from src.infrastructure.probing.kernel_templates import get_shmem_bandwidth_design_spec
from src.infrastructure.sandbox import SandboxRunner


_BINARY_NAME = "probe_binary"


def probe_shmem_bandwidth(
    sandbox: SandboxRunner | None = None,
    code_generator: Callable[[str], str] | None = None,
    block_threads: int = 256,
) -> dict[str, Any] | None:
    """Measure shared memory bandwidth.

    Strategy:
    1. Compile shmem_bw kernel once
    2. Profile with ncu to get GPU execution time
    3. If ncu fails, reuse the compiled binary + cudaEvents fallback
    4. bandwidth = total_bytes / gpu_time_ns * 1e9

    Args:
        sandbox: SandboxRunner for compilation/execution.
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.
        block_threads: Number of threads per block (default 256).

    Returns dict with:
        shmem_bandwidth_gbps: float — shared memory bandwidth in GB/s
        total_bytes: int — total bytes transferred
        gpu_time_ns: float — GPU execution time in ns
        method: str — methodology
    """
    spec = get_shmem_bandwidth_design_spec()
    
    if code_generator is not None:
        source = code_generator(_build_generation_prompt(spec, block_threads))
        print("[shmem_bandwidth] Using LLM-generated CUDA source")
    else:
        source = _get_fallback_source(block_threads)
        print("[shmem_bandwidth] Using fallback CUDA source (no LLM available)")
    
    result = compile_and_run(source, sandbox=sandbox)
    if not result or not result.success:
        return None

    parsed = parse_nvcc_output(result.stdout)
    total_bytes = parsed.get("total_bytes_transferred", 0)
    if not total_bytes:
        return None

    work_dir = getattr(sandbox, "sandbox_root", None) or getattr(sandbox, "_sandbox_root", None) if sandbox else None
    if not work_dir:
        return None

    binary_path = os.path.join(work_dir, _BINARY_NAME)
    ncu = shutil.which("ncu")

    if ncu is not None:
        try:
            min_gpu_time_ns = None
            best_ncu_raw = None
            for _ in range(3):
                ncu_result = sandbox.run(
                    command=ncu,
                    args=["--profile-fromstart", "on", "--print-summary", "per_kernel",
                          binary_path],
                    work_dir=work_dir,
                )
                if ncu_result and ncu_result.success:
                    gpu_time_ns = parse_ncu_gpu_time(ncu_result.stdout + ncu_result.stderr)
                    if gpu_time_ns and gpu_time_ns > 0:
                        if min_gpu_time_ns is None or gpu_time_ns < min_gpu_time_ns:
                            min_gpu_time_ns = gpu_time_ns
                            best_ncu_raw = ncu_result.stdout + ncu_result.stderr

            if min_gpu_time_ns and min_gpu_time_ns > 0:
                total_bytes_int = int(total_bytes)
                bandwidth_gbps = total_bytes_int / min_gpu_time_ns * 1e9 / 1e9
                return {
                    "shmem_bandwidth_gbps": round(bandwidth_gbps, 2),
                    "total_bytes": total_bytes_int,
                    "gpu_time_ns": min_gpu_time_ns,
                    "method": "ncu_profiling",
                    "_confidence": _assess_confidence(bandwidth_gbps, 100, 20000),
                    "_ncu_raw": best_ncu_raw[:1000] if best_ncu_raw else None,
                }
        except Exception as e:
            print(f"[shmem_bandwidth] ncu profiling failed: {e}")

    return _run_with_cuda_events_fallback(source, sandbox, block_threads)


def _run_with_cuda_events_fallback(
    source: str, sandbox: SandboxRunner | None, block_threads: int,
) -> dict[str, Any] | None:
    """Fallback: measure shmem bandwidth using cudaEventElapsedTime when ncu unavailable."""
    import time as _time

    runner = sandbox
    work_dir = getattr(runner, "sandbox_root", None) or getattr(runner, "_sandbox_root", None) if runner else None
    if not work_dir:
        return None

    event_source = source.replace(
        "int main() {",
        '#include <stdio.h>\n#include <cuda_runtime.h>\n\nint main() {'
    ).replace(
        "    shmem_bw_kernel<<<1, block_threads, shmem_bytes>>>(iterations);\n    cudaDeviceSynchronize();",
        '    cudaEvent_t evt_start, evt_stop;\n'
        '    cudaEventCreate(&evt_start);\n'
        '    cudaEventCreate(&evt_stop);\n\n'
        '    // Warmup\n'
        '    shmem_bw_kernel<<<1, block_threads, shmem_bytes>>>(iterations);\n'
        '    cudaDeviceSynchronize();\n\n'
        '    cudaEventRecord(evt_start);\n'
        '    shmem_bw_kernel<<<1, block_threads, shmem_bytes>>>(iterations);\n'
        '    cudaEventRecord(evt_stop);\n'
        '    cudaEventSynchronize(evt_stop);\n\n'
        '    float elapsed_ms;\n'
        '    cudaEventElapsedTime(&elapsed_ms, evt_start, evt_stop);\n'
        '    printf("elapsed_time_ms: %.4f\\n", elapsed_ms);\n'
        '    cudaEventDestroy(evt_start);\n'
        '    cudaEventDestroy(evt_stop);'
    )

    result = compile_and_run(event_source, sandbox=sandbox)
    if not result or not result.success:
        return None

    parsed = parse_nvcc_output(result.stdout)
    total_bytes = parsed.get("total_bytes_transferred", 0)
    elapsed_ms = parsed.get("elapsed_time_ms", 0)

    if total_bytes and elapsed_ms and elapsed_ms > 0:
        gpu_time_ns = elapsed_ms * 1_000_000
        bandwidth_gbps = total_bytes / gpu_time_ns * 1e9 / 1e9
        return {
            "shmem_bandwidth_gbps": round(bandwidth_gbps, 2),
            "total_bytes": int(total_bytes),
            "gpu_time_ns": round(gpu_time_ns, 2),
            "method": "cuda_events_fallback",
            "_confidence": round(_assess_confidence(bandwidth_gbps, 100, 20000) * 0.7, 2),
        }

    return {
        "shmem_bandwidth_gbps": None,
        "total_bytes": int(total_bytes) if total_bytes else 0,
        "gpu_time_ns": None,
        "method": "ncu_unavailable",
        "_confidence": 0.0,
        "error": "ncu not found and cudaEvents fallback failed",
    }


def _build_generation_prompt(spec, block_threads: int) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for shared memory bandwidth measurement.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

ARCHITECTURE NOTES:
{spec.architecture_notes}

PARAMETERS:
- Block threads: {block_threads}
- Shared memory size: {block_threads} floats ({block_threads * 4} bytes)
- Iterations: 10000

REQUIREMENTS:
1. Use extern __shared__ for dynamic shared memory allocation
2. Include __syncthreads() for proper synchronization
3. Prevent dead-code elimination with volatile or conditional writes
4. Output must be parseable (key: value format)
5. No architecture-specific code — must work on all NVIDIA GPUs
6. Include complete main() function with error handling
"""


def _get_fallback_source(block_threads: int = 256) -> str:
    """Fallback CUDA source when LLM is not available.
    
    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.
    
    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.
    """
    return f"""
#include <stdio.h>
#include <cuda_runtime.h>

#define BLOCK_SIZE {block_threads}

__global__ void shmem_bw_kernel(int iterations) {{
    extern __shared__ float shmem[];
    int tid = threadIdx.x;
    int size = blockDim.x;

    for (int i = tid; i < size; i += blockDim.x) {{
        shmem[i] = (float)(i * 0.001f);
    }}
    __syncthreads();

    for (int iter = 0; iter < iterations; iter++) {{
        float sum = 0;
        for (int i = tid; i < size; i += blockDim.x) {{
            float val = shmem[i];
            val = val * 1.001f + 0.0001f;
            sum += val;
        }}
        if (sum > 1e9f) shmem[0] = sum;

        for (int i = tid; i < size; i += blockDim.x) {{
            shmem[i] = (float)(sum + i);
        }}
        __syncthreads();
    }}
}}

int main() {{
    int iterations = 10000;
    int block_threads = {block_threads};
    int shmem_bytes = block_threads * sizeof(float);

    cudaFuncSetAttribute(shmem_bw_kernel,
        cudaFuncAttributeMaxDynamicSharedMemorySize, shmem_bytes);

    shmem_bw_kernel<<<1, block_threads, shmem_bytes>>>(iterations);
    cudaDeviceSynchronize();

    printf("shmem_bytes: %d\\n", shmem_bytes);
    printf("block_threads: %d\\n", block_threads);
    printf("iterations: %d\\n", iterations);

    int total_bytes = iterations * block_threads * 2 * sizeof(float);
    printf("total_bytes_transferred: %d\\n", total_bytes);

    return 0;
}}
"""
