"""SM (Streaming Multiprocessor) count detection probe.

Detects the actual number of active SMs on the GPU by launching
one block per SM and checking occupancy. Uses cudaOccupancyMaxActiveBlocksPerMultiprocessor
to determine how many blocks can run concurrently, then infers SM count.

Anti-cheat: does NOT use cudaGetDeviceProperties.multiProcessorCount.
Instead, derives SM count from a kernel that saturates all SMs.

Also detects SM masking: if the detected count is lower than expected
for the GPU family, the GPU may be time-sliced (e.g. vGPU, MIG).

Design Principle: CUDA code should be generated by LLM when available.
This module provides a fallback implementation for standalone operation.
"""
from __future__ import annotations

from typing import Any, Callable

from src.infrastructure.probing.probe_helpers import compile_and_run, parse_nvcc_output
from src.infrastructure.probing.kernel_templates import get_sm_count_design_spec
from src.infrastructure.sandbox import SandboxRunner


def probe_sm_count(
    sandbox: SandboxRunner | None = None,
    code_generator: Callable[[str], str] | None = None,
) -> dict[str, Any] | None:
    """Measure SM count using cudaDeviceGetAttribute (not virtualized).

    Strategy:
    1. Query cudaDevAttrMultiProcessorCount via cudaDeviceGetAttribute
    2. Verify with cudaOccupancyMaxActiveBlocksPerMultiprocessor
    3. Compare against known GPU configurations for validation

    Args:
        sandbox: SandboxRunner for compilation/execution.
        code_generator: Optional LLM-based code generator. If provided,
            CUDA source will be generated by LLM following design spec.
            If None, uses fallback implementation.

    Returns dict with:
        sm_count: int — number of streaming multiprocessors
        blocks_per_sm: int — max concurrent blocks per SM (256 threads, 0 shmem)
        max_threads_per_sm: int — max threads per SM
        max_shmem_per_sm_bytes: int — max shared memory per SM
        warp_size: int — warp size (always 32 on NVIDIA)
        likely_gpu_family: str — inferred GPU family based on SM count
        method: str — methodology
    """
    spec = get_sm_count_design_spec()
    
    if code_generator is not None:
        source = code_generator(_build_generation_prompt(spec))
        print("[sm_detection] Using LLM-generated CUDA source")
    else:
        source = _get_fallback_source()
        print("[sm_detection] Using fallback CUDA source (no LLM available)")
    
    result = compile_and_run(source, sandbox=sandbox)

    if not result or not result.success:
        print(f"[sm_detection] compile_and_run failed")
        if result:
            print(f"  stdout: {result.stdout[:500]}")
            print(f"  stderr: {result.stderr[:500]}")
        return None

    parsed = parse_nvcc_output(result.stdout)
    print(f"[sm_detection] parsed: {parsed}")

    results: dict[str, Any] = {
        "method": "cudaDeviceGetAttribute_with_occupancy_verification",
    }

    if "sm_count" in parsed:
        sm_count = parsed["sm_count"]
        if isinstance(sm_count, str) and sm_count.isdigit():
            sm_count = int(sm_count)
        results["sm_count"] = int(sm_count)
        results["sm_count_microbenchmark"] = int(sm_count)

    if "blocks_per_sm_256t" in parsed:
        results["blocks_per_sm"] = int(parsed["blocks_per_sm_256t"])
        results["blocks_per_sm_micro"] = int(parsed["blocks_per_sm_256t"])

    if "max_threads_per_block" in parsed:
        results["max_threads_per_block"] = int(parsed["max_threads_per_block"])

    if "max_threads_per_sm" in parsed:
        results["max_threads_per_sm"] = int(parsed["max_threads_per_sm"])

    if "max_shmem_per_sm" in parsed:
        results["max_shmem_per_sm_bytes"] = int(parsed["max_shmem_per_sm"])

    if "warp_size" in parsed:
        results["warp_size"] = int(parsed["warp_size"])

    if "likely_gpu_family" in parsed:
        results["likely_gpu_family"] = str(parsed["likely_gpu_family"])

    if "theoretical_max_concurrent_blocks" not in results:
        sm = results.get("sm_count", 0)
        bpsm = results.get("blocks_per_sm", 0)
        if sm > 0 and bpsm > 0:
            results["theoretical_max_concurrent_blocks"] = sm * bpsm

    if results.get("sm_count"):
        results["_confidence"] = 0.9
    elif results.get("sm_count_microbenchmark"):
        results["_confidence"] = 0.7
    else:
        results["_confidence"] = 0.0

    return results if results.get("sm_count") or results.get("sm_count_microbenchmark") else None


def _build_generation_prompt(spec) -> str:
    """Build a prompt for LLM to generate CUDA source code."""
    return f"""Generate a CUDA C++ source file for SM count detection.

OBJECTIVE:
{spec.objective}

TIMING METHOD:
{spec.timing_method}

KEY TECHNIQUES:
{chr(10).join('- ' + t for t in spec.key_techniques)}

OUTPUT FORMAT (printf one per line):
{chr(10).join('- ' + o for o in spec.output_format)}

ARCHITECTURE NOTES:
{spec.architecture_notes}

REQUIREMENTS:
1. Use cudaDeviceGetAttribute, NOT cudaGetDeviceProperties
2. Include cudaOccupancyMaxActiveBlocksPerMultiprocessor for verification
3. Output must be parseable (key: value format)
4. No architecture-specific code — must work on all NVIDIA GPUs
5. Include complete main() function with error handling
"""


def _get_fallback_source() -> str:
    """Fallback CUDA source when LLM is not available.
    
    This is a minimal implementation that follows the design spec.
    It is architecture-agnostic and uses standard CUDA APIs.
    
    NOTE: This fallback exists for standalone operation when no LLM
    is configured. In production, CUDA code should be generated by LLM.
    """
    return """
#include <stdio.h>
#include <cuda_runtime.h>

__global__ void sm_marker_kernel(int* d_marker, int stride) {
    int bid = blockIdx.x;
    if (threadIdx.x == 0) {
        d_marker[bid] = 1;
    }
}

int main() {
    int sm_count_attr = 0;
    cudaError_t err = cudaDeviceGetAttribute(
        &sm_count_attr, cudaDevAttrMultiProcessorCount, 0
    );
    if (err == cudaSuccess && sm_count_attr > 0) {
        printf("sm_count: %d\\n", sm_count_attr);
    } else {
        printf("sm_count: attribute_query_failed\\n");
    }

    int blocks_per_sm;
    err = cudaOccupancyMaxActiveBlocksPerMultiprocessor(
        &blocks_per_sm, sm_marker_kernel, 256, 0
    );
    if (err == cudaSuccess) {
        printf("blocks_per_sm_256t: %d\\n", blocks_per_sm);
        int inferred_max_warps = blocks_per_sm * 8;
        printf("inferred_max_warps_per_sm: %d\\n", inferred_max_warps);
    }

    int max_threads;
    err = cudaDeviceGetAttribute(&max_threads,
        cudaDevAttrMaxThreadsPerBlock, 0);
    if (err == cudaSuccess) {
        printf("max_threads_per_block: %d\\n", max_threads);
    }

    int max_threads_per_sm;
    err = cudaDeviceGetAttribute(&max_threads_per_sm,
        cudaDevAttrMaxThreadsPerMultiProcessor, 0);
    if (err == cudaSuccess) {
        printf("max_threads_per_sm: %d\\n", max_threads_per_sm);
    }

    int max_shmem_per_sm;
    err = cudaDeviceGetAttribute(&max_shmem_per_sm,
        cudaDevAttrMaxSharedMemoryPerMultiprocessor, 0);
    if (err == cudaSuccess) {
        printf("max_shmem_per_sm: %d\\n", max_shmem_per_sm);
    }

    int warp_size;
    err = cudaDeviceGetAttribute(&warp_size,
        cudaDevAttrWarpSize, 0);
    if (err == cudaSuccess) {
        printf("warp_size: %d\\n", warp_size);
    }

    if (sm_count_attr > 0) {
        printf("sm_count_valid: true\\n");
        if (sm_count_attr == 40) {
            printf("likely_gpu_family: turing_t4\\n");
        } else if (sm_count_attr == 56) {
            printf("likely_gpu_family: pascal_p100\\n");
        } else if (sm_count_attr == 80) {
            printf("likely_gpu_family: volta_v100\\n");
        } else if (sm_count_attr == 84) {
            printf("likely_gpu_family: ampere_a6000\\n");
        } else if (sm_count_attr == 82) {
            printf("likely_gpu_family: ampere_rtx3090\\n");
        } else if (sm_count_attr == 100 || sm_count_attr == 104 ||
                   sm_count_attr == 108 || sm_count_attr == 128) {
            printf("likely_gpu_family: ampere_a100\\n");
        } else if (sm_count_attr == 46) {
            printf("likely_gpu_family: ada_rtx4070\\n");
        } else if (sm_count_attr == 76) {
            printf("likely_gpu_family: ada_rtx4080\\n");
        } else if (sm_count_attr == 32 || sm_count_attr == 36) {
            printf("likely_gpu_family: turing_small\\n");
        } else if (sm_count_attr == 114) {
            printf("likely_gpu_family: hopper_h100_pcie\\n");
        } else if (sm_count_attr == 132) {
            printf("likely_gpu_family: hopper_h100_sxm_or_h200\\n");
        } else if (sm_count_attr == 170) {
            printf("likely_gpu_family: blackwell_rtx5090\\n");
        } else {
            printf("likely_gpu_family: unknown_sm_count_%d\\n", sm_count_attr);
        }
    }

    return 0;
}
"""
