#!/usr/bin/env python3
"""供应商配置设置工具

用于配置和测试不同的LLM供应商
"""

import os
import json
from pathlib import Path
from src.infrastructure.provider_manager import get_provider_manager


def setup_provider_interactive():
    """交互式供应商设置"""
    print("🚀 GPU Profiling System - 供应商配置工具")
    print("=" * 50)

    # 初始化供应商管理器
    pm = get_provider_manager()

    print("\n📋 可用供应商:")
    pm.list_providers()

    print("\n🔧 配置选项:")
    print("1. 自动检测供应商")
    print("2. 手动选择供应商")
    print("3. 测试当前配置")
    print("4. 生成配置文件")

    choice = input("\n请选择操作 (1-4): ").strip()

    if choice == "1":
        auto_detect_provider(pm)
    elif choice == "2":
        manual_select_provider(pm)
    elif choice == "3":
        test_current_config(pm)
    elif choice == "4":
        generate_config_file(pm)
    else:
        print("❌ 无效选择")


def auto_detect_provider(pm):
    """自动检测供应商"""
    print("\n🔍 正在自动检测供应商...")
    provider = pm.detect_provider()

    if provider:
        print(f"✅ 检测到: {provider.name}")
        config = pm.create_unified_config()
        if config:
            save_config(config)
            print("✅ 配置文件已生成")
    else:
        print("❌ 未检测到可用供应商")
        print("\n💡 请设置以下环境变量之一:")
        print("  - DASHSCOPE_API_KEY (阿里云百炼)")
        print("  - LONGCAT_API_KEY (LongCat)")
        print("  - ANTHROPIC_API_KEY (Anthropic)")


def manual_select_provider(pm):
    """手动选择供应商"""
    print("\n📝 手动选择供应商:")

    providers = list(pm.providers.keys())
    for i, name in enumerate(providers, 1):
        provider = pm.providers[name]
        api_key = provider.get_api_key()
        status = "✅" if api_key else "❌"
        print(f"{i}. {provider.name} {status}")

    try:
        choice = int(input(f"\n选择供应商 (1-{len(providers)}): ")) - 1
        if 0 <= choice < len(providers):
            provider_name = providers[choice]
            if pm.set_provider(provider_name):
                config = pm.create_unified_config()
                if config:
                    save_config(config)
                    print("✅ 配置完成")
            else:
                print("❌ 配置失败")
        else:
            print("❌ 无效选择")
    except ValueError:
        print("❌ 请输入数字")


def test_current_config(pm):
    """测试当前配置"""
    print("\n🧪 测试当前配置...")

    provider = pm.get_provider()
    if not provider:
        print("❌ 未配置供应商")
        return

    config = pm.create_unified_config()
    if not config:
        print("❌ 无法创建配置")
        return

    print(f"✅ 供应商: {config['provider_name']}")
    print(f"✅ 模型: {config['env']['ANTHROPIC_MODEL']}")
    print(f"✅ 端点: {config['env']['ANTHROPIC_BASE_URL']}")

    # 简单的API连接测试
    print("\n🔗 测试API连接...")
    try:
        from src.infrastructure.model_caller import make_model_caller

        caller = make_model_caller()
        test_messages = [
            {"role": "user", "content": "Hello, are you working?"}
        ]

        # 注意：这里只是测试连接，不实际发送请求
        print("✅ 配置验证通过")
        print("💡 要实际测试API，请运行完整的GPU分析")

    except Exception as e:
        print(f"❌ 配置测试失败: {e}")


def generate_config_file(pm):
    """生成配置文件"""
    print("\n📄 生成配置文件...")

    config = pm.create_unified_config()
    if not config:
        print("❌ 无法创建配置")
        return

    save_config(config)
    print("✅ 配置文件已保存到 config/api_config.json")


def save_config(config):
    """保存配置文件"""
    config_path = Path("config/api_config.json")
    config_path.parent.mkdir(exist_ok=True)

    # 只保存env部分，保持与原有格式兼容
    simple_config = {
        "_comment": f"Generated by provider_manager - {config['provider_name']}",
        "env": config["env"],
        "includeCoAuthoredBy": False,
        "effortLevel": "high"
    }

    with open(config_path, 'w', encoding='utf-8') as f:
        json.dump(simple_config, f, indent=2, ensure_ascii=False)


def show_env_setup_instructions():
    """显示环境变量设置说明"""
    print("\n📋 环境变量设置说明:")
    print("=" * 40)

    print("\n☁️  阿里云百炼:")
    print("export DASHSCOPE_API_KEY='您的API密钥'")
    print("export DASHSCOPE_BASE_URL='https://dashscope.aliyuncs.com/compatible-mode/v1/'")
    print("export DASHSCOPE_MODEL='qwen-max'")

    print("\n🐱 LongCat API:")
    print("export LONGCAT_API_KEY='您的API密钥'")
    print("export LONGCAT_BASE_URL='https://api.longcat.com/openaicompatible/api/v1/'")
    print("export LONGCAT_MODEL='longcat-flash-chat'")

    print("\n🎭 Anthropic Claude:")
    print("export ANTHROPIC_API_KEY='您的API密钥'")
    print("export ANTHROPIC_BASE_URL='https://api.anthropic.com'")
    print("export ANTHROPIC_MODEL='claude-3-sonnet-20240229'")


if __name__ == "__main__":
    setup_provider_interactive()

    # 询问是否显示环境变量设置说明
    show_instructions = input("\n显示环境变量设置说明? (y/n): ").strip().lower()
    if show_instructions in ['y', 'yes']:
        show_env_setup_instructions()

    print("\n🎉 配置工具运行完成！")