"""Unit tests for hardware probing infrastructure.

Tests kernel design specifications, output parsing, and orchestrator logic
without requiring actual GPU hardware.

Design Principle: CUDA code should be generated by LLM when available.
Tests verify design specifications and fallback implementations.
"""
import pytest


class TestKernelDesignSpecs:
    """Verify kernel design specifications are properly defined."""

    def test_pointer_chase_design_spec(self):
        from src.infrastructure.probing.kernel_templates import get_pointer_chase_design_spec
        spec = get_pointer_chase_design_spec()
        assert spec.name == "pointer_chase"
        assert "clock64()" in spec.timing_method
        assert len(spec.key_techniques) > 0
        assert len(spec.output_format) > 0

    def test_working_set_sweep_design_spec(self):
        from src.infrastructure.probing.kernel_templates import get_working_set_sweep_design_spec
        spec = get_working_set_sweep_design_spec()
        assert spec.name == "working_set_sweep"
        assert "clock64()" in spec.timing_method
        assert "cliff" in spec.objective.lower()

    def test_clock_calibration_design_spec(self):
        from src.infrastructure.probing.kernel_templates import get_clock_calibration_design_spec
        spec = get_clock_calibration_design_spec()
        assert spec.name == "clock_calibration"
        assert "clock64()" in spec.timing_method
        assert "frequency" in spec.objective.lower()

    def test_stream_copy_design_spec(self):
        from src.infrastructure.probing.kernel_templates import get_stream_copy_design_spec
        spec = get_stream_copy_design_spec()
        assert spec.name == "stream_copy"
        assert "bandwidth" in spec.objective.lower()

    def test_shmem_capacity_design_spec(self):
        from src.infrastructure.probing.kernel_templates import get_shmem_capacity_design_spec
        spec = get_shmem_capacity_design_spec()
        assert spec.name == "shmem_capacity"
        assert "cudaOccupancyMaxActiveBlocksPerMultiprocessor" in spec.timing_method

    def test_bank_conflict_design_spec(self):
        from src.infrastructure.probing.kernel_templates import get_bank_conflict_design_spec
        spec = get_bank_conflict_design_spec()
        assert spec.name == "bank_conflict"
        assert "strided" in spec.objective.lower()

    def test_shmem_bandwidth_design_spec(self):
        from src.infrastructure.probing.kernel_templates import get_shmem_bandwidth_design_spec
        spec = get_shmem_bandwidth_design_spec()
        assert spec.name == "shmem_bandwidth"
        assert "bandwidth" in spec.objective.lower()

    def test_sm_count_design_spec(self):
        from src.infrastructure.probing.kernel_templates import get_sm_count_design_spec
        spec = get_sm_count_design_spec()
        assert spec.name == "sm_count"
        assert "cudaDeviceGetAttribute" in spec.key_techniques[0]

    def test_get_all_design_specs(self):
        from src.infrastructure.probing.kernel_templates import get_all_design_specs
        specs = get_all_design_specs()
        assert len(specs) == 8
        assert "pointer_chase" in specs
        assert "sm_count" in specs


class TestFallbackSources:
    """Verify fallback CUDA source generation for each probe module."""

    def test_bank_conflict_fallback_source(self):
        from src.infrastructure.probing.bank_conflict import _get_fallback_source
        source = _get_fallback_source(32768)
        assert "clock64()" in source
        assert "__shared__" in source
        assert "bank_conflict" in source.lower()
        assert "cudaGetDeviceProperties" not in source

    def test_clock_measurement_fallback_source(self):
        from src.infrastructure.probing.clock_measurement import _get_fallback_source
        source = _get_fallback_source(10_000_000)
        assert "clock64()" in source
        assert "total_cycles" in source
        assert "cudaGetDeviceProperties" not in source

    def test_shmem_capacity_fallback_source(self):
        from src.infrastructure.probing.shmem_capacity import _get_fallback_source
        source = _get_fallback_source()
        assert "cudaOccupancyMaxActiveBlocksPerMultiprocessor" in source
        assert "sharedMemPerBlock" in source or "sharedMemPerMultiprocessor" in source

    def test_sm_detection_fallback_source(self):
        from src.infrastructure.probing.sm_detection import _get_fallback_source
        source = _get_fallback_source()
        assert "cudaDeviceGetAttribute" in source
        assert "cudaDevAttrMultiProcessorCount" in source
        assert "cudaGetDeviceProperties" not in source

    def test_shmem_bandwidth_fallback_source(self):
        from src.infrastructure.probing.shmem_bandwidth import _get_fallback_source
        source = _get_fallback_source(256)
        assert "__shared__" in source
        assert "shmem" in source.lower()
        assert "iterations" in source

    def test_bandwidth_fallback_source(self):
        from src.infrastructure.probing.bandwidth import _get_fallback_source
        source = _get_fallback_source(32 * 1024 * 1024)
        assert "stream_copy" in source.lower() or "copy" in source.lower()
        assert "bytes_copied" in source or "bytes" in source

    def test_dram_latency_fallback_source(self):
        from src.infrastructure.probing.dram_latency import _get_fallback_source
        source = _get_fallback_source(1024, 10000)
        assert "pointer_chase" in source.lower() or "chase" in source.lower()
        assert "cudaEventElapsedTime" in source or "clock64" in source

    def test_cache_capacity_fallback_source(self):
        from src.infrastructure.probing.cache_capacity import _get_fallback_source
        source = _get_fallback_source(1024 * 1024)
        assert "clock64()" in source or "cudaEventElapsedTime" in source
        assert "cudaGetDeviceProperties" not in source


class TestParseNvccOutput:
    """Verify key:value parsing from probe binary output."""

    def test_parse_simple_key_value(self):
        from src.infrastructure.probing.probe_helpers import parse_nvcc_output
        output = "total_cycles: 12345\niterations: 1000\n"
        result = parse_nvcc_output(output)
        assert result["total_cycles"] == 12345
        assert result["iterations"] == 1000

    def test_parse_float_values(self):
        from src.infrastructure.probing.probe_helpers import parse_nvcc_output
        output = "cycles_per_access: 42.5\n"
        result = parse_nvcc_output(output)
        assert result["cycles_per_access"] == 42.5

    def test_parse_string_values(self):
        from src.infrastructure.probing.probe_helpers import parse_nvcc_output
        output = "method: pointer_chasing\n"
        result = parse_nvcc_output(output)
        assert result["method"] == "pointer_chasing"

    def test_parse_ignores_blank_and_comments(self):
        from src.infrastructure.probing.probe_helpers import parse_nvcc_output
        output = "\n# comment\nvalue: 42\n\n"
        result = parse_nvcc_output(output)
        assert result == {"value": 42}

    def test_parse_empty_output(self):
        from src.infrastructure.probing.probe_helpers import parse_nvcc_output
        result = parse_nvcc_output("")
        assert result == {}


class TestOrchestrator:
    """Test orchestrator logic without GPU."""

    def test_cross_validation_latency_hierarchy(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "dram_latency_cycles": 400,
                "l2_latency_cycles": 40,
                "l1_latency_cycles": 4,
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["latency_hierarchy_valid"] is True

    def test_cross_validation_invalid_hierarchy(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "dram_latency_cycles": 10,
                "l2_latency_cycles": 100,
                "l1_latency_cycles": 4,
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["latency_hierarchy_valid"] is False

    def test_cross_validation_dram_only(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "dram_latency_cycles": 442,
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["dram_latency_plausible"] is True

    def test_cross_validation_implausible_dram_latency(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "dram_latency_cycles": 10,
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["dram_latency_plausible"] is False

    def test_cross_validation_clock_frequency_plausible(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "actual_boost_clock_mhz": 1590,
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["clock_frequency_plausible"] is True

    def test_cross_validation_l2_capacity_plausible(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "l2_cache_size_mb": 4.0,
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["l2_capacity_plausible"] is True

    def test_write_results_json_creates_file(self, tmp_path):
        from src.infrastructure.probing.orchestrator import _write_results_json
        results = {
            "measurements": {"dram_latency_cycles": 442},
            "probe_status": {"dram_latency": "success"},
            "cross_validation": {"dram_latency_plausible": True},
            "evidence_files": [str(tmp_path / "evidence_dram_latency.json")],
        }
        path = str(tmp_path / "results.json")
        _write_results_json(results, path)
        import json
        with open(path) as f:
            data = json.load(f)
        assert data["dram_latency_cycles"] == 442
        assert "methodology" in data
        assert "evidence" in data


class TestProbeHelpers:
    """Test helper functions."""

    def test_sanitize_flags_allows_safe(self):
        from src.infrastructure.probing.probe_helpers import _sanitize_flags
        flags = ["-arch=sm_80", "-O3", "-std=c++14"]
        result = _sanitize_flags(flags)
        assert len(result) == 3

    def test_sanitize_flags_removes_unsafe(self):
        from src.infrastructure.probing.probe_helpers import _sanitize_flags
        flags = ["-arch=sm_80", "`rm -rf /`", "-O3"]
        result = _sanitize_flags(flags)
        assert "-arch=sm_80" in result
        assert "`rm -rf /`" not in result
        assert "-O3" in result


class TestCacheCapacityCliffDetection:
    """Test cliff detection logic."""

    def test_find_cliff_with_clear_jump(self):
        from src.infrastructure.probing.cache_capacity import _find_capacity_cliff
        sweep_data = [
            {"size_bytes": 1_048_576, "size_mb": 1.0, "cycles_per_access": 30.0},
            {"size_bytes": 2_097_152, "size_mb": 2.0, "cycles_per_access": 32.0},
            {"size_bytes": 4_194_304, "size_mb": 4.0, "cycles_per_access": 35.0},
            {"size_bytes": 8_388_608, "size_mb": 8.0, "cycles_per_access": 280.0},
            {"size_bytes": 16_777_216, "size_mb": 16.0, "cycles_per_access": 300.0},
        ]
        cliff_idx = _find_capacity_cliff(sweep_data)
        assert cliff_idx == 3

    def test_find_cliff_no_jump(self):
        from src.infrastructure.probing.cache_capacity import _find_capacity_cliff
        sweep_data = [
            {"size_bytes": 1_048_576, "size_mb": 1.0, "cycles_per_access": 30.0},
            {"size_bytes": 2_097_152, "size_mb": 2.0, "cycles_per_access": 31.0},
        ]
        cliff_idx = _find_capacity_cliff(sweep_data)
        assert cliff_idx >= 0


class TestCrossValidationEnhancements:
    """Enhanced cross-validation checks."""

    def test_sm_family_match_t4(self):
        from src.infrastructure.probing.orchestrator import _check_sm_family_match
        assert _check_sm_family_match(40, "turing_t4") is True

    def test_sm_family_match_t4_wrong_count(self):
        from src.infrastructure.probing.orchestrator import _check_sm_family_match
        assert _check_sm_family_match(20, "turing_t4") is False

    def test_sm_family_match_ampere(self):
        from src.infrastructure.probing.orchestrator import _check_sm_family_match
        assert _check_sm_family_match(108, "ampere_a100") is True

    def test_sm_family_match_unknown_family(self):
        from src.infrastructure.probing.orchestrator import _check_sm_family_match
        assert _check_sm_family_match(50, "custom_gpu") is True

    def test_cross_validation_with_sm_check(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "sm_count": 40,
                "likely_gpu_family": "turing_t4",
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["sm_count_matches_family"] is True

    def test_cross_validation_with_sm_mismatch(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "sm_count": 20,
                "likely_gpu_family": "turing_t4",
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["sm_count_matches_family"] is False


class TestEnhancedCrossValidation:
    """Test new cross-validation checks."""

    def test_sm_count_valid_known_config(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {"sm_count": 40},
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["sm_count_is_known_config"] is True

    def test_sm_count_invalid_unknown_config(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {"sm_count": 999},
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["sm_count_is_known_config"] is False

    def test_l2_capacity_power_of_two(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {"l2_cache_size_mb": 4.0},
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["l2_capacity_is_power_of_two"] is True

    def test_l2_capacity_1_5x_power_of_two(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {"l2_cache_size_mb": 6.0},
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["l2_capacity_is_power_of_two"] is True

    def test_bank_conflict_ratio_bounded(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {"bank_conflict_penalty_ratio": 3.5},
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["bank_conflict_ratio_bounded"] is True

    def test_bank_conflict_ratio_exceeds_warp_size(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {"bank_conflict_penalty_ratio": 35.0},
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["bank_conflict_ratio_bounded"] is False

    def test_shmem_faster_than_dram(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "shmem_bandwidth_gbps": 1500.0,
                "dram_bandwidth_gbps": 300.0,
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["shmem_faster_than_dram"] is True

    def test_shmem_slower_than_dram_fails(self):
        from src.infrastructure.probing.orchestrator import _run_cross_validation
        results = {
            "measurements": {
                "shmem_bandwidth_gbps": 100.0,
                "dram_bandwidth_gbps": 300.0,
            },
            "probe_status": {},
            "cross_validation": {},
        }
        _run_cross_validation(results)
        assert results["cross_validation"]["shmem_faster_than_dram"] is True
        assert results["cross_validation"]["shmem_dram_bw_ratio_plausible"] is True


class TestUnifiedNcuParser:
    """Test unified parse_ncu_gpu_time function."""

    def test_parse_gpu_time_ns_pattern(self):
        from src.infrastructure.probing.probe_helpers import parse_ncu_gpu_time
        result = parse_ncu_gpu_time("gpu_time_ns  42.5")
        assert result == 42.5

    def test_parse_duration_ns_pattern(self):
        from src.infrastructure.probing.probe_helpers import parse_ncu_gpu_time
        result = parse_ncu_gpu_time("Duration (ns) : 1,234.56")
        assert result == 1234.56

    def test_parse_ns_suffix(self):
        from src.infrastructure.probing.probe_helpers import parse_ncu_gpu_time
        result = parse_ncu_gpu_time("some value 99.5ns")
        assert result == 99.5

    def test_parse_returns_none_on_no_match(self):
        from src.infrastructure.probing.probe_helpers import parse_ncu_gpu_time
        result = parse_ncu_gpu_time("no timing info here")
        assert result is None


class TestCodeGeneratorPattern:
    """Test that all probe modules support code_generator parameter."""

    def test_bank_conflict_accepts_code_generator(self):
        import inspect
        from src.infrastructure.probing.bank_conflict import probe_bank_conflict_latency
        sig = inspect.signature(probe_bank_conflict_latency)
        assert "code_generator" in sig.parameters

    def test_clock_measurement_accepts_code_generator(self):
        import inspect
        from src.infrastructure.probing.clock_measurement import probe_actual_clock_frequency
        sig = inspect.signature(probe_actual_clock_frequency)
        assert "code_generator" in sig.parameters

    def test_shmem_capacity_accepts_code_generator(self):
        import inspect
        from src.infrastructure.probing.shmem_capacity import probe_shmem_capacity
        sig = inspect.signature(probe_shmem_capacity)
        assert "code_generator" in sig.parameters

    def test_sm_detection_accepts_code_generator(self):
        import inspect
        from src.infrastructure.probing.sm_detection import probe_sm_count
        sig = inspect.signature(probe_sm_count)
        assert "code_generator" in sig.parameters

    def test_shmem_bandwidth_accepts_code_generator(self):
        import inspect
        from src.infrastructure.probing.shmem_bandwidth import probe_shmem_bandwidth
        sig = inspect.signature(probe_shmem_bandwidth)
        assert "code_generator" in sig.parameters

    def test_bandwidth_accepts_code_generator(self):
        import inspect
        from src.infrastructure.probing.bandwidth import probe_dram_bandwidth
        sig = inspect.signature(probe_dram_bandwidth)
        assert "code_generator" in sig.parameters

    def test_dram_latency_accepts_code_generator(self):
        import inspect
        from src.infrastructure.probing.dram_latency import probe_dram_latency_cycles
        sig = inspect.signature(probe_dram_latency_cycles)
        assert "code_generator" in sig.parameters

    def test_cache_capacity_accepts_code_generator(self):
        import inspect
        from src.infrastructure.probing.cache_capacity import probe_l2_cache_capacity
        sig = inspect.signature(probe_l2_cache_capacity)
        assert "code_generator" in sig.parameters


class TestArchitectureAgnosticCode:
    """Verify all fallback sources are architecture-agnostic."""

    def test_no_hardcoded_sm_values(self):
        from src.infrastructure.probing.sm_detection import _get_fallback_source
        source = _get_fallback_source()
        assert "sm_60" not in source
        assert "sm_70" not in source
        assert "sm_80" not in source
        assert "sm_90" not in source

    def test_no_hardcoded_cache_sizes(self):
        from src.infrastructure.probing.cache_capacity import _get_fallback_source
        source = _get_fallback_source(1024 * 1024)
        assert "4194304" not in source
        assert "8388608" not in source

    def test_no_hardcoded_bandwidth_values(self):
        from src.infrastructure.probing.bandwidth import _get_fallback_source
        source = _get_fallback_source(32 * 1024 * 1024)
        assert "550" not in source
        assert "900" not in source
        assert "1600" not in source
